---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Solución de NetApp con cargas de trabajo de la plataforma de contenedores Red Hat OpenShift gestionadas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los clientes pueden haber «nacido en el cloud» o pueden estar en un momento en su proceso de modernización cuando estén listos para mover algunas cargas de trabajo selectas o todas las cargas de trabajo de sus centros de datos al cloud. Pueden elegir usar contenedores OpenShift gestionados por proveedores y almacenamiento NetApp gestionado por proveedores en la nube para ejecutar sus cargas de trabajo. Deben planificar e implementar los clústeres de contenedores gestionados de Red Hat OpenShift en la nube para un entorno listo para la producción con éxito para sus cargas de trabajo de contenedores. NetApp proporciona ofertas de almacenamiento completamente gestionadas para soluciones Red Hat gestionadas en las tres nubes públicas líderes.

*Amazon FSx para NetApp ONTAP (FSX ONTAP)*

FSX ONTAP ofrece protección de datos, fiabilidad y flexibilidad para puestas en marcha de contenedores en AWS. Trident actúa como el aprovisionador de almacenamiento dinámico para consumir el almacenamiento persistente FSx ONTAP para las aplicaciones con estado de los clientes.

Como ROSA se puede poner en marcha en modo de alta disponibilidad con nodos del plano de control repartidos por varias zonas de disponibilidad, FSx ONTAP también se puede aprovisionar con la opción Multi-AZ que proporciona alta disponibilidad y protección frente a fallos de AZ.

*Google Cloud NetApp Volumes*

Red Hat OpenShift Dedicated es una plataforma de aplicaciones totalmente gestionada que permite crear, implementar y escalar aplicaciones rápidamente en la nube híbrida. Google Cloud NetApp Volumes proporciona volúmenes persistentes que llevan el conjunto completo de funcionalidades de gestión de datos empresariales de ONTAP a las puestas en marcha de OpenShift en Google Cloud.
