---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Astra Control Center, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Propuestas de valor de las soluciones de multicloud híbrido de NetApp para cargas de trabajo de contenedor de Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La mayoría de los clientes no empiezan a crear entornos basados en Kubernetes sin ninguna infraestructura existente. Tal vez sean un centro TECNOLÓGICO tradicional que ejecuta la mayoría de sus aplicaciones empresariales en máquinas virtuales (en grandes entornos VMware, por ejemplo). A continuación, empiezan a crear pequeños entornos basados en contenedores para satisfacer las necesidades de los equipos de desarrollo de aplicaciones modernos. Estas iniciativas suelen comenzar poco a poco y comienzan a ser más generalizadas a medida que los equipos aprenden estas nuevas tecnologías y habilidades, y comienzan a reconocer los muchos beneficios de adoptarlas. La buena noticia para los clientes es que NetApp puede atender las necesidades de ambos entornos. Este conjunto de soluciones para la multinube híbrida con Red Hat OpenShift capacitará a los clientes de NetApp para adoptar tecnologías y servicios de nube modernos sin tener que actualizar toda su infraestructura y organización. Tanto si las aplicaciones y los datos de los clientes están alojados en las instalaciones, en el cloud, ejecutados en máquinas virtuales o en contenedores, NetApp puede proporcionar gestión, protección, seguridad y portabilidad de datos consistentes. Con estas nuevas soluciones, el mismo valor que NetApp ha proporcionado en entornos de centros de datos on-premises durante décadas estará disponible en todo el horizonte de datos de la empresa, sin necesidad de realizar una inversión significativa para rediseñar la herramienta, adquirir nuevas habilidades o crear nuevos equipos. NetApp se encuentra bien posicionado para ayudar a los clientes a resolver estos retos empresariales, independientemente de la fase de su transición al cloud en la que se encuentren.

Multicloud híbrido de NetApp con Red Hat OpenShift:

* Ofrece a los clientes diseños y prácticas validados que demuestran las mejores formas de gestionar, proteger, proteger y migrar sus datos y aplicaciones al utilizar Red Hat OpenShift con soluciones de almacenamiento basadas en NetApp.
* Presente las mejores prácticas para clientes que ejecuten Red Hat OpenShift con almacenamiento de NetApp en entornos VMware, una infraestructura básica o una combinación de ambas opciones.
* Muestra estrategias y opciones tanto para entornos on-premises como en la nube, así como entornos híbridos donde se utilizan ambas.

