---
sidebar: sidebar 
permalink: rhhc/rhhc-versions.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, vmware, ROSA, ACC, Astra Control Center, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Versiones de varios componentes utilizados en la validación de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La solución prueba y valida la migración y la protección de datos centralizada con la plataforma de contenedores OpenShift, OpenShift Advanced Cluster Manager, NetApp ONTAP y Astra Control Center de NetApp.

Los escenarios 1, 2 y 3 de la solución se validaron utilizando las versiones como se muestra en la tabla siguiente:

[cols="25%, 75%"]
|===


| *Componente* | *Versión* 


| *VMware* | VSphere Client versión 8.0.0.10200 VMware ESXi, 8,0.0, 20842819 


| *Hub Cluster* | OpenShift 4.11.34 


| *Clusters de origen y destino* | OpenShift 4.12.9 en las instalaciones y en AWS 


| *Astra Trident de NetApp* | Trident Server y Client 23.04.0 


| *Centro de control de Astra de NetApp* | ACC 22.11.0-82 


| *ONTAP DE NETAPP* | ONTAP 9.12.1 


| *AWS FSx para ONTAP de NetApp* | Zona de acceso única 
|===
El escenario 4 de la solución se validó usando las versiones como se muestra en la tabla siguiente:

[cols="25%, 75%"]
|===


| *Componente* | *Versión* 


| *VMware* | VSphere Client versión 8.0.2.00000
VMware ESXi, 8,0.2, 22380479 


| *Hub Cluster* | OpenShift 4.13.13 


| *Clusters de origen y destino* | OpenShift 4.13.12
En las instalaciones y en Google Cloud 


| *Astra Trident de NetApp* | Trident Server y Client 23.07.0 


| *Centro de control de Astra de NetApp* | ACC 23.07.0-25 


| *ONTAP DE NETAPP* | ONTAP 9.12.1 


| *Cloud Volumes ONTAP* | Un espacio de disponibilidad, nodo único, 9.14.0 
|===