---
sidebar: sidebar 
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html 
keywords: use case, gpfs, nfs 
summary: Utilizamos XCP de NetApp para migrar los datos de GPFS a NFS, de modo que las GPU puedan procesar los datos. Por lo general, la IA procesa datos desde un sistema de archivos de red. 
---
= Informática de alto rendimiento para NFS de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este caso de uso se basa en solicitudes de organizaciones de campo. Algunos clientes de NetApp tienen sus datos en un entorno de computación de alto rendimiento que ofrece análisis de datos para modelos de formación y permite que las organizaciones de investigación obtengan información y comprendan una gran cantidad de datos digitales. Los ingenieros de campo de NetApp necesitan un procedimiento detallado para extraer los datos de GPFS de IBM a NFS. Utilizamos XCP de NetApp para migrar los datos de GPFS a NFS, de modo que las GPU puedan procesar los datos. Por lo general, la IA procesa datos desde un sistema de archivos de red.

Si quiere más información sobre la informática de alto rendimiento para el caso de uso de NFS de ONTAP, una demostración registrada y los resultados de pruebas, consulte https://blog.netapp.com/data-migration-xcp["Uso de XCP para mover datos desde un lago de datos y la informática de alto rendimiento a NFS de ONTAP"^] blog.

Si quiere ver pasos detallados sobre el movimiento de datos de MapR-FS a NFS de ONTAP mediante XCP de NetApp, consulte el apéndice A: GPFS a NFS―pasos detallados en https://www.netapp.com/us/media/tr-4732.pdf["TR-4732: Análisis de Big Data en la inteligencia artificial"^].
