---
sidebar: sidebar 
permalink: xcp/xcp-bp-creating-a-csv-file-from-smb-cifs-share.html 
keywords: csv, data dump 
summary: El comando de esta sección vuelca los datos en formato CSV. Puede sumar la columna size para obtener el tamaño total de los datos. 
---
= Creación de un archivo CSV desde un recurso compartido de SMB/CIFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-specific-date-based-scan-and-copy-of-data.html["Anterior: Exploración específica basada en fecha y copia de datos."]

[role="lead"]
El siguiente comando vuelca los datos en formato CSV. Puede sumar la columna size para obtener el tamaño total de los datos.

....
xcp scan -match "((now-x.atime) / 3600) > 31*day" -fmt "'{}, {}, {}, {}'.format(relpath, name, strftime(x.atime, '%y-%m-%d-%H:%M:%S'), humanize_size(size))" -preserve-atime  >file.csv
....
El resultado debería ser similar a este ejemplo:

....
erase\report_av_fp_cdot_crosstab.csvreport_av_fp_cdot_crosstab.csv20-01-29-10:26:2449.6MiB
....
Para escanear hasta la profundidad de tres subdirectorios y proporcionar el resultado en orden de clasificación, ejecute el `xcp -du` comando y volcar el tamaño en cada nivel de directorio hasta la profundidad de tres subdirectorios.

....
./xcp  scan -du -depth 3 NFS_Server_IP:/source_vol
 
....
Para ordenar la información, vuelque la información en un archivo CSV y ordene la información.

....
xcp scan -match “type == d” -depth 3 -fmt "'{}, {}, {}, {}'.format(name, relpath, size)" NFS_Server_IP:/share > directory_report.csv
....
Se trata de un informe personalizado que utiliza `-fmt` comando. Escanea todos los directorios y vuelca el nombre del directorio, la ruta y el tamaño del directorio en un archivo CSV. Puede ordenar la columna de tamaño de la aplicación de hoja de cálculo.

link:xcp-bp-data-migration-from-7-mode-to-ontap.html["Siguiente: Migración de datos de 7-Mode a ONTAP."]
