---
sidebar: sidebar 
permalink: data-analytics/apache-spark-conclusion.html 
keywords: conclusion 
summary: En esta sección se resume este documento en relación con las soluciones de almacenamiento de NetApp para Apache Spark. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-python-scripts-for-each-major-use-case.html["Anterior: Scripts de Python para cada caso de uso principal."]

[role="lead"]
En este documento, comentamos la arquitectura Apache Spark, los casos de uso de clientes y la cartera de almacenamiento de NetApp en relación a Big Data, análisis modernos e IA, ML y DL. En nuestras pruebas de validación del rendimiento basadas en herramientas de pruebas de rendimiento estándares del sector y la demanda de los clientes, las soluciones de Spark de NetApp demostraron un rendimiento superior en comparación con los sistemas Hadoop nativos. Una combinación de los casos de uso de clientes y los resultados de rendimiento que se presentan en este informe puede ayudarle a elegir la solución Spark adecuada para su puesta en marcha.

link:apache-spark-where-to-find-additional-information.html["Siguiente: Dónde encontrar información adicional."]
