---
sidebar: sidebar 
permalink: data-analytics/apache-spark-target-audience.html 
keywords: audience, data scientist, engineer, devops, cloud administrator, architect 
summary: En esta sección se describe quién podría estar interesado en el contenido de esta solución. 
---
= Público objetivo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-solution-overview.html["Anterior: Descripción general de la solución."]

[role="lead"]
El mundo del análisis y la ciencia de datos tiene múltiples disciplinas DE TECNOLOGÍA y negocio:

* El científico de datos necesita la flexibilidad para poder usar las herramientas y las bibliotecas de elección.
* El ingeniero de datos necesita saber cómo fluyen los datos y dónde residen.
* Un ingeniero de DevOps necesita las herramientas necesarias para integrar nuevas aplicaciones de IA y ML en sus canalizaciones de CI y de CD.
* Los administradores y arquitectos de cloud deben poder configurar y gestionar recursos de cloud híbrido.
* Los usuarios empresariales quieren tener acceso a aplicaciones de análisis, IA, APRENDIZAJE AUTOMÁTICO y aprendizaje profundo.


En este informe técnico, describimos cómo AFF, E-Series, StorageGRID, acceso directo NFS, Apache Spark, Horovod, y Keras ayudan a cada uno de estos papeles a aportar valor a las empresas.

link:apache-spark-solution-technology.html["Siguiente: Tecnología de soluciones."]
