---
sidebar: sidebar 
permalink: data-analytics/bda-ai-customer-challenges.html 
keywords: customer, challenge, data lake, repository, syncing, moving data 
summary: En esta página, se tratan los retos a los que se puede enfrentar un cliente al intentar acceder a los datos desde análisis de Big Data para operaciones de IA. 
---
= Retos del cliente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:bda-ai-introduction.html["Anterior: Introducción."]

[role="lead"]
Los clientes pueden enfrentarse a los siguientes retos al intentar acceder a los datos desde los análisis de Big Data para operaciones de IA:

* Los datos del cliente se encuentran en un repositorio de lago de datos. El lago de datos puede contener diferentes tipos de datos, como datos estructurados, no estructurados, semiestructurados, registros y datos entre equipos. Todos estos tipos de datos deben procesarse en sistemas de IA.
* La IA no es compatible con los sistemas de archivos Hadoop. Una arquitectura de IA típica no puede acceder directamente a los datos de HDFS y HCFS, que deben moverse a un sistema de archivos comprensible para IA (NFS).
* La transferencia de datos sobre el lago de datos a la IA normalmente requiere procesos especializados. La cantidad de datos en el lago de datos puede ser muy grande. Un cliente debe tener un método eficiente, de alto rendimiento y rentable para mover datos a sistemas de IA.
* Sincronizando datos. Si un cliente desea sincronizar datos entre la plataforma de Big Data e IA, en ocasiones los datos procesados mediante la IA se pueden usar con Big Data para su procesamiento analítico.


link:bda-ai-data-mover-solution.html["Siguiente: Solución de movimiento de datos."]
