---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-conclusion.html 
keywords: conclusion 
summary: Basándose en esta validación, los científicos e ingenieros de datos pueden acceder a los datos NFS desde los portátiles SageMaker Jupyter de AWS a través de bloques S3 de Cloud Volumes ONTAP de NetApp. Este método permite acceder y compartir fácilmente los mismos datos desde NFS y S3 sin necesidad de software adicional. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:cdm-fod-data-duality-for-data-scientists-and-other-applications.html["Anterior: Dualidad de datos para científicos de datos y otras aplicaciones."]

[role="lead"]
Basándose en esta validación, los científicos e ingenieros de datos pueden acceder a los datos NFS desde los portátiles SageMaker Jupyter de AWS a través de bloques S3 de Cloud Volumes ONTAP de NetApp. Este método permite acceder y compartir fácilmente los mismos datos desde NFS y S3 sin necesidad de software adicional.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Clasificación de texto usando SageMaker BlazingText
+
https://["https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html"^]

* Compatibilidad de versiones de ONTAP para el almacenamiento de objetos S3
+
https://["https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Abril de 2023 | Versión inicial 
|===