---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-solution-overview.html 
keywords: tr4967, 4967, introduction, overview 
summary: Los científicos e ingenieros de datos a menudo necesitan acceder a los datos almacenados en formato NFS, pero acceder a estos datos directamente desde el protocolo S3 en AWS SageMaker puede resultar difícil, ya que AWS solo admite el acceso a buckets de S3. Sin embargo, ONTAP de NetApp proporciona una solución al habilitar el acceso de protocolo doble para NFS y S3. Con esta solución, los científicos e ingenieros de datos pueden acceder a los datos NFS desde portátiles AWS SageMaker a través de bloques de S3 TB desde Cloud Volumes ONTAP de NetApp. Este método permite acceder y compartir fácilmente los mismos datos desde NFS y S3 sin necesidad de software adicional. 
---
= TR-4967: Gestión de datos en cloud con la dualidad de objetos de archivos de NetApp y AWS SageMaker
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam, NetApp

[role="lead"]
Los científicos e ingenieros de datos a menudo necesitan acceder a los datos almacenados en formato NFS, pero acceder a estos datos directamente desde el protocolo S3 en AWS SageMaker puede resultar difícil, ya que AWS solo admite el acceso a buckets de S3. Sin embargo, ONTAP de NetApp proporciona una solución al habilitar el acceso de protocolo doble para NFS y S3. Con esta solución, los científicos e ingenieros de datos pueden acceder a los datos NFS desde portátiles AWS SageMaker a través de bloques de S3 TB desde Cloud Volumes ONTAP de NetApp. Este método permite acceder y compartir fácilmente los mismos datos desde NFS y S3 sin necesidad de software adicional.
