---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-conclusion.html 
keywords: conclusion 
summary: Este documento proporciona directrices de prácticas recomendadas para el uso de Kafka con almacenamiento de NetApp, como pruebas de certificación Confluent Kafka, resultados de rendimiento, ajuste, conectores Kafka y la función de reequilibrio automático. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:confluent-kafka-sizing.html["Anterior: Ajuste de tamaño."]

[role="lead"]
Este documento proporciona directrices de prácticas recomendadas para el uso del almacenamiento por niveles con fluidez de NetApp, como pruebas de verificación, resultados de rendimiento del almacenamiento por niveles, ajuste, conectores Confluent S3 y la función de equilibrio automático. Teniendo en cuenta las políticas de ILM, el rendimiento fluido con varias pruebas de rendimiento para la verificación y las API S3 estándares del sector, el almacenamiento de objetos StorageGRID de NetApp es una opción óptima para el almacenamiento por niveles fluido.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Qué es Apache Kafka
+
https://["https://www.confluent.io/what-is-apache-kafka/"^]

* Documentación de productos de NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]

* Detalles de los parámetros S3-hunk
+
https://["https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html#s3-configuration-options"^]

* Apache Kafka
+
https://["https://en.wikipedia.org/wiki/Apache_Kafka"^]

* Almacenamiento infinito en plataforma confluente
+
https://["https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/"^]

* Confluent Tiered Storage: Mejores prácticas y ajuste de tamaño
+
https://["https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations"^]

* Conector de receptor Amazon S3 para la plataforma Confluent
+
https://["https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html"^]

* Tamaño de Kafka
+
https://["https://eventsizer.io"]

* Ajuste de tamaño de StorageGRID
+
https://["https://fusion.netapp.com/"^]

* Casos de uso de Kafka
+
https://["https://kafka.apache.org/uses"^]

* Clústeres de Kafka con equilibrio automático en una plataforma con fluidez 6.0
+
https://["https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/"^]

+
https://["https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Diciembre de 2021 | Versión inicial. 
|===