---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-conclusion.html 
keywords: conclusion 
summary: Este documento proporciona las directrices de mejores prácticas para el uso de Dremio con almacenamiento NetApp, incluidas las pruebas de certificación TPCDS, el ajuste y los detalles de uso del cliente. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En conclusión, este informe técnico proporciona información completa sobre la puesta en marcha de q Hybrid Iceberg Lakehouse con Dremio junto con distintas fuentes de datos de las controladoras de almacenamiento de NetApp, incluidas ONTAP S3, NAS y StorageGRID. El proceso de implementación se ejecutó con éxito y se utilizó la herramienta de evaluación comparativa TPC-DS para realizar 99 consultas SQL en las diferentes fuentes de datos. El informe también ha explorado casos de uso de clientes en NetApp, lo que demuestra la versatilidad y la eficacia de Dremio a la hora de satisfacer diversos requisitos empresariales. Además, se examinó un caso de uso específico que involucraba a un cliente de ventas de piezas de automóviles, destacando la aplicación práctica y los beneficios de aprovechar Dremio para el análisis de datos y las perspectivas.

En general, este documento sirve como recurso valioso para comprender la instalación y el uso de Dremio con controladoras de almacenamiento de NetApp, y mostrar sus funciones y el potencial para impulsar la toma de decisiones y la optimización basadas en datos en varios sectores.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Instalación de ZooKeeper
+
https://medium.com/@ahmetfurkandemir/distributed-hadoop-cluster-1-spark-with-all-dependincies-03c8ec616166[]

* Dremio
+
https://docs.dremio.com/current/get-started/cluster-deployments/deployment-models/standalone/standalone-tarball/[]

* Configuración de Dremio con StorageGRID
+
https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/configure-dremio-storagegrid.html#configure-dremio-data-source[]

* Caso de uso de NetApp
+
https://www.dremio.com/customers/netapp/[]


