---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-overview-of-hadoop-data-protection-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: 'Esta sección proporciona una descripción detallada de los casos de uso de protección de datos que constituyen el centro de este documento. En el resto de secciones, se proporcionan más detalles sobre cada caso práctico, como el problema del cliente (escenario), los requisitos y retos, y las soluciones.' 
---
= Descripción general de los casos prácticos de protección de datos de Hadoop
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta sección proporciona una descripción detallada de los casos de uso de protección de datos que constituyen el centro de este documento. En el resto de secciones, se proporcionan más detalles sobre cada caso práctico, como el problema del cliente (escenario), los requisitos y retos, y las soluciones.



== Caso de uso 1: Backup de datos de Hadoop

Para este caso de uso, el volumen NFS de NetApp ayudó a una gran institución financiera a reducir el tiempo de tiempo de backup prolongado de más de 24 horas a tan solo unas pocas horas.



== Caso de uso 2: Backup y recuperación ante desastres del cloud a las instalaciones

Al utilizar Data Fabric con la tecnología de NetApp como elementos básicos, una gran empresa de retransmisión pudo cumplir los requisitos de realizar backups de los datos del cloud en su centro de datos en las instalaciones en función de los diferentes modos de transferencia de datos, como, por ejemplo, bajo demanda, de forma instantánea. O basado en la carga del clúster de Hadoop/Spark.



== Caso de uso 3: Activación de DevTest en datos de Hadoop existentes

Las soluciones de NetApp ayudaron a un distribuidor de música en línea a crear rápidamente varios clústeres de Hadoop con una gestión eficiente del espacio en diferentes sucursales, con el fin de crear informes y ejecutar tareas diarias de DevTest mediante políticas programadas.



== Caso de uso 4: Protección de datos y conectividad multicloud

Un gran proveedor de servicios utilizó el Data Fabric con tecnología de NetApp para proporcionar análisis multicloud a sus clientes de diferentes instancias de cloud.



== Caso de uso 5: Acelerar las cargas de trabajo analíticas

Uno de los mayores bancos de inversión y servicios financieros utilizó la solución de almacenamiento conectado a la red de NetApp para reducir el tiempo de espera de I/o y acelerar su plataforma de análisis financiero cuantitativo.
