---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements 
summary: En esta sección se proporciona un resumen de los casos de uso y las soluciones que ofrece NetApp para satisfacer diversos requisitos de protección de datos de Hadoop. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se proporciona un resumen de los casos de uso y las soluciones que ofrece NetApp para satisfacer diversos requisitos de protección de datos de Hadoop. Gracias al Data Fabric con tecnología de NetApp, los clientes pueden:

* Disponga de la flexibilidad necesaria para elegir las soluciones de protección de datos adecuadas aprovechando las completas funcionalidades de gestión de datos de NetApp y su integración con los flujos de trabajo nativos de Hadoop.
* Reduzca el tiempo necesario para realizar backups en clústeres de Hadoop en casi un 70 %.
* Elimine cualquier efecto en el rendimiento que se pueda obtener gracias a los backups de clústeres de Hadoop.
* Ofrezca protección de datos multicloud y acceso a los datos desde distintos proveedores de cloud simultáneamente a una única fuente de datos de análisis.
* Cree copias de clúster de Hadoop rápidas y con gestión eficiente del espacio mediante la tecnología FlexClone.




== Dónde encontrar información adicional

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Soluciones de análisis de Big Data de NetApp
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* Carga de trabajo de Apache Spark con el almacenamiento de NetApp
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* Soluciones de almacenamiento de NetApp para Apache Spark
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* Apache Hadoop en Data Fabric habilitado por NetApp
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]





== Reconocimientos

* Paul Burland, representante de ventas, ANZ Victoria District Sales, NetApp
* Hoseb Dermanilian, Director de Desarrollo Empresarial de NetApp
* Lee Dorrier, director de MPSG, NetApp
* David Thiessen, ingeniero de sistemas, ANZ Victoria District se, NetApp




== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Enero de 2018 | Versión inicial 


| Versión 2.0 | Octubre de 2021 | Actualizado con el caso de uso n.o 5: Acelere la carga de trabajo analítica 


| Versión 3.0 | Noviembre de 2023 | Se han eliminado los detalles de NIPAM 
|===