---
sidebar: sidebar 
permalink: data-analytics/kafka-ontap-overview.html 
keywords: tr4941, 4941, introduction 
summary: Este documento describe las pruebas de rendimiento para la plataforma Confluent en ONTAP de NetApp mediante un kit de pruebas de rendimiento de almacenamiento por niveles. 
---
= TR-4941: Relaciones con las controladoras de almacenamiento ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, Joe Scott, NetApp Rankesh Kumar, Confluente

[role="lead"]
Para que la plataforma Confluent sea más escalable y elástica, debe poder escalar y equilibrar las cargas de trabajo muy rápidamente. El almacenamiento por niveles permite que el almacenamiento de grandes volúmenes de datos en Confluent sea gestionable reduciendo esta carga operativa.

La idea fundamental es separar el almacenamiento de datos del procesamiento de datos, lo que facilita en gran medida el escalado de cada uno de ellos independientemente.

Cargado con innovaciones líderes en el sector, el software de gestión de datos ONTAP de NetApp proporciona fluidez con muchas ventajas en cualquier lugar en el que residen los datos.

Este documento describe las pruebas de rendimiento para la plataforma Confluent en ONTAP de NetApp mediante un kit de pruebas de rendimiento de almacenamiento por niveles.
