---
sidebar: sidebar 
permalink: data-analytics/kafka-nfs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-nfs-conclusion.html["Anterior: Conclusión."]

[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* ¿Qué es Apache Kafka?
+
https://["https://www.confluent.io/what-is-apache-kafka/"^]

* ¿Qué es el tonto renombrar?
+
https://["https://linux-nfs.org/wiki/index.php/Server-side_silly_rename"^]

* ONATP se lee para aplicaciones de transmisión.
+
https://["https://www.netapp.com/blog/ontap-ready-for-streaming-applications/"^]

* Tonto- renombrar tema con Kafka.
+
https://["https://sbg.technology/2018/07/10/kafka-nfs/"^]

* Documentación de productos de NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]

* ¿Qué es NFS?
+
https://["https://en.wikipedia.org/wiki/Network_File_System"^]

* ¿Qué es la reasignación de particiones Kafka?
+
https://["https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-reassign-overview.html"^]

* ¿Qué es la prueba de rendimiento de OpenMessaging?
+
https://["https://openmessaging.cloud/"^]

* ¿Cómo se migra a un agente de Kafka?
+
https://["https://medium.com/@sanchitbansal26/how-to-migrate-kafka-cluster-with-no-downtime-58c216129058"^]

* ¿Cómo se supervisa a Kafka Broker con Prometheus?
+
https://[]

* Plataforma gestionada para Apache Kafka
+
https://[]

* Compatibilidad con Apache Kafka
+
https://[]

* Servicios de consultoría de Apache Kafka
+
https://[]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Marzo de 2023 | Versión inicial. 
|===