---
sidebar: sidebar 
permalink: data-analytics/kafka-sc-performance-best-practice-guidelines.html 
keywords: best practices, get size, s3 buckets, ethernet links, mtu 
summary: Esta página describe las mejores prácticas para mejorar el rendimiento en esta solución. 
---
= Directrices de mejores prácticas de rendimiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-sc-performance-tests-with-produce-consume-workload-generator.html["Anterior: Pruebas de rendimiento con generador de cargas de trabajo de producción-consumo."]

[role="lead"]
* Para ONTAP, si es posible, UTILICE OBTENER tamaño >=1 MB.
* Aumentando `num.network.threads` y.. `num.io.threads` pulg `server.properties` En los nodos de agente, puede pasar la actividad aumentada de organización en niveles a nivel de S3. Estos resultados son con `num.network.threads` y.. `num.io.threads` establezca el valor 32.
* Los bloques de S3 deben apuntar a ocho constituyentes por agregado del miembro.
* Los enlaces Ethernet que impulsan el tráfico S3 deben usar un MTU de 9k cuando sea posible en el almacenamiento y en el cliente.


link:kafka-sc-conclusion.html["Siguiente: Conclusión."]
