---
sidebar: sidebar 
permalink: data-analytics/sb-4154.html 
keywords:  
summary:  
---
= Análisis de datos moderno: Diferentes soluciones para diferentes estrategias de análisis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este whitepaper describe las estrategias de soluciones de análisis de datos modernas de NetApp. Incluye información sobre los resultados empresariales, retos de los clientes, tendencias tecnológicas, arquitectura heredada de la competencia, flujos de trabajo modernos, casos de uso, sectores, cloud, partners tecnológicos, transmisores de datos, asesor digital de NetApp Active IQ (también conocido como asesor digital), kit de herramientas DataOps de NetApp, Hadoop to Spark, almacenamiento definido por software con NetApp Trident Protect, contenedores, gestión de datos empresariales, archivado y organización en niveles para alcanzar los objetivos de IA y análisis y cómo NetApp modernizan juntos su arquitectura de datos.

link:https://www.netapp.com/pdf.html?item=/media/58015-sb-4154.pdf["Análisis de datos moderno: Diferentes soluciones para diferentes estrategias de análisis"^]
