---
sidebar: sidebar 
permalink: data-analytics/sb-4154.html 
keywords:  
summary:  
---
= Análisis de datos moderno: Diferentes soluciones para diferentes estrategias de análisis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este whitepaper describe las estrategias de soluciones de análisis de datos modernas de NetApp. Incluye detalles sobre los resultados de negocio, retos del cliente, tendencias tecnológicas, arquitectura heredada de la competencia, flujos de trabajo modernos, casos prácticos, sectores, cloud, partners tecnológicos, transmisores de datos, el asesor digital de NetApp Active IQ (también conocido como asesor digital), kit de herramientas DataOps de NetApp, Hadoop to Spark, almacenamiento definido por software con Astra Control de NetApp, contenedores, gestión de datos empresariales, archivado y organización en niveles para conseguir los objetivos de IA y análisis y cómo NetApp y los clientes juntos están modernizando su arquitectura de datos.

link:https://www.netapp.com/pdf.html?item=/media/58015-sb-4154.pdf["Análisis de datos moderno: Diferentes soluciones para diferentes estrategias de análisis"^]
