---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references, history 
summary: Splunk Enterprise es la solución SIEM líder del mercado que impulsa los resultados en los equipos de seguridad, TECNOLOGÍA y DevOps. El uso de Splunk ha aumentado considerablemente en las organizaciones de nuestros clientes. Por lo tanto, es necesario añadir más orígenes de datos y conservar los datos durante un periodo más largo, haciendo hincapié en la infraestructura Splunk. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:stgr-splunkss-single-site-smartstore-performance.html["Anterior: Rendimiento de SmartStore para un único sitio."]

[role="lead"]
Splunk Enterprise es la solución SIEM líder del mercado que impulsa los resultados en los equipos de seguridad, TECNOLOGÍA y DevOps. El uso de Splunk ha aumentado considerablemente en las organizaciones de nuestros clientes. Por lo tanto, es necesario añadir más orígenes de datos y conservar los datos durante un periodo más largo, haciendo hincapié en la infraestructura Splunk.

La combinación de SmartStore de Splunk y StorageGRID de NetApp está diseñada para proporcionar una arquitectura escalable a las organizaciones que consigan un rendimiento de introducción de datos mejorado con el almacenamiento de objetos de SmartStore y StorageGRID, y una mayor escalabilidad para un entorno de Splunk en diversas regiones geográficas.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Recursos de documentación de StorageGRID de NetApp
+
https://www.netapp.com/data-storage/storagegrid/documentation/["https://www.netapp.com/data-storage/storagegrid/documentation/"^]

* Documentación de productos de NetApp
+
https://docs.netapp.com["https://docs.netapp.com"^]

* Documentación de Splunk Enterprise
+
https://docs.splunk.com/Documentation/Splunk["https://docs.splunk.com/Documentation/Splunk"^]

* Splunk Enterprise sobre SmartStore
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore"^]

* Manual de puesta en marcha distribuida de Splunk Enterprise
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview["https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview"^]

* Splunk Enterprise gestiona indizadores y clústeres de indizadores
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| 1.0 | Julio de 2022 | Versión inicial. 
|===