---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references 
summary: Splunk Enterprise es la solución SIEM líder del mercado que impulsa los resultados en los equipos de seguridad, TECNOLOGÍA y DevOps. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Splunk Enterprise es la solución SIEM líder del mercado que impulsa los resultados en los equipos de seguridad, TECNOLOGÍA y DevOps. El uso de Splunk ha aumentado considerablemente en las organizaciones de nuestros clientes. Por lo tanto, es necesario añadir más orígenes de datos y conservar los datos durante un periodo más largo, haciendo hincapié en la infraestructura Splunk.

La combinación de SmartStore de Splunk y StorageGRID de NetApp está diseñada para proporcionar una arquitectura escalable a las organizaciones que consigan un rendimiento de introducción de datos mejorado con el almacenamiento de objetos de SmartStore y StorageGRID, y una mayor escalabilidad para un entorno de Splunk en diversas regiones geográficas.



== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* https://docs.netapp.com/us-en/storagegrid-family/["Recursos de documentación de StorageGRID de NetApp"^]
* https://docs.netapp.com["Documentación de productos de NetApp"^]
* https://docs.splunk.com/Documentation/Splunk["Documentación de Splunk Enterprise"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore["Splunk Enterprise sobre SmartStore"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview["Manual de puesta en marcha distribuida de Splunk Enterprise"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers["Splunk Enterprise gestiona indizadores y clústeres de indizadores"^]

