---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: La solución permite agregar recursos de cómputo, almacenamiento activo o S3 para satisfacer la creciente demanda en términos de cantidad de usuarios o tasa de ingesta en implementaciones de sitios únicos o múltiples. 
---
= Ventajas de esta solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La solución permite agregar recursos de cómputo, almacenamiento activo o S3 para satisfacer la creciente demanda en términos de cantidad de usuarios o tasa de ingesta en implementaciones de sitios únicos o múltiples.

* *Rendimiento.* la combinación de Splunk SmartStore y NetApp StorageGRID proporciona una rápida migración de datos entre bloques activos y depósitos calientes mediante el almacenamiento de objetos. StorageGRID potencia el proceso de migración ofreciendo un rendimiento rápido para grandes cargas de trabajo de objetos.
* *Preparado para varios sitios.* la arquitectura distribuida de StorageGRID permite a Splunk SmartStore ampliar las implementaciones en uno o varios sitios a través de un único espacio de nombres global donde se puede acceder a los datos desde cualquier sitio independientemente de dónde residan.
* *Escalabilidad mejorada.* Escale los recursos de almacenamiento de forma independiente de los recursos informáticos para satisfacer las necesidades y demandas en evolución de su entorno Splunk, con lo que se mejora el TCO.
* *Capacidad.* satisfaga los volúmenes de rápido crecimiento en la implementación de Splunk con StorageGRID mediante el escalado de un espacio de nombres único a más de 560 PB.
* *Disponibilidad de datos.* optimizar la disponibilidad de datos, el rendimiento, la distribución geográfica, la retención, la protección, de almacenamiento y costes con políticas condicionadas por metadatos que pueden adaptarse de forma dinámica a medida que evoluciona el valor de negocio de sus datos.


Aumente el rendimiento con el almacenamiento en caché SmartStore, que es un componente del indizador que gestiona la transferencia de copias de bloques entre el almacenamiento local (activo) y remoto (en caliente). . La solución permite agregar recursos de cómputo, almacenamiento activo o S3 para satisfacer la creciente demanda en términos de cantidad de usuarios o tasa de ingesta en implementaciones de un solo sitio o de varios sitios
