---
sidebar: sidebar 
permalink: data-analytics/tr-4623-link.html 
keywords:  
summary:  
---
= TR-4623: E5700 E-Series de NetApp y Splunk Enterprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mitch Blackburn, NetApp

TR-4623 describe la arquitectura integrada del diseño de E-Series y Splunk de NetApp. Optimizado para un equilibrio de almacenamiento en nodos, fiabilidad, rendimiento, capacidad de almacenamiento y densidad, Este diseño emplea el modelo de nodo de índice en clúster de Splunk, con una mayor escalabilidad y un TCO menor. Separar el almacenamiento de la computación permite escalar cada uno de manera independiente, lo que se traduce en un ahorro del coste derivado del sobreaprovisionamiento entre uno y otro. Además, este documento resume los resultados de las pruebas de rendimiento obtenidos a partir de una herramienta de simulación de eventos de registro de equipos Splunk.

link:https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf["TR-4623: E5700 E-Series de NetApp y Splunk Enterprise"^]
