---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: La solución proporciona los pasos necesarios para instalar Hyper-V en un sistema de almacenamiento de NetApp 
---
= Implementación de Microsoft Hyper-V en almacenamiento de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La plataforma de Windows Server utiliza la función Hyper-V para proporcionar tecnología de virtualización. Hyper-V es uno de los numerosos roles opcionales que se ofrecen con Windows Server.



== Descripción general

La función de Hyper-V nos permite crear y gestionar un entorno informático virtualizado mediante la tecnología de virtualización integrada en Windows Server. La tecnología Hyper-V virtualiza el hardware para proporcionar un entorno en el que puede ejecutar varios sistemas operativos al mismo tiempo en un equipo físico. Hyper-V permite crear y gestionar máquinas virtuales y sus recursos. Cada máquina virtual es un sistema informático aislado y virtualizado que puede ejecutar su propio sistema operativo. Hyper-V proporciona una infraestructura para virtualizar aplicaciones y cargas de trabajo que admite una variedad de objetivos comerciales destinados a mejorar la eficiencia y reducir los costos, lo que es una alternativa perfecta a VMware® vSphere, especialmente cuando las organizaciones buscan la coexistencia de múltiples hipervisores durante las condiciones actuales del mercado.



== Destinatarios

En este documento se describen los procedimientos de arquitectura y puesta en marcha para la configuración del cluster de Hyper-V con los sistemas NetApp ONTAP. La audiencia a la que se dirige este documento incluye ingenieros de ventas, consultores de campo, servicios profesionales, gestores de TECNOLOGÍA, ingenieros de partners, y clientes que desean poner en marcha Hyper-V como hipervisor primario o como alternativa.



== Arquitectura

La arquitectura descrita en este documento incluye específicamente la virtualización de Microsoft® Windows Server® 2022 y Hyper-V®. NetApp recomienda encarecidamente el software de virtualización y el software de gestión de la infraestructura como parte de cada puesta en marcha. La configuración utiliza las prácticas recomendadas para cada componente para permitir una infraestructura fiable de nivel empresarial.



== Resumen de casos de uso

Este documento describe los procedimientos de puesta en marcha y las prácticas recomendadas para configurar el clúster de Hyper-V para que funcione de forma óptima como carga de trabajo en Microsoft Windows Server 2022 mediante los modelos de cabinas ASA y FAS All-Flash de NetApp. El sistema operativo/hipervisor del servidor es Microsoft Windows Server 2022. La guía cubre los sistemas de almacenamiento de NetApp que proporcionan datos a través de protocolos de red de área de almacenamiento (SAN) y almacenamiento conectado a la red (NAS).
