---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  pdf:
    zip-level: 4
    zip-filename: netapp-solutions-pdfs.zip
  internal:
    pdf_enabled: false
  prod:
    pdf:
      zip-level: 4
      zip-filename: netapp-solutions-pdfs.zip
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación de las soluciones de NetApp
    url: index.html
  - section: ai
  - section: containers
  - section: data-access
  - title: Aplicaciones empresariales
    entries:
    - title: SAP Y SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: vmw-sc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: Soluciones FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Soluciones NetApp HCI heredadas
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Cambiar registro
    url: change-log-display.html
  - title: Información sobre las soluciones de NetApp
    url: about.html
  - title: Avisos legales
    url: legal-notices.html
