---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
    lipi_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación de las soluciones de NetApp
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: Aplicaciones empresariales
    entries:
    - title: SAP Y SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: Soluciones FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Soluciones NetApp HCI heredadas
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Cambiar registro
    url: "/change-log-display.html"
  - title: Información sobre las soluciones de NetApp
    url: "/about.html"
  - title: Avisos legales
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Introducción
    links:
    - title: Acerca de este repositorio
      url: about.html
    - title: Historial de cambios
      url: change-log-display.html
    - title: Blogs
      url: blogs.html
    - title: Vídeos y demostraciones
      url: videos.html
    - title: Avisos legales
      url: legal-notices.html
  - title: Páginas de destino de soluciones
    links:
    - title: Inteligencia artificial
      url: ai/index.html
    - title: Contenedores
      url: containers/index.html
    - title: Bases de datos empresariales
      url: databases/index.html
    - title: Análisis de datos moderno
      url: data-analytics/index.html
    - title: Multicloud híbrido de NetApp con VMware
      url: ehc/index.html
    - title: Multicloud híbrido de NetApp con Red Hat
      url: rhhc/index.html
    - title: SAP Y SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
    - title: Virtualización
      url: virtualization/index.html
  - title: Automatización de soluciones
    links:
    - title: Introducción
      url: automation/automation_introduction.html
    - title: Primeros pasos
      url: automation/getting-started.html
    - title: Automatización de solicitudes
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: 'FlexPod: Una solución de NetApp y Cisco'
    links:
    - title: Contenido técnico de soluciones FlexPod
      url: https://docs.netapp.com/us-en/flexpod/
    - title: Página de ventas de FlexPod
      url: https://flexpod.com
    - title: Vídeos y demostraciones
      url: https://tv.netapp.com/search?q=flexpod
    - title: Blogs
      url: https://blog.netapp.com/tag/FlexPod/
  - title: Comentarios
    links:
    - title: Proponer una nueva solución
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: Envíe sus comentarios sobre la solución
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
