---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions.zip
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de las soluciones de NetApp
    url: "/index.html"
  - section: ai
  - section: data-analytics
  - section: cloud
  - section: virtualization
  - section: containers
  - section: databases
  - section: data-access
  - section: automation
  - title: SAP Y SAP HANA
    url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - title: Soluciones FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Cambiar registro
    url: "/change-log-display.html"
  - title: Información sobre las soluciones de NetApp
    url: "/about.html"
  - title: Avisos legales
    url: "/legal-notices.html"
