---
sidebar: sidebar 
permalink: videos.html 
summary: Serie de vídeos y demostraciones donde se analizan las características de muchas de las soluciones de NetApp 
keywords: netapp, solutions, videos, demos 
---
= Soluciones de NetApp: Vídeos y demostraciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
Descripción general de los vídeos y demostraciones en los que se destacan características específicas de muchas de las soluciones de NetApp.

.Inteligencia artificial (IA) y análisis de datos moderno
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["Soluciones de IA de NetApp"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOPS"^]


====
.Aplicaciones y bases de datos empresariales
[#db%collapsible]
====
[Underline]#*Vídeos para bases de datos de código abierto*#

[cols="5a, 5a, 5a"]
|===


 a| 
Puesta en marcha automatizada de PostgreSQL, configuración de replicación de alta disponibilidad/recuperación ante desastres, conmutación por error y resincronización

 a| 
 a| 

|===
[Underline]#*Vídeos para la modernización de Oracle con el cloud híbrido en AWS y FSX*#

[cols="5a, 5a, 5a"]
|===


 a| 
Parte 1: Caso práctico y arquitectura de la solución

 a| 
Parte 2a: Migración de bases de datos desde las instalaciones a AWS mediante reubicación automatizada de PDB con la máxima disponibilidad

 a| 
Parte 2b: Migración de bases de datos desde las instalaciones a AWS mediante la consola BlueXP mediante SnapMirror




 a| 
Parte 3: Configuración automatizada de replicación de alta disponibilidad/recuperación ante desastres de bases de datos, conmutación por error y resincronización

 a| 
Parte 4a: Clonado de bases de datos para desarrollo/pruebas con interfaz de usuario de SnapCenter desde copia replicada en espera

 a| 
Part 4b: Backup, restauración y clonado de bases de datos con la interfaz de usuario de SnapCenter




 a| 
Parte 4c: Backup de bases de datos, restauración con backup y recuperación de aplicaciones SaaS BlueXP

 a| 
 a| 

|===
[Underline]#*Vídeos para la base de datos de SQL Server*#

[cols="5a, 5a, 5a"]
|===


 a| 
Ponga en marcha SQL Server en AWS EC2 mediante Amazon FSX para ONTAP de NetApp

 a| 
Clon de base de datos multi-tenant conectable de Oracle con snapshots de almacenamiento

video::krzMWjrrMb0[youtube,width=360] a| 
Puesta en marcha automatizada de Oracle 19c RAC en FlexPod con Ansible

video::VcQMJIRzhoY[youtube,width=360]
|===
*Estudio de caso*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["SAP en Azure NetApp Files"^]


====
.Multicloud híbrido (HMC)
[#hmc%collapsible]
====
[Underline]#*Vídeos para AWS/VMC*#

[cols="5a, 5a, 5a"]
|===


 a| 
Almacenamiento conectado como invitado de Windows con FSX ONTAP mediante iSCSI

 a| 
Almacenamiento conectado invitado de Linux con FSX ONTAP mediante NFS

 a| 
Ahorro de VMware Cloud en AWS TCO con Amazon FSX para ONTAP de NetApp




 a| 
VMware Cloud en un almacén de datos complementario con Amazon FSX para ONTAP de NetApp

 a| 
Instalación y configuración de VMware HCX para VMC

 a| 
Demostración de migración de VMotion con VMware HCX para VMC y FSxN




 a| 
Demostración de migración en frío con VMware HCX para VMC y FSxN

 a| 
 a| 

|===
[Underline]#*Vídeos para Azure/AVS*#

[cols="5a, 5a, 5a"]
|===


 a| 
Descripción general adicional del almacén de datos de la solución para VMware Azure con Azure NetApp Files

 a| 
Recuperación ante desastres de la solución VMware para Azure con Cloud Volumes ONTAP, SnapCenter y JetStream

 a| 
Demostración de migración en frío con VMware HCX para AVS y ANF




 a| 
Demostración de VMotion con VMware HCX para AVS y ANF

 a| 
Demostración de migración masiva con VMware HCX para AVS y ANF

 a| 

|===
====
.Multicloud híbrido con Red Hat OpenShift
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
DR de ROSA con el servicio Astra Control

 a| 
Integración de FSxN con Astra Trident

 a| 
Failover y failover de aplicaciones en ROSA con FSxN




 a| 
Recuperación de desastres mediante Astra Control Center

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["Véalo en NetAppTV"]
 a| 
 a| 

|===
====
.Virtualización
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["Colección de vídeos de VMware"]


====
.Contenedores/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["Vídeos de NetApp con Google Anthos"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["Vídeos de NetApp con VMware Tanzu"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["Vídeos de NetApp para DevOps"]
* link:containers/rh-os-n_videos_and_demos.html["Vídeos de NetApp con Red Hat OpenShift"]


====
.Automatización de soluciones
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Puesta en marcha automatizada de Oracle 19c RAC en FlexPod con Ansible

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====