---
sidebar: sidebar 
permalink: ehc/aws-storage-options.html 
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo 
summary: El almacenamiento de NetApp se puede vincular al servicio Azure VMware como almacenamiento conectado como invitado o como almacenamiento complementario. 
---
= Amazon Web Services: Opciones para usar el almacenamiento de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El almacenamiento de NetApp se puede conectar a Amazon Web Services como almacenamiento conectado como invitado o como almacenamiento complementario.



== Amazon FSx para NetApp ONTAP (FSx ONTAP) como almacén de datos NFS complementario

Amazon FSx ONTAP proporciona opciones excelentes para poner en marcha y gestionar cargas de trabajo de aplicaciones junto con servicios de archivos, a la vez que se reduce el TCO al facilitar los requisitos de datos a la capa de aplicación. Sea cual sea el caso de uso, elige VMware Cloud en AWS junto con Amazon FSx ONTAP para una rápida materialización de las ventajas de la nube, una infraestructura consistente y operaciones desde on-premises a AWS, portabilidad bidireccional de cargas de trabajo y capacidad y rendimiento de clase empresarial. Es el mismo proceso y procedimientos que ya conoce y que se utilizan para conectar el almacenamiento.

Para obtener más información, visite:

* link:aws-native-overview.html["FSX ONTAP como almacén de datos NFS suplementario: Descripción general"]
* link:aws-native-nfs-datastore-option.html["Amazon FSx para ONTAP como almacén de datos complementario"]




== Amazon FSx para NetApp ONTAP como almacenamiento conectado invitado

Amazon FSx ONTAP es un servicio totalmente gestionado que ofrece un almacenamiento de archivos con muchas funciones, alta fiabilidad, escalabilidad y alto rendimiento basado en el popular sistema de archivos ONTAP de NetApp. FSX ONTAP combina las características, el rendimiento, las funcionalidades y las operaciones de API que ya conoce de los sistemas de archivos de NetApp con la agilidad, la escalabilidad y la simplicidad de un servicio de AWS totalmente gestionado.

FSX ONTAP proporciona un almacenamiento de archivos compartido con muchas funciones, rápido y flexible que es ampliamente accesible desde las instancias de computación de Linux, Windows y macOS que se ejecutan en AWS u on-premises. FSX ONTAP ofrece un almacenamiento en unidades de estado sólido (SSD) de alto rendimiento con latencias inferiores al milisegundo. Con FSx ONTAP, puedes alcanzar niveles de rendimiento en unidad de estado sólido para tu carga de trabajo mientras pagas por el almacenamiento en unidad de estado sólido por solo una pequeña fracción de tus datos.

Gestionar los datos con FSx ONTAP es más fácil, ya que puede instantáneas, clonar y replicar sus archivos con tan solo hacer clic. Además, FSx ONTAP organiza automáticamente en niveles los datos en un almacenamiento elástico de menor coste, lo que reduce la necesidad de aprovisionar o gestionar capacidad.

FSX ONTAP también proporciona almacenamiento duradero y de alta disponibilidad con backups totalmente gestionados y compatibilidad con la recuperación ante desastres entre regiones. Para que sea más fácil proteger y proteger sus datos, FSx ONTAP es compatible con las aplicaciones antivirus y de seguridad de datos más populares.

Si desea más información, visite link:aws-guest.html#fsx-ontap["FSX ONTAP como almacenamiento conectado como invitado"]



== Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado

Cloud Volumes ONTAP, o CVO, es la solución de gestión de datos en el cloud líder del sector que se basa en el software de almacenamiento ONTAP de NetApp, disponible de forma nativa en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform (GCP).

Se trata de una versión de ONTAP definida por software que consume almacenamiento nativo del cloud, lo que le permite tener el mismo software de almacenamiento en el cloud y en las instalaciones, lo que reduce la necesidad de volver a formar al personal INFORMÁTICO en todos los métodos nuevos para gestionar sus datos.

CVO ofrece a los clientes la capacidad de mover datos del perímetro, al centro de datos, al cloud y al backup sin problemas, de tal modo que su cloud híbrido se aúna, todo ello gestionado con una consola de gestión de panel único, Cloud Manager de NetApp.

Gracias al diseño, CVO ofrece un rendimiento extremo y capacidades de gestión de datos avanzadas para satisfacer incluso las aplicaciones más exigentes en el cloud.

Para más información, por favor visite link:aws-guest.html#aws-cvo["CVO como almacenamiento conectado invitado"].
