---
sidebar: sidebar 
permalink: ehc/ehc-solutions.html 
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst 
summary:  
---
= Soluciones de NetApp para VMware en proveedores a hiperescala
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Obtenga más información acerca de las soluciones que NetApp ofrece el entorno de VMware en cada uno de los proveedores a hiperescala, desde la migración de flujos de trabajo, la ampliación o la descarga al cloud, backup/restauración y recuperación ante desastres.



== Soluciones NetApp para entornos VMware

Tanto si opera en un modelo de cloud híbrido como si es un modelo de "primero el cloud", NetApp ofrece una amplia variedad de soluciones destinadas a abordar los casos prácticos más comunes para gestionar cargas de trabajo en un modelo de cloud o de cloud híbrido.

NetApp también ofrece soluciones para el almacenamiento aprovisionado como almacenamiento "invitado" (conectado) o como almacén de datos NFS complementario en cada uno de los proveedores a hiperescala. Todas las soluciones se categorizan al unísono con la clasificación de VMware de las cargas de trabajo del cloud. Estas clasificaciones incluyen:

* Protect (incluye recuperación ante desastres y backup/restauración)
* Migración
* Extender


Para obtener más detalles sobre las soluciones disponibles para cada proveedor a hiperescala, visite:

* link:aws-solutions.html["De NetApp para AWS / VMC"]
* link:azure-solutions.html["De NetApp para Azure / AVS"]
* link:gcp-solutions.html["Soluciones para GCP/GCVE"]

