---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= Resumen y conclusión: Por qué elegir el multicloud híbrido de NetApp con VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud Volumes junto con las soluciones de VMware para los principales proveedores a hiperescala ofrecen un gran potencial para las organizaciones que desean aprovechar el cloud híbrido. El resto de esta sección proporciona los casos de uso que muestran la integración de NetApp Cloud Volumes para ofrecer auténticas funcionalidades de multicloud híbrido.



== Caso de uso n.o 1: Optimización del almacenamiento

Cuando se realiza un ejercicio de configuración con salida RVtools, siempre es evidente que la escala de la potencia (vCPU/vmem) es paralela al almacenamiento. Muchas veces, las organizaciones se encuentran en una situación en la que el espacio de almacenamiento requiere el tamaño del clúster mucho más allá de lo que se necesita para la potencia.

Al integrar Cloud Volumes de NetApp, las organizaciones pueden desarrollar una solución cloud basada en vSphere con un método de migración simple, sin necesidad de volver a plataformas, sin cambios de IP ni cambios de arquitectura. Asimismo, esta optimización le permite escalar el espacio de almacenamiento a la vez que mantiene el número de hosts al menor tiempo necesario en vSphere, pero sin cambios en la jerarquía de almacenamiento, la seguridad ni los archivos que se han puesto a disposición. Esto permite optimizar la puesta en marcha y reducir el TCO general entre un 35 y un 45 %. Esta integración también le permite ampliar el almacenamiento del almacenamiento de datos templados al rendimiento de producción en segundos.



== Caso de uso n.o 2: Migración al cloud

Las organizaciones sufren la presión de migrar aplicaciones desde los centros de datos en las instalaciones al cloud público por varios motivos: Un vencimiento del arrendamiento inminente; una directiva financiera para pasar de gastos de capital a gastos operativos (gastos operativos) o, simplemente, una obligación descendente para trasladarlo todo al cloud.

Cuando la velocidad es crucial, solo es posible utilizar un método de migración optimizado, ya que volver a crear plataformas y refactorizar aplicaciones para adaptarse a la plataforma IaaS en particular del cloud es lenta y cara y, a menudo, lleva meses. Al combinar Cloud Volumes de NetApp con la replicación de SnapMirror con gestión eficiente del ancho de banda para el almacenamiento conectado al «guest» (incluidos RDM en combinación con las copias Snapshot coherentes con las aplicaciones y HCX, la migración específica del cloud (como Azure Migrate) o productos de terceros para replicar máquinas virtuales), esta transición es incluso más fácil que depender de mecanismos de filtros de I/o que requieren tiempo.



== Caso de uso n.o 3: Expansión del centro de datos

Cuando un centro de datos alcanza límites de capacidad debido a los picos de demanda estacionales o simplemente a un crecimiento orgánico constante, cambiar a VMware alojado en cloud junto con Cloud Volumes de NetApp es una solución sencilla. El aprovechamiento de Cloud Volumes de NetApp permite la creación, replicación y expansión del almacenamiento de forma muy sencilla, al proporcionar alta disponibilidad en las zonas de disponibilidad y funcionalidades de escalado dinámico. El aprovechamiento de Cloud Volumes de NetApp ayuda a minimizar la capacidad de clústeres de hosts, ya que permite superar la necesidad de ampliar clústeres.



== Caso de uso n.o 4: Recuperación ante desastres en el cloud

En un enfoque tradicional, si se produce un desastre, las máquinas virtuales replicadas al cloud requerirían la conversión a la propia plataforma de hipervisor de la nube antes de poder restaurarlas, no una tarea que se debe manejar durante una crisis.

Mediante el uso de Cloud Volumes de NetApp para almacenamiento conectado al invitado con la replicación de SnapCenter y SnapMirror desde las instalaciones junto con soluciones de virtualización de cloud público, es posible diseñar un mejor método para la recuperación ante desastres que permita la recuperación de réplicas de equipos virtuales en una infraestructura VMware SDDC totalmente coherente junto con herramientas de recuperación específicas para cloud (Por ejemplo, Azure Site Recovery) o herramientas de terceros equivalentes, como Veeam. Este enfoque también le permite realizar simulacros de recuperación ante desastres y recuperar rápidamente desde el ransomware. Esto también permite escalar a producción completa para pruebas o durante un desastre añadiendo hosts bajo demanda.



== Caso de uso n.o 5: Modernización de aplicaciones

Una vez que las aplicaciones se encuentran en el cloud público, las organizaciones querrán aprovechar los cientos de potentes servicios de cloud para modernizarlas y ampliarlas. Con el uso de Cloud Volumes de NetApp, la modernización es un proceso sencillo, ya que los datos de aplicaciones no están bloqueados en VSAN y permite la movilidad de datos en una amplia variedad de casos de uso, incluido Kubernetes.



== Conclusión

Tanto si su objetivo es llegar a un cloud híbrido como en un cloud all-cloud, NetApp Cloud Volumes ofrece opciones excelentes para poner en marcha y gestionar las cargas de trabajo de las aplicaciones, junto con los servicios de archivos y protocolos de bloques, a la vez que reduce el TCO, pues permite que los requisitos de datos se cumplan sin problemas en la capa de la aplicación.

Sea cual sea el caso de uso, elija su cloud preferido/proveedor a hiperescala junto con Cloud Volumes de NetApp para la realización rápida de las ventajas del cloud, una infraestructura consistente y operaciones en las instalaciones y en varios clouds, la portabilidad bidireccional de las cargas de trabajo, y la capacidad y el rendimiento de nivel empresarial.

Es el mismo proceso y procedimientos que ya conocen y que se utilizan para conectar el almacenamiento. Recuerde que solo la posición de los datos ha cambiado con nuevos nombres; las herramientas y los procesos siguen siendo los mismos y Cloud Volumes de NetApp ayuda a optimizar la puesta en marcha general.
