---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= Configuración del entorno de virtualización en el proveedor de cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Aquí se ofrece información sobre cómo configurar el entorno de virtualización en cada uno de los proveedores a hiperescala compatibles.

[role="tabbed-block"]
====
.AWS/VMC
--
En esta sección se describe cómo configurar y gestionar VMware Cloud en AWS SDDC y utilizarlo en combinación con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP a VMC de AWS.

El proceso de configuración puede dividirse en los siguientes pasos:

* Poner en marcha y configurar VMware Cloud para AWS
* Conecte VMware Cloud a FSX ONTAP


Vea el detalles link:aws/aws-setup.html["Pasos de configuración para VMC"].

--
.Azure / AVS
--
En esta sección se describe cómo configurar y gestionar la solución VMware de Azure y utilizarla en combinación con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento en invitado es el único método compatible para conectar Cloud Volumes ONTAP a la solución VMware Azure.

El proceso de configuración puede dividirse en los siguientes pasos:

* Registre el proveedor de recursos y cree un cloud privado
* Conéctese a una puerta de enlace de red virtual ExpressRoute nueva o existente
* Validar la conectividad de red y acceder al cloud privado


Vea el detalles link:azure/azure-setup.html["Pasos de configuración para AVS"].

--
.GCP/GCVE
--
En esta sección se describe cómo configurar y gestionar GCVE y cómo utilizarlo junto con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP y Cloud Volumes Services a GCVE.

El proceso de configuración puede dividirse en los siguientes pasos:

* Implementar y configurar GCVE
* Active el acceso privado a GCVE


Vea el detalles link:gcp/gcp-setup.html["Pasos de configuración para GCVE"].

--
====