---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= Casos de uso del multicloud híbrido de NetApp con VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Una descripción de los casos de uso que son importantes para la organización TECNOLÓGICA al planificar una puesta en marcha de cloud híbrido o cloud-first.



== Casos de uso populares

Sus casos de uso son:

* Recuperación tras desastres,
* Alojar cargas de trabajo durante el mantenimiento del centro de datos; * explosión rápida en la que se necesitan recursos adicionales más allá de lo aprovisionado en el centro de datos local,
* Ampliación de sitios de VMware,
* Migración rápida al cloud,
* Desarrollo/pruebas, y.
* Modernización de aplicaciones aprovechando tecnologías complementarias de cloud.


A lo largo de esta documentación, las referencias de cargas de trabajo del cloud se detaltarán por medio de casos de uso de VMware. Estos casos de uso son:

* Protect (incluye recuperación ante desastres y backup/restauración)
* Migración
* Extender




=== En el camino hacia la TECNOLOGÍA

La mayoría de las organizaciones se encuentran en un camino hacia la transformación y la modernización. Como parte de este proceso, las empresas intentan aprovechar sus inversiones existentes en VMware al mismo tiempo que aprovechan las ventajas de la nube y exploran las formas de hacer el proceso de migración de la forma más fluida posible. Este enfoque facilita enormemente sus esfuerzos de modernización, ya que los datos ya están en el cloud.

La respuesta más sencilla a este escenario son las ofertas de VMware en cada proveedor a hiperescala. Al igual que Cloud Volumes de NetApp®, VMware proporciona una forma de mover o ampliar los entornos VMware locales a cualquier cloud, lo que le permite conservar activos, habilidades y herramientas existentes en las instalaciones al tiempo que ejecuta cargas de trabajo de forma nativa en el cloud. De este modo se reduce el riesgo, ya que no se producirán interrupciones del servicio ni se necesitarán cambios en la IP, y el equipo DE TECNOLOGÍA podrá utilizar las habilidades y herramientas existentes de la manera en que lo hacen en las instalaciones. Esto puede llevar a migraciones de cloud aceleradas y a una transición mucho más fluida a una arquitectura multicloud híbrida.



=== Descripción de la importancia de las opciones de almacenamiento de NFS suplementario

Mientras que VMware en cualquier cloud ofrece funcionalidades híbridas únicas a todos los clientes, las opciones de almacenamiento NFS suplementario limitadas han restringido su utilidad para las organizaciones con cargas de trabajo que requieren un gran nivel de almacenamiento. Debido a que el almacenamiento está directamente ligado a los hosts, la única forma de escalar el almacenamiento es añadir más hosts, lo cual puede aumentar los costes entre un 35 y un 40 % o más para cargas de trabajo con un uso intensivo del almacenamiento. Estas cargas de trabajo solo necesitan almacenamiento adicional, no una potencia adicional. Pero eso significa pagar por los anfitriones adicionales.

Consideremos este caso:

Un cliente solo necesita cinco hosts para CPU y memoria, pero tiene muchas necesidades de almacenamiento y necesita 12 hosts para satisfacer sus requisitos de almacenamiento. Este requisito acaba realmente a la altura del escalado financiero al tener que comprar la potencia adicional cuando solo necesitan aumentar el almacenamiento.

Cuando planifica la adopción y las migraciones de la nube, siempre es importante evaluar el mejor enfoque y tomar el camino más sencillo que reduzca las inversiones totales. El método más habitual y sencillo para la migración de cualquier aplicación es el realojamiento (también conocido como lift and shift), en el que no hay ningún equipo virtual (VM) ni conversión de datos. Al utilizar Cloud Volumes de NetApp con el centro de datos definido por software (SDDC) de VMware, al tiempo que complementa VSAN, proporciona una opción de elevación y cambio sencilla.
