---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= Opciones de almacenamiento de NetApp para proveedores de cloud público
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Explore las opciones para NetApp como almacenamiento en los tres principales proveedores a hiperescala.

[role="tabbed-block"]
====
.AWS/VMC
--
AWS admite almacenamiento de NetApp con las siguientes configuraciones:

* FSX ONTAP como almacenamiento conectado como invitado
* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* FSX ONTAP como almacén de datos NFS complementario


Vea el detalles link:aws-guest.html["Opciones de almacenamiento de conexión para invitado para VMC"]. Vea el detalles link:aws-native-nfs-datastore-option.html["Opciones suplementarias de almacén de datos de NFS para VMC"].

--
.Azure / AVS
--
Azure admite almacenamiento de NetApp en las siguientes configuraciones:

* Azure NetApp Files (ANF) como almacenamiento conectado como invitado
* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Azure NetApp Files (ANF) como almacén de datos NFS complementario


Vea el detalles link:azure-guest.html["Opciones de almacenamiento de Guest Connect para AVS"]. Vea el detalles link:azure-native-nfs-datastore-option.html["Opciones complementarias de almacén de datos NFS para AVS"].

--
.GCP/GCVE
--
Google Cloud es compatible con almacenamiento de NetApp en las siguientes configuraciones:

* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Google Cloud NetApp Volumes (NetApp Volumes) como almacenamiento conectado de invitado
* Google Cloud NetApp Volumes (NetApp Volumes) como almacén de datos NFS complementario


Ver los detalles link:gcp-guest.html["Opciones de almacenamiento de Guest Connect para GCVE"]. Ver los detalles link:gcp-ncvs-datastore.html["Opciones complementarias de almacén de datos NFS para GCVE"].

Lea más link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Compatibilidad con el almacén de datos de NetApp Volumes de Google Cloud para VMware Engine de Google Cloud (blog de NetApp)"^]sobre o. link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Cómo usar volúmenes de NetApp de Google Cloud como almacenes de datos para el motor de VMware de Google Cloud (blog de Google)"^]

--
====