---
sidebar: sidebar 
permalink: ehc/evs-mount-fsxn-conclusion.html 
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx 
summary: Este artículo proporcionó instrucciones sobre cómo configurar FSx para ONTAP como almacenamiento externo para Amazon EVS para su uso con los protocolos NFS e iSCSI. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento ha proporcionado instrucciones sobre cómo configurar FSx para ONTAP como almacenamiento externo para Amazon EVS para su uso con los protocolos NFS e iSCSI.

Usar FSx for ONTAP como almacenamiento externo para Amazon EVS ofrece claros beneficios operativos y comerciales. Ofrece mayor resiliencia, protección, replicación y rentabilidad de los datos gracias a la tecnología ONTAP, y mantiene el TCO optimizado gracias a la desvinculación de la arquitectura hiperconvergente de VMware. Con FSx for ONTAP, los usuarios de Amazon EVS pueden escalar el almacenamiento sin añadir recursos informáticos ni inflar los costes. Esto aprovecha al máximo el potencial de elasticidad y escalabilidad que ofrece la nube de AWS.

Para obtener más información, lea el anuncio de novedades de Amazon: link:https://aws.amazon.com/about-aws/whats-new/2025/06/amazon-elastic-vmware-service-fsx-netapp-ontap/["Amazon EVS ahora se integra con FSx para ONTAP"] , y el blog de NetApp: link:https://www.netapp.com/blog/amazon-elastic-vmware-service-fsx-ontap/["Amazon EVS anuncia compatibilidad con FSx para ONTAP"] .
