---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funcionalidades de NetApp para Google Cloud Platform GCVE
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Obtén más información sobre las funcionalidades que NetApp aporta a Google Cloud Platform (GCP) Google Cloud VMware Engine (GCVE), desde NetApp como dispositivo de almacenamiento conectado invitado o un almacén de datos NFS complementario para migrar flujos de trabajo, extender/irrumpir a la nube, backup/restauración y recuperación ante desastres.

Para ir a la sección del contenido deseado, seleccione una de las siguientes opciones:

* link:#config["Configuración de GCVE en GCP"]
* link:#datastore["Opciones de almacenamiento de NetApp para GCVE"]
* link:#solutions["Soluciones cloud de NetApp/VMware"]




== Configuración de GCVE en GCP

Al igual que en las instalaciones, la planificación de un entorno de virtualización basado en cloud es crucial para tener un entorno preparado para la producción con éxito a la hora de crear equipos virtuales y migración.

En esta sección se describe cómo configurar y gestionar GCVE y cómo utilizarlo junto con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP y Cloud Volumes Services a GCVE.

El proceso de configuración puede dividirse en los siguientes pasos:

* Implementar y configurar GCVE
* Active el acceso privado a GCVE


Vea el detalles link:gcp-setup.html["Pasos de configuración para GCVE"].



== Opciones de almacenamiento de NetApp para GCVE

El almacenamiento de NetApp se puede utilizar de varias maneras, ya sea como adivinar conectado o como un almacén de datos NFS complementario, en GCP GCVE.

Visite link:ehc-support-configs.html["Opciones de almacenamiento de NetApp admitidas"] si quiere más información.

Google Cloud es compatible con almacenamiento de NetApp en las siguientes configuraciones:

* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Cloud Volumes Service (CVS) como almacenamiento conectado como invitado
* Cloud Volumes Service (CVS) como almacén de datos NFS complementario


Vea el detalles link:gcp-guest.html["Opciones de almacenamiento de Guest Connect para GCVE"].

Más información acerca de link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Soporte de almacén de datos de Cloud Volumes Service de NetApp para Google Cloud VMware Engine (blog de NetApp)"^] o. link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Cómo usar CVS de NetApp como almacenes de datos para Google Cloud VMware Engine (blog de Google)"^]



== Casos de uso de soluciones

Con las soluciones cloud de NetApp y VMware, la puesta en marcha en Azure AVS resulta sencilla en muchos casos de uso. Los casos de ingenieros de sistemas se definen para cada una de las áreas cloud definidas de VMware:

* Protect (incluye recuperación ante desastres y backup/restauración)
* Extender
* Migración


link:gcp-solutions.html["Consulte las soluciones de NetApp para Google Cloud GCVE"]
