---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funcionalidades de NetApp para Google Cloud Platform GCVE
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Obtén más información sobre las funcionalidades que NetApp aporta a Google Cloud Platform (GCP) Google Cloud VMware Engine (GCVE), desde NetApp como dispositivo de almacenamiento conectado invitado o un almacén de datos NFS complementario para migrar flujos de trabajo, extender/irrumpir a la nube, backup/restauración y recuperación ante desastres.

Para ir a la sección del contenido deseado, seleccione una de las siguientes opciones:

* link:#config["Configuración de GCVE en GCP"]
* link:#datastore["Opciones de almacenamiento de NetApp para GCVE"]
* link:#solutions["Soluciones cloud de NetApp/VMware"]




== Configuración de GCVE en GCP

Al igual que en las instalaciones, la planificación de un entorno de virtualización basado en cloud es crucial para tener un entorno preparado para la producción con éxito a la hora de crear equipos virtuales y migración.

En esta sección se describe cómo configurar y gestionar GCVE y cómo utilizarlo junto con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento en invitado es el único método compatible para conectar volúmenes de Cloud Volumes ONTAP y Google Cloud NetApp a GCVE.

El proceso de configuración puede dividirse en los siguientes pasos:

* Implementar y configurar GCVE
* Active el acceso privado a GCVE


Vea el detalles link:gcp-setup.html["Pasos de configuración para GCVE"].



== Opciones de almacenamiento de NetApp para GCVE

El almacenamiento de NetApp se puede utilizar de varias maneras, ya sea como adivinar conectado o como un almacén de datos NFS complementario, en GCP GCVE.

Visite link:ehc-support-configs.html["Opciones de almacenamiento de NetApp admitidas"] si quiere más información.

Google Cloud es compatible con almacenamiento de NetApp en las siguientes configuraciones:

* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Google Cloud NetApp Volumes (NetApp Volumes) como almacenamiento conectado de invitado
* Google Cloud NetApp Volumes (NetApp Volumes) como almacén de datos NFS complementario


Ver los detalles link:gcp-guest.html["Opciones de almacenamiento de Guest Connect para GCVE"]. Ver los detalles link:gcp-ncvs-datastore.html["Opciones complementarias de almacén de datos NFS para GCVE"].

Lea más link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Compatibilidad con el almacén de datos de NetApp Volumes de Google Cloud para VMware Engine de Google Cloud (blog de NetApp)"^]sobre o. link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Cómo usar volúmenes de NetApp de Google Cloud como almacenes de datos para el motor de VMware de Google Cloud (blog de Google)"^]



== Casos de uso de soluciones

Con las soluciones cloud de NetApp y VMware, la puesta en marcha en Azure AVS resulta sencilla en muchos casos de uso. Los casos de ingenieros de sistemas se definen para cada una de las áreas cloud definidas de VMware:

* Protect (incluye recuperación ante desastres y backup/restauración)
* Extender
* Migración


link:gcp-solutions.html["Consulte las soluciones de NetApp para Google Cloud GCVE"]
