---
sidebar: sidebar 
permalink: ehc/gcp-storage-options.html 
keywords: gcp, gcve, gcnv, nfs, supplemental, datastore, vcenter, vmware, cvo, storage, options 
summary: El almacenamiento de NetApp se puede conectar al motor de virtualización de Google Cloud como almacenamiento conectado como invitado o como almacenamiento complementario. 
---
= Google Cloud VMware Engine: Opciones para usar el almacenamiento de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El almacenamiento de NetApp se puede conectar al motor de virtualización de Google Cloud como almacenamiento conectado como invitado o como almacenamiento complementario.



== Google Cloud NetApp Volumes (NetApp Volumes) como almacén de datos NFS complementario

Los clientes que requieren capacidad de almacenamiento adicional en su entorno de Google Cloud VMware Engine (GCVE) pueden utilizar los volúmenes de Google Cloud NetApp para montarlos como almacén de datos NFS complementario. El almacenamiento de datos en Google Cloud NetApp Volumes permite a los clientes replicar entre regiones para protegerlos de más allá.

Si desea más información, visite link:gcp-ncvs-datastore.html["Google Cloud NetApp Volumes (NetApp Volumes) como almacén de datos NFS complementario"]



== CVO de NetApp como almacenamiento conectado de invitado

Cloud Volumes ONTAP, o CVO, es la solución de gestión de datos en el cloud líder del sector que se basa en el software de almacenamiento ONTAP de NetApp, disponible de forma nativa en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform (GCP).

Se trata de una versión de ONTAP definida por software que consume almacenamiento nativo del cloud, lo que le permite tener el mismo software de almacenamiento en el cloud y en las instalaciones, lo que reduce la necesidad de volver a formar al personal INFORMÁTICO en todos los métodos nuevos para gestionar sus datos.

CVO ofrece a los clientes la capacidad de mover datos del perímetro, al centro de datos, al cloud y al backup sin problemas, de tal modo que su cloud híbrido se aúna, todo ello gestionado con una consola de gestión de panel único, Cloud Manager de NetApp.

Gracias al diseño, CVO ofrece un rendimiento extremo y capacidades de gestión de datos avanzadas para satisfacer incluso las aplicaciones más exigentes en el cloud.

Si desea más información, visite link:gcp-guest.html#gcp-cvo["CVO de NetApp como almacenamiento conectado de invitado"]



== Google Cloud NetApp Volumes (NetApp Volumes) como almacenamiento conectado de invitado

Los recursos compartidos de Google Cloud NetApp Volumes se pueden montar desde las máquinas virtuales que se crean en el entorno de VMware Engine. Los volúmenes también pueden montarse en el cliente Linux y asignarse en el cliente Windows porque Google Cloud NetApp Volumes admite los protocolos SMB y NFS. Google Cloud NetApp Volumes puede configurarse en sencillos pasos.

El cloud privado de Google Cloud NetApp Volumes y Google Cloud VMware Engine debe estar en la misma región.

Si desea más información, visite link:gcp-guest.html#gcnv["Google Cloud NetApp Volumes (NetApp Volumes) como almacenamiento conectado de invitado"]
