---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: La seguridad, especialmente en el cloud, donde la infraestructura se encuentra fuera del control de los administradores de almacenamiento, es primordial para confiar en sus datos para ofrecer servicios ofrecidos por los proveedores de cloud. Este documento contiene una información general sobre las ofertas de seguridad que ofrece Google Cloud NetApp Volumes en Google Cloud. 
---
= TR-4918: Información general de seguridad: Google Cloud NetApp Volumes en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Oliver Krause, Justin Parisi, NetApp

[role="lead"]
La seguridad, especialmente en el cloud, donde la infraestructura se encuentra fuera del control de los administradores de almacenamiento, es primordial para confiar en sus datos para ofrecer servicios ofrecidos por los proveedores de cloud. Este documento es una visión general de las ofertas de seguridad que https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud NetApp Volumes ofrece en Google Cloud"^].



== Audiencia de destino

La audiencia de destino de este documento incluye, entre otros, los siguientes roles:

* Proveedores de cloud
* Administradores de almacenamiento
* Arquitectos de almacenamiento
* Recursos sobre el terreno
* Responsables de la toma de decisiones empresariales


Si tiene alguna pregunta sobre el contenido de este informe técnico, consulte la sección link:ncvs-gc-additional-information.html#contact-us["“Contacto”."]

|===
| Abreviatura | Definición 


| NetApp Volumes-SW | Google Cloud NetApp Volumes, NetApp Volumes de tipo de servicio 


| Volúmenes de NetApp: Rendimiento | Servicio Cloud Volume, tipo de servicio NetApp Volumes-Performance 


| SAL |  
|===