---
sidebar: sidebar 
permalink: ehc/ncvs-gc-dual-protocol-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: Google Cloud NetApp Volumes ofrece la posibilidad de compartir los mismos conjuntos de datos tanto con clientes de SMB como NFS al tiempo que mantiene los permisos de acceso de protocolo dual adecuados. Para ello, se coordina la asignación de identidad entre protocolos y se utiliza un servidor LDAP de back-end centralizado para proporcionar las identidades UNIX a los volúmenes de NetApp de Google Cloud. Puede utilizar Windows Active Directory para proporcionar facilidad de uso a los usuarios de Windows y UNIX. 
---
= Protocolo doble/multiprotocolo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes ofrece la posibilidad de compartir los mismos conjuntos de datos tanto con clientes SMB como NFS manteniendo los permisos de acceso adecuados (https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["protocolo dual"^]). Para ello, se coordina la asignación de identidad entre protocolos y se utiliza un servidor LDAP de back-end centralizado para proporcionar las identidades UNIX a los volúmenes de NetApp de Google Cloud. Puede utilizar Windows Active Directory para proporcionar facilidad de uso a los usuarios de Windows y UNIX.



== Control de acceso

* *Compartir controles de acceso.* Determinar qué clientes o usuarios y grupos pueden acceder a un recurso compartido NAS. Para NFS, las reglas y políticas de exportación controlan el acceso del cliente a las exportaciones. Las exportaciones de NFS se gestionan desde la instancia de Google Cloud NetApp Volumes. SMB utiliza recursos compartidos de CIFS/SMB y ACL de uso compartido para proporcionar un control más granular a nivel de usuarios y grupos. Solo puede configurar ACL de nivel compartido de clientes SMB mediante https://library.NetApp.com/ecmdocs/ECMP1401220/html/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html[MMC/Computer Management^] con una cuenta que tenga derechos de administrador en la instancia de volúmenes de NetApp de Google Cloud (consulte la sección link:ncvs-smb.html#cuentas de administrador local/BUILN).
* *Controles de acceso a archivos.* Controle los permisos a nivel de archivo o carpeta y siempre se administran desde el cliente NAS. Los clientes NFS pueden utilizar bits de modo tradicional (rwx) o ACL de NFSv4. Los clientes de SMB aprovechan los permisos NTFS.


El control de acceso de los volúmenes que sirven datos tanto a NFS como a SMB depende del protocolo en uso. Para obtener información sobre los permisos con protocolo dual, consulte la sección “<<Modelo de permisos>>.”



== Asignación de usuarios

Cuando un cliente accede a un volumen, Google Cloud NetApp Volumes intenta asignar el usuario entrante a un usuario válido en la dirección opuesta. Esto es necesario para que se determine el acceso adecuado a través de los protocolos y para garantizar que el usuario que solicita acceso sea realmente lo que afirma ser.

Por ejemplo, si un usuario de Windows llamado `joe` intenta acceder a un volumen con permisos UNIX mediante SMB, los volúmenes de NetApp de Google Cloud realizan una búsqueda para encontrar el usuario UNIX correspondiente `joe` llamado . Si existe uno, los archivos que se escriben en un recurso compartido de SMB como usuario de Windows `joe` aparecen como usuario UNIX `joe` de los clientes NFS.

Como alternativa, si un usuario de UNIX llamado `joe` intenta acceder a un volumen de volúmenes de NetApp de Google Cloud con permisos de Windows, el usuario de UNIX debe poder realizar la asignación a un usuario de Windows válido. De lo contrario, se deniega el acceso al volumen.

Actualmente, sólo se admite Active Directory para la gestión de identidades de UNIX externas con LDAP. Para obtener más información acerca de cómo configurar el acceso a este servicio, consulte https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["Creación de una conexión AD"^].



== Modelo de permisos

Cuando se utilizan configuraciones de protocolo doble, los volúmenes de Google Cloud NetApp utilizan estilos de seguridad para los volúmenes para determinar el tipo de ACL. Estos estilos de seguridad se establecen en función de la especificación del protocolo NAS, o en el caso del protocolo doble, es una opción elegida en el momento de la creación del volumen de Google Cloud NetApp.

* Si solo utiliza NFS, los volúmenes de Google Cloud NetApp Volumes utilizan permisos UNIX.
* Si solo utiliza bloque de mensajes del servidor, los volúmenes de Google Cloud NetApp utilizan permisos NTFS.


Si se crea un volumen de protocolo doble, se puede elegir el estilo de ACL al crear un volumen. Esta decisión debe tomarse en función de la administración de permisos deseada. Si los usuarios gestionan permisos desde clientes de Windows/SMB, seleccione NTFS. Si sus usuarios prefieren usar clientes NFS y chmod/chown, utilice los estilos de seguridad de UNIX.
