---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: La seguridad, especialmente en el cloud, donde la infraestructura se encuentra fuera del control de los administradores de almacenamiento, es primordial para confiar en sus datos para ofrecer servicios ofrecidos por los proveedores de cloud. Este documento contiene una descripción general de las ofertas de seguridad que ofrece Cloud Volumes Service de NetApp en Google Cloud. 
---
= TR-4918: Descripción general de la seguridad: Cloud Volumes Service de NetApp en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Oliver Krause, Justin Parisi, NetApp



== Alcance del documento

La seguridad, especialmente en el cloud, donde la infraestructura se encuentra fuera del control de los administradores de almacenamiento, es primordial para confiar en sus datos para ofrecer servicios ofrecidos por los proveedores de cloud. Este documento ofrece una visión general de las ofertas de seguridad de NetApp https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service proporciona en Google Cloud"^].



== Audiencia de destino

La audiencia de destino de este documento incluye, entre otros, los siguientes roles:

* Proveedores de cloud
* Administradores de almacenamiento
* Arquitectos de almacenamiento
* Recursos sobre el terreno
* Responsables de la toma de decisiones empresariales


Si tiene alguna pregunta sobre el contenido de este informe técnico, consulte la sección link:ncvs-gc-additional-information.html#contact-us["“Contacto”."]

|===
| Abreviatura | Definición 


| CVS-SW | Cloud Volumes Service, tipo de servicio CVS 


| CVS-Performance | Cloud Volume Service, tipo de servicio CVS-Performance 


| SAL |  
|===