---
sidebar: sidebar 
permalink: ehc/ncvs-gc-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: El equipo de Google Cloud NetApp Volumes gestiona los servicios de back-end en Google Cloud y utiliza varias estrategias para proteger la plataforma y evitar el acceso no deseado. 
---
= Operación de servicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El equipo de Google Cloud NetApp Volumes gestiona los servicios de back-end en Google Cloud y utiliza varias estrategias para proteger la plataforma y evitar el acceso no deseado.

Cada cliente obtiene su propia subred única que tiene acceso protegido por los demás clientes de forma predeterminada, y cada inquilino de Google Cloud NetApp Volumes obtiene su propio espacio de nombres y VLAN para aislar totalmente los datos. Una vez autenticado un usuario, el motor de entrega de servicios (SDE) sólo puede leer los datos de configuración específicos de ese arrendatario.



== Seguridad física

Con la aprobación previa adecuada, solo los ingenieros in situ y los ingenieros de soporte de campo (FSE) con insignia de NetApp tienen acceso a la jaula y los racks para trabajar físicamente. La gestión de almacenamiento y redes no está permitida. Solo estos recursos in situ pueden realizar tareas de mantenimiento del hardware.

Para los ingenieros in situ, se crea un ticket para la descripción del trabajo (SOW, Stament ID) que incluye el identificador de rack y la ubicación del dispositivo (RU), y todos los demás detalles se incluyen en la incidencia. En el caso de los FSE de NetApp, es necesario elevar un ticket de visita a las instalaciones con LA COLOCACIÓN y el ticket incluye los detalles, la fecha y la hora del visitante a efectos de auditoría. La Descripción del Trabajo para el FSE se comunica internamente a NetApp.



== Equipo de operaciones

El equipo de operaciones para Google Cloud NetApp Volumes consta de Ingeniería de producción y un ingeniero de fiabilidad del sitio (SRE) para Google Cloud NetApp Volumes e ingenieros de soporte de campo de NetApp y partners para el hardware. Todos los miembros del equipo de operaciones están acreditados por su trabajo en Google Cloud y se mantienen registros detallados del trabajo para cada ticket generado. Además, existe un estricto proceso de control y aprobación de cambios para garantizar que cada decisión sea examinada adecuadamente.

El equipo de SRE gestiona el plano de control y la forma en que se enrutan los datos desde las solicitudes de la interfaz de usuario al hardware y software de back-end en Google Cloud NetApp Volumes. El equipo de SRE también gestiona los recursos del sistema, como los máximos de volumen e inodo. Los SRE no pueden interactuar con los datos del cliente ni tener acceso a ellos. Los Sres también proporcionan coordinación con Autorizaciones de devolución de material (RMA), como solicitudes de sustitución de disco o memoria nuevas para el hardware de backend.



== Responsabilidades del Cliente

Los clientes de Google Cloud NetApp Volumes gestionan el directorio activo y la gestión de las funciones de usuario de su organización, así como las operaciones de volúmenes y datos. Los clientes pueden tener roles administrativos y pueden delegar permisos en otros usuarios finales dentro del mismo proyecto de Google Cloud con las dos funciones predefinidas que proporcionan NetApp y Google Cloud (Administrador y Visor).

El administrador puede asignar cualquier VPC dentro del proyecto del cliente a los volúmenes de Google Cloud NetApp que el cliente determine que es adecuado. Es responsabilidad del cliente gestionar el acceso a su suscripción a Google Cloud Marketplace y gestionar los ordenadores virtuales que tienen acceso al plano de datos.



== Protección frente a SRE maliciosa

Una de las preocupaciones que podría surgir es: ¿Cómo protege Google Cloud NetApp Volumes frente a escenarios en los que hay un SRE malicioso o cuando se han visto comprometidas las credenciales de SRE?

El acceso al entorno de producción es sólo con un número limitado de personas que reciben servicios de salud sexual y reproductiva. Los privilegios administrativos se limitan además a un puñado de administradores con experiencia. Todas las acciones que realiza cualquier persona en el entorno de producción de Google Cloud NetApp Volumes se registran y cualquier anomalía en las actividades básicas o sospechosas es detectada por nuestra plataforma de inteligencia de amenazas de gestión de eventos e información de seguridad (SIEM). Como resultado, es posible realizar un seguimiento y mitigar las acciones maliciosas antes de que se produzcan demasiado daño en el back-end de Google Cloud NetApp Volumes.



== Ciclo de vida de volumen

Google Cloud NetApp Volumes gestiona solo los objetos dentro del servicio, no los datos de los volúmenes. Solo los clientes que acceden a los volúmenes pueden gestionar los datos, las ACL, los propietarios de archivos, etc. Los datos de estos volúmenes están cifrados en reposo y el acceso se limita a los inquilinos de la instancia de Google Cloud NetApp Volumes.

El ciclo de vida de los volúmenes para Google Cloud NetApp Volumes es create-update-delete. Los volúmenes retienen copias Snapshot de los volúmenes hasta que se eliminan los volúmenes. Solo los administradores de volúmenes de Google Cloud NetApp validados pueden eliminar volúmenes en volúmenes de Google Cloud NetApp. Cuando un administrador solicita la eliminación de un volumen, se necesita un paso adicional para introducir el nombre del volumen para verificar la eliminación. Una vez eliminado el volumen, este ya no se puede recuperar.

En los casos en que se finaliza un contrato de Google Cloud NetApp Volumes, NetApp marca volúmenes para su eliminación después de un período de tiempo determinado. Antes de que caduque ese período de tiempo, puede recuperar volúmenes a petición del cliente.



== Certificaciones

Google Cloud NetApp Volumes para Google Cloud cuenta actualmente con la certificación ISO/IEC 27001:2013 e ISO/IEC 27018:2019. El servicio también recibió recientemente su informe de certificación SOC2 de tipo I. Para obtener más información sobre el compromiso de NetApp con la seguridad y privacidad de los datos, consulte https://www.netapp.com/company/trust-center/compliance/["Cumplimiento de normativas: Seguridad y privacidad de los datos"^].



== RGPD

Nuestros compromisos con respecto a la privacidad y el cumplimiento del RGPD están disponibles en diversos de nuestros  https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["contratos con clientes"^], como nuestro https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["Adición al procesamiento de datos del cliente"^], que incluye la  https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["Cláusulas contractuales estándar"^] Proporcionado por la Comisión Europea. También asumimos estos compromisos en nuestra Política de privacidad, respaldada por los valores fundamentales establecidos en nuestro Código de conducta corporativo.
