---
sidebar: sidebar 
permalink: ehc/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: Parte de confiar en una solución cloud es comprender la arquitectura y el modo en el que se protege. En esta sección se presentan distintos aspectos de la arquitectura de Cloud Volumes Service en Google para ayudar a solucionar los posibles problemas relacionados con la seguridad de los datos, así como llamadas a áreas en las que se puedan necesitar pasos de configuración adicionales para obtener la puesta en marcha más segura. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Parte de confiar en una solución cloud es comprender la arquitectura y el modo en el que se protege. En esta sección se presentan distintos aspectos de la arquitectura de Cloud Volumes Service en Google para ayudar a solucionar los posibles problemas relacionados con la seguridad de los datos, así como llamadas a áreas en las que se puedan necesitar pasos de configuración adicionales para obtener la puesta en marcha más segura.

La arquitectura general de Cloud Volumes Service se puede dividir en dos componentes principales: El plano de control y el plano de datos.



== Plano de control

El plano de control en Cloud Volumes Service es la infraestructura de back-end gestionada por los administradores de Cloud Volumes Service y el software de automatización nativo de NetApp. Este plano es completamente transparente para los usuarios finales e incluye redes, hardware de almacenamiento, actualizaciones de software, etc. para ayudar a ofrecer valor a una solución residente en cloud como Cloud Volumes Service.



== Plano de datos

El plano de datos en Cloud Volumes Service incluye los volúmenes de datos reales y la configuración de Cloud Volumes Service general (como el control de acceso, la autenticación de Kerberos, etc.). El plano de datos está totalmente bajo el control de los usuarios finales y de los consumidores de la plataforma Cloud Volumes Service.

Existen diferencias distintas en cómo se asegura y gestiona cada plano. En las siguientes secciones se tratan estas diferencias, empezando por la descripción general de la arquitectura de Cloud Volumes Service.
