---
sidebar: sidebar 
permalink: ehc/ncvs-gc-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp Volumes expone múltiples puertos TCP para servir recursos compartidos de NFS y SMB. 
---
= Servidor de seguridad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes expone múltiples puertos TCP para servir recursos compartidos de NFS y SMB:

* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Puertos necesarios para el acceso NFS"^]
* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Puertos necesarios para el acceso a SMB"^]


Además, SMB, NFS con LDAP incluido Kerberos y configuraciones de protocolo dual requieren acceso a un dominio de Windows Active Directory. Deben estar las conexiones de Active Directory https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes?hl=en_US["configurado"^] por región. Los controladores de dominio de Active Directory (DC) se identifican mediante el uso https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Descubrimiento de DC basado en DNS"^] Utilizando los servidores DNS especificados. Se utiliza cualquiera de los DC devueltos. La lista de centros de datos elegibles se puede limitar especificando un sitio de Active Directory.

Google Cloud NetApp Volumes llega con direcciones IP del rango CIDR asignado con el `gcloud compute address` comando mientras que https://cloud.google.com/architecture/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US["Integrar Google Cloud NetApp Volumes"^]. Puede utilizar este CIDR como direcciones de origen para configurar firewalls entrantes en los controladores de dominio de Active Directory.

Los controladores de dominio de Active Directory deben https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Exponga los puertos a los CIDR de NetApp Volumes de Google Cloud, como se menciona aquí"^].
