---
sidebar: sidebar 
permalink: ehc/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: Parte de confiar en una solución cloud es comprender la arquitectura y el modo en el que se protege. En esta sección se mencionan los diferentes aspectos de la arquitectura de Google Cloud NetApp Volumes en Google con el fin de aliviar las posibles dudas sobre cómo se protegen los datos, así como las áreas en las que puede ser necesario realizar pasos de configuración adicionales para obtener la puesta en marcha más segura. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Parte de confiar en una solución cloud es comprender la arquitectura y el modo en el que se protege. En esta sección se mencionan los diferentes aspectos de la arquitectura de Google Cloud NetApp Volumes en Google con el fin de aliviar las posibles dudas sobre cómo se protegen los datos, así como las áreas en las que puede ser necesario realizar pasos de configuración adicionales para obtener la puesta en marcha más segura.

La arquitectura general de los volúmenes de Google Cloud NetApp se puede dividir en dos componentes principales: El plano de control y el plano de datos.



== Plano de control

El plano de control de Google Cloud NetApp Volumes es la infraestructura de back-end gestionada por los administradores de Google Cloud NetApp Volumes y el software de automatización nativo de NetApp. Este plano es completamente transparente para los usuarios finales e incluye redes, hardware de almacenamiento, actualizaciones de software, etc., para ayudar a ofrecer valor a una solución residente en cloud, como Google Cloud NetApp Volumes.



== Plano de datos

El plano de datos de los volúmenes de Google Cloud NetApp incluye los volúmenes de datos reales y la configuración de volúmenes de Google Cloud NetApp (como el control de acceso, la autenticación de Kerberos, etc.). El plano de datos está bajo el control de los usuarios finales y los consumidores de la plataforma Google Cloud NetApp Volumes.

Existen diferencias distintas en cómo se asegura y gestiona cada plano. En las siguientes secciones se cubren estas diferencias, empezando por una descripción general de la arquitectura de Google Cloud NetApp Volumes.
