---
sidebar: sidebar 
permalink: ehc/ncvs-gc-nas-protocols_overview.html 
keywords: nas, nfs, smb, cifs 
summary: 'Los protocolos NAS incluyen NFS (v3 y v4.1) y SMB/CIFS (2.x y 3.x). Estos protocolos son la forma en que los volúmenes de NetApp permiten el acceso compartido a datos entre varios clientes NAS. Además, los volúmenes de NetApp de Google Cloud pueden proporcionar acceso simultáneo a clientes NFS y SMB/CIFS (protocolo doble) mientras se cumple toda la configuración de identidades y permisos en archivos y carpetas de los recursos compartidos de NAS.' 
---
= Información general sobre los protocolos NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los protocolos NAS incluyen NFS (v3 y v4.1) y SMB/CIFS (2.x y 3.x). Estos protocolos son la forma en que los volúmenes de NetApp permiten el acceso compartido a datos entre varios clientes NAS. Además, los volúmenes de NetApp de Google Cloud pueden proporcionar acceso simultáneo a clientes NFS y SMB/CIFS (protocolo doble) mientras se cumple toda la configuración de identidades y permisos en archivos y carpetas de los recursos compartidos de NAS. Para mantener la mayor seguridad de transferencia de datos posible, Google Cloud NetApp Volumes admite el cifrado de protocolos en tránsito mediante el cifrado SMB y NFS Kerberos 5p.


NOTE: El protocolo doble está disponible con NetApp Volumes-Performance solo.
