---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Astra Trident 
summary: Este documento de referencia proporciona la validación de la puesta en marcha de la solución Anthos con NetApp y está puesto en marcha en entornos de centros de datos múltiples validados por NetApp y nuestros partners de ingeniería. 
---
= NVA-1165: Anthos con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Banu Sundhar y Suresh Thoppay, NetApp

[role="lead"]
Este documento de referencia proporciona la validación de la puesta en marcha de la solución Anthos con NetApp y nuestros partners de ingeniería cuando se pone en marcha en varios entornos de centros de datos. Además, se detalla la integración del almacenamiento con los sistemas de almacenamiento de NetApp, mediante el orquestador de almacenamiento Astra Trident, con el fin de gestionar el almacenamiento persistente. Por último, exploramos y documentamos una serie de validaciones de soluciones y casos de uso reales.



== Casos de uso

La solución Anthos con NetApp está diseñada para ofrecer un valor excepcional a los clientes con los siguientes casos prácticos:

* Es fácil poner en marcha y gestionar el entorno de Anthos puesto en marcha utilizando el proporcionado `bmctl` de metal desnudo o de `gkectl` Herramienta en VMware vSphere.
* Combine la potencia de las cargas de trabajo virtualizadas y de contenedores empresariales con Anthos puesto en vSphere o de forma básica con https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["reconocimiento de la virtualización"^].
* Casos prácticos y de configuración reales que destacan las funciones de Anthos cuando se utiliza con el almacenamiento de NetApp y Astra Trident, el orquestador de almacenamiento de código abierto para Kubernetes.




== Valor empresarial

Las empresas están adoptando cada vez más prácticas de DevOps para crear nuevos productos, acortar los ciclos de lanzamiento y agregar nuevas funciones con rapidez. Debido a su naturaleza ágil innata, los contenedores y microservicios tienen un papel crucial en el soporte de las prácticas de DevOps. Sin embargo, practicar DevOps a escala de producción en un entorno empresarial presenta sus propios retos e impone ciertos requisitos sobre la infraestructura subyacente, como los siguientes:

* Alta disponibilidad en todas las capas de la pila
* Facilidad de los procedimientos de puesta en marcha
* Operaciones y actualizaciones no disruptivas
* Infraestructura programable y impulsada por API para adaptarse a la agilidad de los microservicios
* Multi-tenancy con garantías de rendimiento
* La capacidad de ejecutar cargas de trabajo virtualizadas y en contenedores de forma simultánea
* La capacidad de escalar la infraestructura de forma independiente en función de las demandas de las cargas de trabajo


La solución Anthos con NetApp reconoce estos retos y presenta una solución que ayuda a abordar cada problema implementando la puesta en marcha totalmente automatizada de Anthos en las instalaciones en el entorno de centro de datos que elija el cliente.



== Información general de la tecnología

La solución Anthos con NetApp incluye los siguientes componentes principales:



=== Anthos en el entorno local

Anthos en las instalaciones es una plataforma de Kubernetes empresarial con soporte completo que se puede poner en marcha en el hipervisor VMware vSphere o en una infraestructura básica de su elección.

Para obtener más información sobre Anthos, consulte el sitio web de Anthos que se encuentra https://cloud.google.com/anthos["aquí"^].



=== Sistemas de almacenamiento NetApp

NetApp cuenta con varios sistemas de almacenamiento perfectos para centros de datos empresariales y para puestas en marcha de cloud híbrido. La cartera de NetApp incluye ONTAP, Cloud Volumes ONTAP, Cloud Volumes Service, Azure NetApp Files y FSxN de NetApp para los sistemas de almacenamiento ONTAP de NetApp, todos los cuales pueden proporcionar almacenamiento persistente para aplicaciones en contenedores.

Si quiere más información, visite el sitio web de NetApp https://www.netapp.com["aquí"].



=== Integraciones de almacenamiento de NetApp

Astra Trident es un orquestador de almacenamiento de código abierto y totalmente compatible para contenedores y distribuciones de Kubernetes, incluido Anthos.

Si quiere más información, visite el sitio web de Astra Trident https://docs.netapp.com/us-en/trident/index.html["aquí"].



== Opciones de configuración avanzadas

Esta sección se dedica a personalizaciones que los usuarios del mundo real probablemente tendrían que realizar al implementar esta solución en la producción, como la creación de un registro de imagen privada dedicado o la implementación de instancias de equilibrador de carga personalizadas.



== Matriz de compatibilidad actual para versiones validadas

Consulte https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["aquí"] para conocer la matriz de soporte de versiones validadas.
