---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_advanced.html 
keywords: Advanced Configuration, Load Balancers 
summary: Esta sección se dedica a personalizaciones que los usuarios reales tendrían que realizar al implementar esta solución en la producción, como la implementación de instancias de equilibrador de carga personalizadas. 
---
= Opciones de configuración avanzadas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Normalmente, la solución más fácil de implementar es la mejor, pero, en algunos casos, se requieren personalizaciones avanzadas para cumplir los requisitos o especificaciones de una aplicación específica o del entorno al que se está implementando la solución. Con este fin, la solución Red Hat OpenShift con NetApp permite que las siguientes personalizaciones cumplan estas necesidades.


NOTE: En esta sección hemos documentado algunas opciones de configuración avanzadas, como el uso de equilibradores de carga de terceros o la creación de un registro privado para alojar imágenes de contenedor personalizadas, que son requisitos previos para la instalación de Astra Control Center de NetApp.

En las siguientes páginas encontrará información adicional sobre las opciones de configuración avanzadas validadas en la solución Red Hat OpenShift con NetApp:
