---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_trident_ontap_iscsi.html 
summary: Para habilitar la integración de Trident con el sistema de almacenamiento ONTAP de NetApp, debe crear un back-end que permita la comunicación con el sistema de almacenamiento. 
keywords: Trident, Astra Trident, ONTAP, AFF, FAS, iSCSI 
---
= Configuración de iSCSI de ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Para habilitar la integración de Trident con el sistema de almacenamiento ONTAP de NetApp, debe crear un back-end que permita la comunicación con el sistema de almacenamiento.

. Hay archivos de fondo de ejemplo disponibles en el archivo de instalación descargado en `sample-input` jerarquía de carpetas. Para los sistemas ONTAP de NetApp que proporcionan servicio iSCSI, copie el `backend-ontap-san.json` archivar en el directorio de trabajo y editar el archivo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-san/backend-ontap-san.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-san.json
----
. Edite los valores managementLIF, dataLIF, svm, username y password de este archivo.
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "172.21.224.201",
  "dataLIF": "10.61.181.240",
  "svm": "trident_svm",
  "username": "admin",
  "password": "password"
}
----
. Con este archivo back-end en su lugar, ejecute el siguiente comando para crear su primer back-end.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-san.json
+------------------------+----------------+--------------------------------------+--------+---------+
|          NAME          | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------------+----------------+--------------------------------------+--------+---------+
| ontapsan_10.61.181.241 | ontap-san      | 6788533c-7fea-4a35-b797-fb9bb3322b91 | online |       0 |
+------------------------+----------------+--------------------------------------+--------+---------+
----
. Con el back-end creado, debe crear después una clase de almacenamiento. Al igual que con el backend, existe un archivo de clase de almacenamiento de ejemplo que se puede editar para el entorno disponible en la carpeta de entradas de ejemplo. Cópielo en el directorio de trabajo y realice las modificaciones necesarias para reflejar el backend creado.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. La única edición que se debe realizar en este archivo es definir `backendType` valor asignado al nombre del controlador de almacenamiento desde el back-end recién creado. Observe también el valor del campo de nombre, al que se debe hacer referencia en un paso posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
----
+

NOTE: Hay un campo opcional llamado `fsType` que se define en este archivo. En los back-ends iSCSI, este valor se puede establecer en un tipo de sistema de archivos Linux específico (XFS, ext4, etc.), o se puede eliminar para permitir que el sistema operativo del nodo de trabajo decida qué sistema de ficheros utilizar.

. Ejecute el `kubectl` comando para crear la clase de almacenamiento.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Con la clase de almacenamiento creada, debe crear la primera reclamación de volumen persistente (RVP). Hay una muestra `pvc-basic.yaml` archivo que se puede utilizar para realizar esta acción ubicada también en entradas de ejemplo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. La única edición que se debe realizar en este archivo es asegurarse de que `storageClassName` el campo coincide con el que se acaba de crear. La definición de PVC se puede personalizar aún más según sea necesario para el aprovisionamiento de la carga de trabajo.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Cree el PVC emitiendo el `kubectl` comando. La creación puede tardar un poco de tiempo, según el tamaño del volumen de backup que se esté creando, para que pueda ver el proceso a medida que finalice.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-7ceac1ba-0189-43c7-8f98-094719f7956c   1Gi        RWO            basic-csi      3s
----

