= 
:allow-uri-read: 


. Inicie sesión en el sitio de soporte de NetApp y descargue la versión más reciente de Astra Control Center de NetApp. Para ello, es necesario disponer de una licencia adjunta a su cuenta de NetApp. Después de descargar el tarball, transfiéralo a la estación de trabajo de administración.
+

NOTE: Para empezar con una licencia de prueba de Astra Control, visite https://cloud.netapp.com/astra-register["Sitio de registro de Astra"^].

. Desembale la bola tar y cambie el directorio de trabajo a la carpeta resultante.
+
[listing]
----
[netapp-user@rhel7 ~]$ tar -vxzf astra-control-center-21.08.65.tar.gz
[netapp-user@rhel7 ~]$ cd astra-control-center-21.08.65
----
. Antes de iniciar la instalación, empuje las imágenes de Astra Control Center hasta un registro de imágenes.
+

NOTE: Puede elegir hacer esto con Docker o Podman; en este paso se proporcionan instrucciones para ambos.



[role="tabbed-block"]
====
'''
. Exporte el FQDN del registro con el nombre de organización/espacio de nombres/proyecto como una variable de entorno ‘sector’.
+
[listing]
----
[netapp-user@rhel7 ~]$ export registry=astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra
----
. Inicie sesión en el registro.
+
[listing]
----
[netapp-user@rhel7 ~]$ podman login -u ocp-user -p password --tls-verify=false astra-registry.apps.ocp-vmw.cie.netapp.com
----
+

NOTE: Si está utilizando `kubeadmin` usuario para iniciar sesión en el registro privado y, a continuación, utilizar token en lugar de password - `podman login -u ocp-user -p token --tls-verify=false astra-registry.apps.ocp-vmw.cie.netapp.com`.

+

NOTE: También puede crear una cuenta de servicio, asignar el editor de Registro y/o la función de visor de Registro (en función de si necesita acceso de inserción/extracción) e iniciar sesión en el Registro mediante el token de la cuenta de servicio.

. Cree un archivo de script de shell y pegue el siguiente contenido en él.
+
[listing]
----
[netapp-user@rhel7 ~]$ vi push-images-to-registry.sh

for astraImageFile in $(ls images/*.tar); do
   astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')
   podman tag $astraImage $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
   podman push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
done
----
+

NOTE: Si utiliza certificados que no son de confianza para el registro, edite la secuencia de comandos del shell y utilice `--tls-verify=false` para el comando podman push `podman push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///') --tls-verify=false`.

. Haga que el archivo sea ejecutable.
+
[listing]
----
[netapp-user@rhel7 ~]$ chmod +x push-images-to-registry.sh
----
. Ejecute el script shell.
+
[listing]
----
[netapp-user@rhel7 ~]$ ./push-images-to-registry.sh
----
+
'''
+
'''
. Exporte el FQDN del registro con el nombre de organización/espacio de nombres/proyecto como una variable de entorno ‘sector’.
+
[listing]
----
[netapp-user@rhel7 ~]$ export registry=astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra
----
. Inicie sesión en el registro.
+
[listing]
----
[netapp-user@rhel7 ~]$ docker login -u ocp-user -p password astra-registry.apps.ocp-vmw.cie.netapp.com
----
+

NOTE: Si está utilizando `kubeadmin` usuario para iniciar sesión en el registro privado y, a continuación, utilizar token en lugar de password - `docker login -u ocp-user -p token astra-registry.apps.ocp-vmw.cie.netapp.com`.

+

NOTE: También puede crear una cuenta de servicio, asignar el editor de Registro y/o la función de visor de Registro (en función de si necesita acceso de inserción/extracción) e iniciar sesión en el Registro mediante el token de la cuenta de servicio.

. Cree un archivo de script de shell y pegue el siguiente contenido en él.
+
[listing]
----
[netapp-user@rhel7 ~]$ vi push-images-to-registry.sh

for astraImageFile in $(ls images/*.tar); do
   astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
   docker tag $astraImage $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
   docker push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
done
----
. Haga que el archivo sea ejecutable.
+
[listing]
----
[netapp-user@rhel7 ~]$ chmod +x push-images-to-registry.sh
----
. Ejecute el script shell.
+
[listing]
----
[netapp-user@rhel7 ~]$ ./push-images-to-registry.sh
----
+
'''


====
. A continuación, cargue los certificados TLS del registro de imágenes en los nodos de OpenShift. Para ello, cree un mapa de configuración en `openshift-config` Espacio de nombres mediante los certificados TLS y retome la configuración de la imagen del clúster para garantizar la confianza del certificado.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create configmap default-ingress-ca -n openshift-config --from-file=astra-registry.apps.ocp-vmw.cie.netapp.com=tls.crt

[netapp-user@rhel7 ~]$ oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"default-ingress-ca"}}}' --type=merge
----
+

NOTE: Si está utilizando un registro interno OpenShift con certificados TLS predeterminados del operador Ingress con una ruta, debe seguir el paso anterior para aplicar el parche a los certificados en el nombre de host de la ruta. Para extraer los certificados del operador Ingress, puede utilizar el comando `oc extract secret/router-ca --keys=tls.crt -n openshift-ingress-operator`.

. Cree un espacio de nombres `netapp-acc-operator` Para instalar el operador del Centro de control Astra.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create ns netapp-acc-operator
----
. Cree un secreto con credenciales para iniciar sesión en el registro de imágenes `netapp-acc-operator` espacio de nombres.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create secret docker-registry astra-registry-cred --docker-server=astra-registry.apps.ocp-vmw.cie.netapp.com --docker-username=ocp-user --docker-password=password -n netapp-acc-operator
secret/astra-registry-cred created
----
. Edite el operador del Centro de control Astra CR `astra_control_center_operator_deploy.yaml`, Que es un conjunto de todos los recursos que implementa Astra Control Center. En la CR del operador, busque la definición de despliegue para `acc-operator-controller-manager` E introduzca el FQDN del registro junto con el nombre de la organización tal como se le dio al insertar las imágenes en el registro (en este ejemplo, `astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra`) sustituyendo el texto `ASTRA_IMAGE_REGISTRY` y proporcionar el nombre del secreto en el que acabamos de crear `imagePullSecrets` sección. Verifique otros detalles del operador, guarde y cierre.
+
[listing]
----
[netapp-user@rhel7 ~]$ vim astra_control_center_operator_deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: ASTRA_IMAGE_REGISTRY/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        image: astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra/acc-operator:21.08.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets: [name: astra-registry-cred]
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----
. Cree el operador ejecutando el siguiente comando.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create -f astra_control_center_operator_deploy.yaml
----
. Cree un espacio de nombres dedicado para instalar todos los recursos de Astra Control Center.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create ns netapp-astra-cc
namespace/netapp-astra-cc created
----
. Cree el secreto para acceder al registro de imágenes en ese espacio de nombres.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create secret docker-registry astra-registry-cred --docker-server=astra-registry.apps.ocp-vmw.cie.netapp.com --docker-username=ocp-user --docker-password=password -n netapp-astra-cc

secret/astra-registry-cred created
----
. Edite el archivo CRD de Astra Control Center `astra_control_center_min.yaml` E introduzca el FQDN, los detalles del registro de imágenes, la dirección de correo electrónico del administrador y otros detalles.
+
[listing]
----
[netapp-user@rhel7 ~]$ vim astra_control_center_min.yaml

apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: "NetApp HCG Solutions"
  astraVersion: "21.08.65"
  astraAddress: "astra-control-center.cie.netapp.com"
  autoSupport:
    enrolled: true
  email: "solutions_tme@netapp.com"
  firstName: "NetApp HCG"
  lastName: "Admin"
  imageRegistry:
    name: "astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra"     # use your registry
    secret: "astra-registry-cred"             # comment out if not needed
----
. Cree el Centro de control de Astra CRD en el espacio de nombres creado para él.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc apply -f astra_control_center_min.yaml -n netapp-astra-cc
astracontrolcenter.astra.netapp.io/astra created
----



NOTE: El archivo anterior `astra_control_center_min.yaml` Es la versión mínima de Astra Control Center CRD. Si desea crear el CRD con más control, como definir un storagegrid que no sea el predeterminado para crear RVP o proporcionar detalles SMTP para las notificaciones por correo, puede editar el archivo `astra_control_center.yaml`, Introduzca los detalles necesarios y utilícela para crear el CRD.
