---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= Descripción general de VMware Sovereign Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El concepto de soberanía se está convirtiendo en un componente necesario del cloud computing para muchas entidades que procesan y mantienen datos altamente confidenciales, como los gobiernos nacionales y estatales, y sectores altamente regulados, como las finanzas y la sanidad. Los gobiernos nacionales también buscan expandir la funcionalidad económica digital y reducir la dependencia de empresas multinacionales para sus servicios de cloud.



== Iniciativa de cloud soberano de VMware

VMware define un cloud soberano como uno que:

* Protege y libera el valor de los datos críticos (por ejemplo, datos nacionales, corporativos y datos personales) para organizaciones del sector privado y público
* Ofrece una funcionalidad nacional para la economía digital
* Protege los datos con controles de seguridad auditados
* Garantiza el cumplimiento de leyes de privacidad de datos
* Mejora el control de los datos al proporcionar tanto la residencia de datos como la soberanía de datos con un control jurisdiccional total




== Asociación con un proveedor de servicios cloud soberano de VMware de confianza

Para garantizar el éxito, las organizaciones deben trabajar con partners en los que confíen y que sean capaces de alojar plataformas de cloud soberano auténticas y autónomas. Los proveedores de nube de VMware reconocidos dentro de la iniciativa VMware Sovereign Cloud se comprometen a diseñar y operar soluciones de nube basadas en arquitecturas modernas y definidas por software que incorporan los principios clave y las mejores prácticas descritas en el marco de VMware Sovereign Cloud.

* *Soberanía de datos y control jurisdiccional* – Todos los datos son residentes y están sujetos al control exclusivo y autoridad del estado nacional donde se recopilaron esos datos. Las operaciones se gestionan completamente dentro de la jurisdicción
* *Acceso e integridad de datos* – La infraestructura en la nube es resiliente y está disponible en al menos dos ubicaciones de centros de datos dentro de la jurisdicción con opciones de conectividad seguras y privadas disponibles.
* *Seguridad y cumplimiento de datos* – Los controles del sistema de gestión de la seguridad de la información están certificados según un estándar global (o regional) reconocido por la industria y se auditan regularmente.
* * Independencia de datos y movilidad *: Soporte para arquitecturas de aplicaciones modernas para evitar el bloqueo en la nube de proveedores y permitir la portabilidad e independencia de las aplicaciones


Para obtener más información de VMware, visite:

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["Descripción general de la nube soberana de VMware"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["¿Qué es VMware Sovereign Cloud?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["Presentamos la nueva iniciativa VMware Sovereign Cloud"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["Whitepaper técnico de VMware Sovereign Cloud"]

