---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= NetApp con VMware Sovereign Cloud: Casos de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ofrece compatibilidad con los conceptos de nube soberana de VMware mediante la integración de varias tecnologías de NetApp.

Utilice los siguientes enlaces para obtener más información acerca de las integraciones de la tecnología de NetApp con VMware Sovereign Cloud:

* link:#storageGRID["NetApp StorageGRID como extensión de almacén de objetos"]




== NetApp StorageGRID como extensión de almacén de objetos

NetApp ha colaborado con VMware para integrar NetApp StorageGRID en VMware Cloud Director en apoyo de la nube soberana de VMware. Este complemento para VMware Cloud Director permite que los proveedores de servicios utilicen StorageGRID como su oferta de almacenamiento de objetos (independientemente del caso de uso) y permite la gestión de StorageGRID mediante la misma solución multi-tenant de VMware (Cloud Director de VMware) utilizada por los proveedores de servicios para gestionar otras partes de su catálogo de ofertas.

Los partners que ofrecen clouds soberanos de VMware pueden elegir NetApp StorageGRID para que les ayude a gestionar y mantener los entornos de cloud con datos no estructurados. Su compatibilidad universal en su compatibilidad nativa con API estándar del sector, como la API de Amazon S3, ayuda a garantizar una interoperabilidad fluida entre diversos entornos de cloud, así como innovaciones únicas, como la gestión automatizada del ciclo de vida, ayudan a garantizar una protección y un almacenamiento más rentables y una conservación a largo plazo de los datos no estructurados de los clientes.

Integración del cloud soberano de NetApp con los proveedores de Cloud Director clientes con:

* Garantía de que los datos confidenciales, incluidos los metadatos, permanecen bajo control soberano al tiempo que impiden el acceso por parte de autoridades extranjeras que podrían violar las leyes de privacidad de los datos.
* Mayor seguridad y cumplimiento de normativas que protege las aplicaciones y los datos de los vectores de ataque en rápida evolución, a la vez que mantiene un cumplimiento continuo con un local de confianza. de infraestructura, marcos incorporados y expertos locales.
* Infraestructura preparada para el futuro que reacciona con rapidez a los cambios en las normativas de privacidad de datos, las amenazas de seguridad y la política geográfica.
* La capacidad de desbloquear el valor de los datos con análisis y uso compartido de datos seguros para impulsar la innovación sin infringir las leyes de privacidad. La integridad de los datos está protegida para garantizar la precisión de la información.


Si quiere más información sobre la integración de StorageGRID, consulte lo siguiente:

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["Anuncio de NetApp"]

