---
sidebar: sidebar 
permalink: containers/a-w-n_overview_storint.html 
keywords: Trident, Trident, persistent storage 
summary: NetApp proporciona una serie de productos que ayudan a nuestros clientes a orquestar y gestionar datos persistentes en entornos basados en contenedores como Anthos. 
---
= Descripción general de integración del almacenamiento de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp proporciona una serie de productos que ayudan a nuestros clientes a orquestar y gestionar datos persistentes en entornos basados en contenedores como Anthos.



== Programa para partners de almacenamiento Anthos Ready.

Google Cloud solicita periódicamente una validación actualizada de las integraciones de almacenamiento de partners con los nuevos lanzamientos de Anthos a través de su programa para partners de almacenamiento Anthos Ready. Encontrará una lista de las soluciones de almacenamiento validadas actualmente, los controladores CSI, las funciones disponibles y las versiones de Anthos admitidas https://cloud.google.com/anthos/docs/resources/partner-storage["aquí"^].

NetApp ha mantenido el cumplimiento trimestral con solicitudes para validar nuestro orquestador de almacenamiento conforme a la normativa CSI de Trident y nuestro sistema de almacenamiento ONTAP con versiones de Anthos.

La siguiente tabla contiene las versiones de Anthos probadas por los ingenieros de partners de NetApp y NetApp para la validación de los controladores CSI de NetApp Trident y los conjuntos de funciones como parte del programa para partners de almacenamiento Anthos Ready:

|===


| Tipo de puesta en marcha | Versión | Sistema de almacenamiento | Versión de Trident | Protocolo | Funciones 


| VMware | 1,28 | ONTAP 9.12.1 | 24,02 | NAS | Multiwriter, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1,28 | ONTAP 9.12.1 | 24,02 | SAN | Bloque sin procesar, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23,04 | NAS | Multiwriter, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23,04 | SAN | Bloque sin procesar, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | Multiwriter, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | Bloque sin procesar, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | Multiwriter, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | Bloque sin procesar, expansión de volumen, instantáneas, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | Multiwriter, expansión de volumen, instantáneas 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | Bloque bruto, expansión de volumen, snapshots 


| VMware | 1.11 | Elemento 12.3 | 22.04 | SAN | Bloque bruto, expansión de volumen, snapshots 


| nativo | 1.10 | ONTAP 9.8 | 22.01 | NAS | Multiwriter, expansión de volumen, instantáneas 


| nativo | 1.10 | ONTAP 9.8 | 22.01 | SAN | Bloque bruto, expansión de volumen, snapshots 
|===


== Integraciones de almacenamiento de NetApp

NetApp proporciona una serie de productos que le ayudan a orquestar y gestionar datos persistentes en entornos basados en contenedores como Anthos.

NetApp Trident es un orquestador de almacenamiento de código abierto totalmente compatible para contenedores y distribuciones de Kubernetes, entre los que se incluye Anthos. Para obtener más información, visite el sitio web de Trident https://docs.netapp.com/us-en/trident/index.html["aquí"] .

Las siguientes páginas contienen información adicional sobre los productos de NetApp que se han validado para la gestión de aplicaciones y almacenamiento persistente en la solución Anthos con NetApp.
