---
sidebar: sidebar 
permalink: containers/rh-os-n_overview_advanced.html 
keywords: Advanced Configuration, Load Balancers, Custom Registry 
summary: Esta sección se dedica a personalizaciones que los usuarios del mundo real probablemente deban realizar al implementar esta solución en la producción, como la creación de un registro de imagen dedicado o la implementación de instancias personalizadas de equilibrador de carga. 
---
= Opciones de configuración avanzadas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Normalmente, la solución más fácil de implementar es la mejor, pero, en algunos casos, se requieren personalizaciones avanzadas para cumplir los requisitos o especificaciones de una aplicación específica o del entorno al que se está implementando la solución. Con este fin, la solución Red Hat OpenShift con NetApp permite que las siguientes personalizaciones cumplan estas necesidades.


NOTE: En esta sección hemos documentado algunas opciones de configuración avanzadas, como el uso de equilibradores de carga de terceros o la creación de un registro privado para alojar imágenes de contenedor personalizadas, ambos requisitos previos para instalar NetApp Trident Protect.

En las siguientes páginas encontrará información adicional sobre las opciones de configuración avanzadas validadas en la solución Red Hat OpenShift con NetApp:

* link:rh-os-n_load_balancers.html["Exploración de las opciones de equilibrio de carga"]
* link:rh-os-n_private_registry.html["Configuración de registros de imágenes privadas"]

