---
sidebar: sidebar 
permalink: containers/rh-os-n_trident_element_iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= Configuración de iSCSI de NetApp Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Para habilitar la integración de Trident con el sistema de almacenamiento NetApp Element, debe crear un back-end que permita la comunicación con el sistema de almacenamiento mediante el protocolo iSCSI.

. Hay archivos de fondo de ejemplo disponibles en el archivo de instalación descargado en `sample-input` jerarquía de carpetas. Para sistemas NetApp Element que sirven iSCSI, copie el `backend-solidfire.json` archivar en el directorio de trabajo y editar el archivo.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. Edite el valor de usuario, contraseña y MVIP de en el `EndPoint` línea.
.. Edite el `SVIP` valor.
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. Con este archivo back-end en su sitio, ejecute el siguiente comando para crear su primer back-end.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Con el back-end creado, debe crear después una clase de almacenamiento. Al igual que con el backend, existe un archivo de clase de almacenamiento de ejemplo que se puede editar para el entorno disponible en la carpeta de entradas de ejemplo. Cópielo en el directorio de trabajo y realice las modificaciones necesarias para reflejar el backend creado.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. La única edición que se debe realizar en este archivo es definir `backendType` valor asignado al nombre del controlador de almacenamiento desde el back-end recién creado. Observe también el valor del campo de nombre, al que se debe hacer referencia en un paso posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: Hay un campo opcional llamado `fsType` que se define en este archivo. En los back-ends de iSCSI, este valor se puede establecer en un tipo de sistema de archivos de Linux específico (XFS, ext4, etc.), o se puede eliminar para permitir a OpenShift decidir qué sistema de archivos utilizar.

. Ejecute el `oc` comando para crear la clase de almacenamiento.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Con la clase de almacenamiento creada, debe crear la primera reclamación de volumen persistente (RVP). Hay una muestra `pvc-basic.yaml` archivo que se puede utilizar para realizar esta acción ubicada también en entradas de ejemplo.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. La única edición que se debe realizar en este archivo es asegurarse de que `storageClassName` el campo coincide con el que se acaba de crear. La definición de PVC se puede personalizar aún más según sea necesario para el aprovisionamiento de la carga de trabajo.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Cree el PVC emitiendo el `oc` comando. La creación puede tardar un poco de tiempo, según el tamaño del volumen de backup que se esté creando, para que pueda ver el proceso a medida que finalice.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----


link:rh-os-n_use_cases.html["Siguiente: Casos prácticos y validación de la solución."]
