---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_rosa_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, ROSA, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift Virtualization en ROSA 
---
= Implemente Red Hat OpenShift Virtualization con FSxN en ROSA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se proporcionan detalles para configurar FSx para NetApp ONTAP como la clase de almacenamiento predeterminada para el clúster ROSA y, a continuación, crear una máquina virtual que aproveche el almacenamiento FSx ONTAP para sus volúmenes. También examinaremos la conexión a la máquina virtual mediante las credenciales de invitado y el reinicio de la máquina virtual. Y finalmente, realizaremos una migración en vivo de la Máquina Virtual desde el nodo actual a un nuevo nodo. Examinaremos el contenido del almacenamiento en disco tras el reinicio de una máquina virtual y la migración dinámica.



== Requisitos previos

* link:https://signin.aws.amazon.com/signin?redirect_uri=https://portal.aws.amazon.com/billing/signup/resume&client_id=signup["Cuenta de AWS"]
* link:https://console.redhat.com/["Una cuenta de Red Hat"]
* Usuario de IAM link:https://www.rosaworkshop.io/rosa/1-account_setup/["con los permisos adecuados"]para crear y acceder al clúster ROSA
* link:https://aws.amazon.com/cli/["CLI DE AWS"]
* link:https://console.redhat.com/openshift/downloads["ROSA CLI"]
* link:https://console.redhat.com/openshift/downloads["Interfaz de línea de comandos de OpenShift"] (oc)
* link:https://docs.aws.amazon.com/eks/latest/userguide/helm.html["Documentación de HELM 3"]
* link:https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html["UN GRUPO DE HCP ROSA"] (con al menos 3 nodos de trabajo con configuración básica)
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/installing#virt-aws-bm_preparing-cluster-for-virt["OpenShift Virtualization instalado en ROSA Cluster"]
* link:https://console.redhat.com/openshift/overview["Acceso a la consola web de Red Hat OpenShift"]

