---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_prerequisites.html 
keywords: OpenShift, OCP, Astra Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: OpenShift Virtualization de Red Hat con ONTAP de NetApp 
---
= Ponga en marcha Red Hat OpenShift Virtualization con ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se detalla cómo implementar Red Hat OpenShift Virtualization con NetApp ONTAP.



== Requisitos previos

* Un clúster de Red Hat OpenShift (posterior a la versión 4.6) instalado en una infraestructura con configuración básica con nodos de trabajo RHCOS
* El clúster OpenShift debe instalarse a través de la infraestructura aprovisionada por el instalador (IPI).
* Ponga en marcha comprobaciones de estado de la máquina para mantener la alta disponibilidad de las máquinas virtuales
* Un clúster ONTAP de NetApp
* Astra Trident se ha instalado en el clúster OpenShift
* Un back-end de Trident configurado con una SVM en un clúster de ONTAP
* Un StorageClass configurado en el clúster OpenShift con Astra Trident como aprovisionador
* Acceso de administrador de clúster al clúster de Red Hat OpenShift
* Acceso de administrador al clúster de ONTAP de NetApp
* Una estación de trabajo de administración con herramientas trimentctl y oc instaladas y agregadas a $PATH


Puesto que OpenShift Virtualization es gestionado por un operador instalado en el clúster OpenShift, impone gastos adicionales en memoria, CPU y almacenamiento, que se deben tener en cuenta al planificar los requisitos de hardware para el clúster. Consulte la documentación https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt["aquí"] para obtener más detalles.

Opcionalmente, también puede especificar un subconjunto de los nodos del clúster de OpenShift para alojar los operadores, controladores y equipos virtuales de OpenShift mediante la configuración de reglas de colocación de nodos. Para configurar reglas de colocación de nodos para OpenShift Virtualization, siga la documentación https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html["aquí"].

En el caso del backup de almacenamiento que ofrece OpenShift Virtualization, NetApp recomienda tener un tipo de almacenamiento dedicado que solicite almacenamiento desde un back-end de Trident concreto, el cual, a su vez, se encuentra respaldado por una SVM dedicada. Esto mantiene un nivel de multi-tenancy con respecto a los datos que se sirven para cargas de trabajo basadas en equipos virtuales en el clúster OpenShift.
