---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_advanced_cluster_management_deployment_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Advanced Cluster Management para Kubernetes en Red Hat OpenShift con NetApp 
---
= Ponga en marcha la gestión avanzada de clústeres para Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se describe la gestión avanzada de clústeres para Kubernetes en Red Hat OpenShift con NetApp.



== Requisitos previos

. Un clúster de Red Hat OpenShift (superior a la versión 4.5) para el clúster de concentrador
. Clústeres de Red Hat OpenShift (superiores a la versión 4.4.3) para clústeres administrados
. Acceso de administrador de clúster al clúster de Red Hat OpenShift
. Una suscripción a Red Hat para Advanced Cluster Management para Kubernetes


Advanced Cluster Management es un complemento para el clúster OpenShift, por lo que existen ciertos requisitos y restricciones en los recursos de hardware basados en las funciones utilizadas en el concentrador y clústeres administrados. Debe tener en cuenta estos problemas al configurar los clústeres. Consulte la documentación https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration["aquí"] para obtener más detalles.

De manera opcional, si el clúster de concentrador tiene nodos dedicados para alojar componentes de infraestructura y desea instalar recursos de Advanced Cluster Management solo en esos nodos, deberá añadir toleraciones y selectores a esos nodos según corresponda. Para obtener más detalles, consulte la documentación de https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node["aquí"].
