---
sidebar: sidebar 
permalink: containers/rh-os-n_trident_ontap_nfs.html 
keywords: Trident, Astra Trident, ONTAP, AFF, FAS, NFS 
summary: Para habilitar la integración de Trident con el sistema de almacenamiento ONTAP de NetApp, debe crear un back-end que permita la comunicación con el sistema de almacenamiento. 
---
= Configuración NFS de ONTAP de NetApp
:allow-uri-read: 


Para habilitar la integración de Trident con el sistema de almacenamiento ONTAP de NetApp, debe crear un back-end que permita la comunicación con el sistema de almacenamiento.

. Hay archivos de fondo de ejemplo disponibles en el archivo de instalación descargado en `sample-input` jerarquía de carpetas. Para los sistemas ONTAP de NetApp que sirven NFS, copie el `backend-ontap-nas.json` archivar en el directorio de trabajo y editar el archivo.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[netapp-user@rhel7 trident-installer]$ vi backend-ontap-nas.json
----
. Editar la backendName, managementLIF, dataLIF, svm, nombre de usuario, y los valores de contraseña en este archivo.
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: Se recomienda definir el valor de backendName personalizado como una combinación de storageDriverName y DataLIF que sirve NFS para una identificación sencilla.

. Con este archivo back-end en su lugar, ejecute el siguiente comando para crear su primer back-end.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Con el back-end creado, debe crear después una clase de almacenamiento. Al igual que con el backend, existe un archivo de clase de almacenamiento de ejemplo que se puede editar para el entorno disponible en la carpeta de entradas de ejemplo. Cópielo en el directorio de trabajo y realice las modificaciones necesarias para reflejar el backend creado.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. La única edición que se debe realizar en este archivo es definir `backendType` valor asignado al nombre del controlador de almacenamiento desde el back-end recién creado. Observe también el valor del campo de nombre, al que se debe hacer referencia en un paso posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: Hay un campo opcional llamado `fsType` que se define en este archivo. Esta línea se puede eliminar en los back-ends de NFS.

. Ejecute el `oc` comando para crear la clase de almacenamiento.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Con la clase de almacenamiento creada, debe crear la primera reclamación de volumen persistente (RVP). Hay una muestra `pvc-basic.yaml` archivo que se puede utilizar para realizar esta acción ubicada también en entradas de ejemplo.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. La única edición que se debe realizar en este archivo es asegurarse de que `storageClassName` el campo coincide con el que se acaba de crear. La definición de PVC se puede personalizar aún más según sea necesario para el aprovisionamiento de la carga de trabajo.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Cree el PVC emitiendo el `oc` comando. La creación puede tardar un poco de tiempo, según el tamaño del volumen de backup que se esté creando, para que pueda ver el proceso a medida que finalice.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----


link:rh-os-n_use_cases.html["Siguiente: Casos prácticos y validación de la solución."]
