---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Vídeos y demostraciones: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Los siguientes vídeos muestran algunas de las funcionalidades documentadas en este documento:

[cols="5a, 5a, 5a"]
|===


 a| 
Acelere el desarrollo de software con Astra Control y la tecnología FlexClone de NetApp: Red Hat OpenShift con NetApp

 a| 
Aproveche Astra Control de NetApp para realizar un análisis post-mortem y restaurar su aplicación

 a| 
Protección de datos en canalización CI/CD con Astra Control Center




 a| 
Migración de cargas de trabajo mediante Astra Control Center: Red Hat OpenShift con NetApp

 a| 
Migración de cargas de trabajo: Red Hat OpenShift con NetApp

 a| 
Instalación de OpenShift Virtualization - Red Hat OpenShift con NetApp




 a| 
Implementación de una máquina virtual con virtualización de OpenShift: Red Hat OpenShift con NetApp

 a| 
NetApp HCI para Red Hat OpenShift en Red Hat Virtualization

 a| 

|===
link:rh-os-n_additional_information.html["Siguiente: Información adicional: Red Hat OpenShift con NetApp."]
