---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_rosa_solution_overview.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift Service on AWS, 
summary: Red Hat OpenShift Service en AWS con NetApp ONTAP 
---
= Red Hat OpenShift Service en AWS con NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este apartado, mostraremos cómo utilizar FSx para ONTAP como capa de almacenamiento persistente para aplicaciones que se ejecutan en ROSA. Mostrará la instalación del controlador CSI de NetApp Trident en un clúster ROSA, el aprovisionamiento de un sistema de archivos FSX para ONTAP y el despliegue de una aplicación con estado de ejemplo. También mostrará estrategias para realizar backups y restaurar los datos de sus aplicaciones. Con esta solución integrada, puede establecer un marco de almacenamiento compartido que se pueda escalar sin esfuerzo en las Azure, lo que simplifica los procesos de escalado, protección y restauración de sus datos con el controlador CSI de Trident.
