---
sidebar: sidebar 
permalink: containers/rh-os-n_load_balancers.html 
keywords: Advanced Configuration, Load Balancers, MetalLB 
summary: Esta sección se dedica a analizar las opciones de equilibrador de carga para los usuarios que desean personalizar su Red Hat OpenShift con la implementación de NetApp. 
---
= Análisis de las opciones de equilibrador de carga: Red Hat OpenShift con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En la mayoría de los casos, Red Hat OpenShift hace que las aplicaciones estén disponibles para el mundo exterior a través de rutas. Un servicio es expuesto dándole un nombre de host accesible desde el exterior. Un enrutador OpenShift puede consumir la ruta definida y los puntos finales identificados por su servicio para proporcionar esta conectividad con nombre a clientes externos.

Sin embargo, en algunos casos, las aplicaciones requieren la puesta en marcha y configuración de equilibradores de carga personalizados para exponer los servicios adecuados. Un ejemplo de esto es Astra Control Center de NetApp. Para satisfacer esta necesidad, hemos evaluado una serie de opciones de equilibrador de carga personalizadas. Su instalación y configuración se describen en esta sección.

En las siguientes páginas se ofrece información adicional sobre las opciones de equilibrador de carga validadas en la solución Red Hat OpenShift con NetApp:

* link:rh-os-n_LB_MetalLB.html["MetalLB"]
* link:rh-os-n_LB_F5BigIP.html["BIG-IP DE F5"]

