---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_management_portal.html 
keywords: VDS, Cloud Management, Portal 
summary: El portal VDS Cloud Workspace Management Suite de NetApp permite la gestión centralizada de diversas implementaciones de VDS, incluida una con sitios definidos para los usuarios locales, los administradores, el catálogo de aplicaciones y los eventos programados. El portal también lo utilizan los usuarios administrativos para el aprovisionamiento manual de aplicaciones si es necesario y para conectarse a cualquier equipo para la solución de problemas. 
---
= Portal de gestión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
El portal VDS Cloud Workspace Management Suite de NetApp está disponible https://["aquí"^] y la próxima versión está disponible https://["aquí"^].

El portal permite la administración centralizada de varias implementaciones de VDS, incluida una que tiene sitios definidos para los usuarios locales, administrativos, el catálogo de aplicaciones y eventos con secuencias de comandos. El portal también lo utilizan los usuarios administrativos para el aprovisionamiento manual de aplicaciones si es necesario y para conectarse a cualquier equipo para la solución de problemas.

Los proveedores de servicios pueden utilizar este portal para agregar sus propios socios de canal y permitirles gestionar sus propios clientes.

link:hcvdivds_user_management.html["Siguiente: Gestión de usuarios"]
