---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_application_management.html 
keywords: tech worker, application, Remote Desktop Services, VDS 
summary: Los trabajadores de tareas pueden iniciar rápidamente una aplicación desde la lista de aplicaciones que se les han puesto a su disposición. Los servicios de aplicaciones publican aplicaciones desde los hosts de sesión de Remote Desktop Services. Con WVD, los grupos de aplicaciones proporcionan una funcionalidad similar a la de los grupos de host de Windows 10 con varias sesiones. 
---
= Gestión de aplicaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Los trabajadores de tareas pueden iniciar rápidamente una aplicación desde la lista de aplicaciones que se les han puesto a su disposición. Los servicios de aplicaciones publican aplicaciones desde los hosts de sesión de Remote Desktop Services. Con WVD, los grupos de aplicaciones proporcionan una funcionalidad similar a la de los grupos de host de Windows 10 con varias sesiones.

Para que los trabajadores de la oficina puedan suministrar las aplicaciones que necesiten mediante una placa de servicio manualmente, o bien se pueden aprovisionar automáticamente con la función de eventos programados de VDS de NetApp.

Para obtener más información, consulte https://["Página de autorización de aplicaciones de NetApp"^].

link:hcvdivds_why_ontap.html["Siguiente: Funciones de ONTAP para el servicio de escritorios virtuales"]
