---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_why_ontap.html 
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup, File System analytics, cloud tiering, global namespace 
summary: Funciones de ONTAP para el servicio de escritorios virtuales. 
---
= Funciones de ONTAP para el servicio de escritorios virtuales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las siguientes funciones de ONTAP hacen que resulte atractiva la elección para su uso con un servicio de escritorios virtuales.

* *Sistema de archivos de escalado horizontal.* los volúmenes ONTAP FlexGroup pueden crecer hasta más de 20 PB de tamaño y pueden contener más de 400 mil millones de archivos dentro de un solo espacio de nombres. El clúster puede contener hasta 24 nodos de almacenamiento, cada uno con un número flexible de tarjetas de interfaz de red en función del modelo utilizado.
+
Los escritorios virtuales del usuario, las carpetas principales, los contenedores de perfiles de usuario, los datos compartidos, etc. pueden crecer en función de la demanda sin preocuparse por las limitaciones del sistema de archivos.

* *Análisis del sistema de archivos.* puede utilizar la herramienta XCP para obtener información detallada sobre los datos compartidos. Con ONTAP 9.8 o ActiveIQ Unified Manager, puede consultar y recuperar fácilmente la información de metadatos de archivos e identificar los datos inactivos.
* *Organización en niveles en el cloud.* puede realizar la migración de datos inactivos a un almacén de objetos en la nube o a cualquier almacenamiento compatible con S3 del centro de datos.
* *Versiones de archivo.* los usuarios pueden recuperar archivos protegidos por copias Snapshot de ONTAP de NetApp. Las copias Snapshot de ONTAP ocupan muy poco espacio, ya que solo registran los bloques cambiados.
* *Espacio de nombre global.* la tecnología ONTAP FlexCache permite almacenar en caché de forma remota el almacenamiento de archivos, lo que facilita la administración de datos compartidos entre ubicaciones que contienen sistemas de almacenamiento ONTAP.
* *Soporte multi-tenancy seguro.* Un único clúster de almacenamiento físico puede presentarse como múltiples matrices de almacenamiento virtual cada una con sus propios volúmenes, protocolos de almacenamiento, interfaces de red lógicas, dominio de identidad y autenticación, usuarios de administración, etc. Por lo tanto, es posible compartir la cabina de almacenamiento en varias unidades de negocio o entornos, como pruebas, desarrollo y producción.
+
Para garantizar el rendimiento, puede utilizar la calidad de servicio adaptativa para establecer niveles de rendimiento que se basan en el espacio utilizado o asignado y puede controlar la capacidad de almacenamiento mediante cuotas.

* *Integración de VMware.* Herramientas de ONTAP para VMware vSphere proporciona un complemento de vCenter para aprovisionar almacenes de datos, implementar prácticas recomendadas de host de vSphere y supervisar recursos de ONTAP.
+
ONTAP admite API de vStorage para la integración de cabinas (VAAI) para descargar las operaciones SCSI/archivo en la cabina de almacenamiento. ONTAP también admite API de vStorage para compatibilidad con Storage Awareness (VASA) y Virtual Volumes para protocolos de bloques y archivos.

+
El plugin de SnapCenter para VMware vSphere ofrece un método sencillo de realizar backups y restaurar máquinas virtuales con la función Snapshot en una cabina de almacenamiento.

+
ActiveIQ Unified Manager proporciona visibilidad completa de la red de almacenamiento en un entorno de vSphere. Los administradores pueden identificar fácilmente cualquier problema de latencia que pueda producirse en entornos de puestos de trabajo virtuales alojados en ONTAP.

* *Conformidad de seguridad.* con ActiveIQ Unified Manager, puede supervisar múltiples sistemas ONTAP con alertas por cualquier infracción de directivas.
* *Compatibilidad multiprotocolo.* ONTAP admite bloques (iSCSI, FC, FCoE y NVMe/FC), archivos (NFSv3, NFSv4.1, SMB2.x y SMB3.x) y protocolos de almacenamiento de objetos (S3).
* *Compatibilidad con automatización.* ONTAP proporciona módulos API REST, Ansible y PowerShell para automatizar tareas con el portal de administración VDS.

