---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_conclusion.html 
keywords: VDS, Virtual Desktop Service, HCI, conclusion 
summary: El servicio de escritorios virtuales de NetApp ofrece un entorno de aplicaciones y puestos de trabajo virtuales fácil de usar, prestando especial atención a los desafíos empresariales. Al ampliar VDS con NetApp HCI, es posible utilizar potentes funciones de NetApp en un entorno de VDS, incluidos la deduplicación en línea, la compactación, el thin provisioning y la compresión. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
El servicio de escritorios virtuales de NetApp ofrece un entorno de aplicaciones y puestos de trabajo virtuales fácil de usar, prestando especial atención a los desafíos empresariales. Al ampliar VDS con el entorno ONTAP en las instalaciones, es posible utilizar potentes funciones de NetApp en un entorno VDS, que incluyen un clonado rápido, deduplicación en línea, compactación, thin provisioning, y compresión. Estas funciones ahorran en costes de almacenamiento y mejoran el rendimiento con el almacenamiento all-flash. Con el hipervisor VMware vSphere, que minimiza el tiempo de aprovisionamiento del servidor mediante Virtual Volumes y la API de vSphere para la integración de cabina. Con el cloud híbrido, los clientes pueden elegir el entorno adecuado para sus cargas de trabajo exigentes y ahorrar dinero. La sesión de escritorio que se ejecuta en las instalaciones puede acceder a los recursos cloud en función de políticas.
