---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html 
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services, 
summary: 'El servicio de escritorios virtuales (VDS) de NetApp organiza los servicios de escritorios remotos (RDS) en los principales clouds públicos y en clouds privados. VDS es compatible con Windows Virtual Desktop (WVD) en Microsoft Azure. VDS automatiza muchas tareas que se deben realizar después de la implementación de WVD o RDS, incluida la configuración de recursos compartidos de archivos SMB (para perfiles de usuario, datos compartidos y la unidad de inicio del usuario), habilitar funciones de Windows, instalación de aplicaciones y agentes, firewall y políticas, etc.' 
---
= TR-4861: VDI de cloud híbrido con servicio de puestos de trabajo virtuales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Suresh Thoppay, NetApp

[role="lead"]
El servicio de escritorios virtuales (VDS) de NetApp organiza los servicios de escritorios remotos (RDS) en los principales clouds públicos y en clouds privados. VDS es compatible con Windows Virtual Desktop (WVD) en Microsoft Azure. VDS automatiza muchas tareas que se deben realizar después de la implementación de WVD o RDS, incluida la configuración de recursos compartidos de archivos SMB (para perfiles de usuario, datos compartidos y la unidad de inicio del usuario), habilitar funciones de Windows, instalación de aplicaciones y agentes, firewall y políticas, etc.

Los usuarios consumen VDS para escritorios dedicados, escritorios compartidos y aplicaciones remotas. VDS proporciona eventos con secuencias de comandos para automatizar la administración de aplicaciones en los escritorios y reduce el número de imágenes que se van a gestionar.

VDS proporciona un único portal de gestión para gestionar las puestas en marcha de entornos de cloud público y privado.



== Valor para el cliente

La explosión de personal remoto en 2020 ha cambiado los requisitos de continuidad del negocio. Los departamentos DE TECNOLOGÍA deben hacer frente a nuevos retos para aprovisionar con rapidez puestos de trabajo virtuales y, por tanto, requerir agilidad de aprovisionamiento, gestión remota y las ventajas del TCO de un cloud híbrido que facilita el aprovisionamiento de recursos en las instalaciones y en el cloud. Necesitan una solución de cloud híbrido que:

* Aborda la realidad del espacio de trabajo post-COVID para hacer posibles modelos de trabajo flexibles con dinámica global
* Permite el trabajo en turnos simplificando y acelerando la implementación de entornos de trabajo para todos los empleados, desde trabajadores de tareas hasta usuarios avanzados
* Moviliza a su personal proporcionando recursos de infraestructura de puestos de trabajo virtuales seguros y enriquecidos independientemente de la ubicación física
* Simplifica la puesta en marcha del cloud híbrido
* Automatiza y simplifica la gestión de la reducción de riesgos

