---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: La infraestructura de puestos de trabajo virtuales híbrida con VDS de NetApp permite a los proveedores de servicios y a los administradores de puestos de trabajo virtuales empresariales ampliar fácilmente los recursos a otro entorno de cloud sin que ello afecte a los usuarios. Al disponer de recursos en las instalaciones en NetApp HCI, se obtiene un mejor control de los recursos de GPU y se pueden ampliar los nodos de computación o de almacenamiento según se requiera. 
---
= Casos de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La infraestructura de puestos de trabajo virtuales híbrida con VDS de NetApp permite a los proveedores de servicios y a los administradores de puestos de trabajo virtuales empresariales ampliar fácilmente los recursos a otro entorno de cloud sin que ello afecte a los usuarios. Contar con recursos en las instalaciones proporciona un mejor control de los recursos y ofrece una amplia selección de opciones (computación, GPU, almacenamiento y red) para satisfacer la demanda.

Esta solución se aplica a los siguientes casos de uso:

* Desbordamiento del cloud por el aumento en la demanda de aplicaciones y puestos de trabajo remotos
* Reducir el TCO en aplicaciones y puestos de trabajo remotos de larga duración alojándolos en las instalaciones con almacenamiento flash y recursos GPU
* Facilidad de gestión de puestos de trabajo y aplicaciones remotos en todos los entornos cloud
* Disfrute de aplicaciones y puestos de trabajo remotos usando un modelo de software como servicio con recursos en las instalaciones




== Público objetivo

El público objetivo de la solución incluye los siguientes grupos:

* Arquitectos de EUC/VDI que quieren comprender los requisitos de una instancia de VDS híbrida
* Los partners de NetApp que desean ayudar a sus clientes con sus necesidades de aplicaciones y puesto de trabajo remoto
* Clientes de NetApp HCI existentes que desean atender las demandas de las aplicaciones y los puestos de trabajo remotos

