---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: Cuando se utiliza H610C o H615C, la licencia de la GPU debe obtenerse de los partners de NVIDIA autorizados a revender las licencias. 
---
= Gestión de licencias de NVIDIA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cuando se utiliza H610C o H615C, la licencia de la GPU debe obtenerse de los partners de NVIDIA autorizados a revender las licencias. Puede encontrar partners de NVIDIA con el https://www.nvidia.com/object/partner-locator.html["localizador de partners"^]. Busque competencias como GPU virtual (vGPU) o Tesla.

El software NVIDIA vGPU está disponible en cuatro ediciones:

* PC virtual DE GRID de NVIDIA (GRID VPC)
* Aplicaciones virtuales DE GRID de NVIDIA (VAPPS DE GRID)
* Estación de trabajo de centro de datos virtual Quadro (Quadro VDWS) NVIDIA
* Virtual ComputeServer de NVIDIA (vComputeServer)




== PC virtual DE GRID

Este producto es ideal para usuarios que desean un escritorio virtual que proporcione una gran experiencia de usuario para aplicaciones de Microsoft Windows, exploradores, vídeo de alta definición y soporte para varios monitores. El PC virtual GRID de NVIDIA ofrece una experiencia nativa en un entorno virtual, lo que le permite ejecutar todas las aplicaciones de su PC a pleno rendimiento.



== Aplicaciones virtuales GRID

LAS vApps DE GRID se utilizan para organizaciones que implementan un host de sesión de Escritorio remoto (RDSH) u otras soluciones basadas en sesiones o en streaming de aplicaciones. Diseñado para ofrecer aplicaciones de Microsoft Windows a todo rendimiento, los escritorios RDSH alojados en Windows Server también son compatibles con GRID vApps.



== Estación de trabajo Quadro Virtual Data Center

Esta edición es ideal para diseñadores generales y de gama alta que utilizan potentes herramientas de creación de contenido en 3D como Dassault CATIA, SOLIDWORKS, 3Dexsite, Siemens NX, PTC Creo, Schlumberger Petrel o Autodesk Maya. NVIDIA Quadro VDWS permite a los usuarios acceder a sus aplicaciones gráficas profesionales con todas las características y el rendimiento en cualquier lugar de cualquier dispositivo.



== Virtual ComputeServer de NVIDIA

Muchas organizaciones ejecutan cargas de trabajo de servidores con un uso intensivo de la computación, como la inteligencia artificial (IA), el aprendizaje profundo (DL) y la ciencia de los datos. Para estos casos de uso, el software NVIDIA vComputeServer virtualiza la GPU NVIDIA, lo que acelera las cargas de trabajo de servidores con un uso intensivo de recursos informáticos con características como el código de corrección de errores, la retirada de páginas, la paridad a punto en NVLink y multi-vGPU.


NOTE: Una licencia Quadro VDWS permite utilizar GRID VPC y NVIDIA vComputeServer.

link:hcvdivds_deployment.html["Siguiente: Implementación"]
