---
sidebar: sidebar 
permalink: vdi-vds/vdi-index.html 
keywords: vdi, vds, virtual desktop, end use computing, 
summary: Los trabajadores de tareas pueden iniciar rápidamente una aplicación desde la lista de aplicaciones que se les han puesto a su disposición. Los servicios de aplicaciones publican aplicaciones desde los hosts de sesión de Remote Desktop Services. Con WVD, los grupos de aplicaciones proporcionan una funcionalidad similar a la de los grupos de host de Windows 10 con varias sesiones. 
---
= Soluciones tecnológicas para el usuario final (EUC)/Infraestructura de puestos de trabajo virtuales (VDI)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Tanto si pone en marcha puestos de trabajo virtuales en las instalaciones como en el cloud, NetApp cuenta con una gran variedad de soluciones de EUC/VDI para responder a sus necesidades.



== Servicios de puestos de trabajo virtuales (VDS) de NetApp

El servicio de escritorios virtuales (VDS) de NetApp organiza los servicios de escritorios remotos (RDS) en los principales clouds públicos y en clouds privados.

Soluciones disponibles para VDS:

* link:hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html["Infraestructura de puestos de trabajo virtuales de cloud híbrido con Virtual Desktop Service de NetApp"]




== Computación de usuario final con VMware Horizon

NetApp ha verificado las arquitecturas para VMware Horizon que abarcan varias configuraciones de computación. Entre las soluciones disponibles se incluyen:

* link:https://www.netapp.com/pdf.html?item=/media/7123-nva1129designpdf.pdf["Computación de usuario final con VMware (guía de diseño)"]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf["Computación de usuario final con VMware y GPU NVIDIA (guía de diseño)"]
* link:https://www.netapp.com/pdf.html?item=/media/7124-nva-1129-deploy.pdf["Computación de usuario final con VMware y GPU NVIDIA (guía de puesta en marcha)"]
* link:https://www.netapp.com/pdf.html?item=/media/7125-tr4792pdf.pdf["Computación de usuario final con VMware para gráficos 3D"]

