---
sidebar: sidebar 
permalink: virtualization/vmware-vcf-overview.html 
keywords: netapp, vmware, cloud, foundation, vcf, flexpod 
summary:  
---
= Base de cloud de VMware
:allow-uri-read: 




== Base de cloud de VMware

[role="lead"]
VMware Cloud Foundation (VCF) es un conjunto de tecnologías que ofrece una ruta directa para acceder a una experiencia de nube híbrida. La solución VCF ofrece soporte para cargas de trabajo nativas de Kubernetes y basadas en máquinas virtuales. Los servicios esenciales como VMware vSphere, VMware vSAN, VMware NSX-T Data Center y VMware vRealize Cloud Management son componentes integrales del paquete VCF. Al combinarse, estos servicios establecen una infraestructura definida por software capaz de gestionar la informática, el almacenamiento, las redes, la seguridad y la gestión del cloud. Esta infraestructura colectiva proporciona una experiencia híbrida, en la que el marco VCF amplía el entorno desde el centro de datos in situ a Amazon Web Services (AWS), Azure y Google Cloud.



=== Recursos de documentación

Para obtener información detallada sobre las ofertas de NetApp para VMware Cloud Foundation, consulte la serie de blogs de cuatro (4) partes:

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-getting-started/["NetApp y VMware Cloud Foundation se simplificaron. Parte 1: Introducción"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-ontap-principal-storage/["NetApp y VMware Cloud Foundation simplificaron la parte 2: VCF y almacenamiento principal de ONTAP"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-element-principal-storage/["NetApp y VMware Cloud Foundation simplificaron la parte 3: VCF y almacenamiento principal de Element"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-supplemental-storage/["NetApp y VMware Cloud Foundation simplificados: Parte 4: Herramientas de ONTAP para VMware y almacenamiento complementario"]


*Soluciones NetApp FlexPod para VMware Cloud Foundation*

* link:https://www.netapp.com/blog/expanding-flexpod-hybrid-cloud-with-vmware-cloud-foundation/["Expande el cloud híbrido de FlexPod con VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf.html["FlexPod como dominio de carga de trabajo para VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf_design.html["Guía de diseño de FlexPod como dominio de carga de trabajo para VMware Cloud Foundation"]

