---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Esta página ofrece una introducción a los vídeos y tutoriales. 
---
= Vídeos y demostraciones sobre virtualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Vea los siguientes vídeos y demostraciones en los que se destacan características específicas de las soluciones de cloud híbrido, virtualización y contenedores.

.Herramientas de ONTAP de NetApp para VMware vSphere
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Herramientas de ONTAP para VMware: Información general

 a| 
Aprovisionamiento de almacén de datos iSCSI de VMware con ONTAP

 a| 
Aprovisionamiento del almacén de datos NFS de VMware con ONTAP


|===
====
.VMware Cloud en AWS con AWS FSX para ONTAP de NetApp
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Almacenamiento conectado como invitado de Windows con FSX ONTAP mediante iSCSI

 a| 
Almacenamiento conectado invitado de Linux con FSX ONTAP mediante NFS

 a| 
Ahorro de VMware Cloud en AWS TCO con Amazon FSX para ONTAP de NetApp




 a| 
VMware Cloud en un almacén de datos complementario con Amazon FSX para ONTAP de NetApp

 a| 
Instalación y configuración de VMware HCX para VMC

 a| 
Demostración de migración de VMotion con VMware HCX para VMC y FSxN




 a| 
Demostración de migración en frío con VMware HCX para VMC y FSxN

 a| 
 a| 

|===
====
.Azure VMware Services en Azure con Azure NetApp Files (ANF)
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Descripción general adicional del almacén de datos de la solución para VMware Azure con Azure NetApp Files

 a| 
Recuperación ante desastres de la solución VMware para Azure con Cloud Volumes ONTAP, SnapCenter y JetStream

 a| 
Demostración de migración en frío con VMware HCX para AVS y ANF




 a| 
Demostración de VMotion con VMware HCX para AVS y ANF

 a| 
Demostración de migración masiva con VMware HCX para AVS y ANF

 a| 

|===
====
.Plugin de SnapCenter para VMware vSphere
[%collapsible]
====
El software SnapCenter de NetApp es una plataforma empresarial fácil de usar para coordinar y administrar de un modo seguro la protección de datos en todas las aplicaciones, bases de datos y sistemas de archivos.

El plugin de SnapCenter para VMware vSphere permite ejecutar operaciones de backup, restauración y conexión para máquinas virtuales, así como operaciones de backup y montaje para almacenes de datos que se registran en SnapCenter directamente en VMware vCenter.

Para obtener más información sobre el plugin de SnapCenter para VMware vSphere, consulte link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Información general sobre el plugin de SnapCenter de NetApp para VMware vSphere"].

[cols="5a, 5a, 5a"]
|===


 a| 
Plugin de SnapCenter para VMware vSphere: Requisitos previos de la solución

 a| 
Plugin de SnapCenter para VMware vSphere: Implementación

 a| 
Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de backup




 a| 
Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de restauración

 a| 
SnapCenter - flujo de trabajo de restauración SQL

 a| 

|===
====
.NetApp con VMware Tanzania
[%collapsible]
====
VMware Tanzania permite a los clientes poner en marcha, administrar y gestionar su entorno de Kubernetes a través de vSphere o de VMware Cloud Foundation. Esta cartera de productos de VMware permite a los clientes gestionar todos sus clústeres de Kubernetes relevantes desde un único plano de control al elegir la edición de VMware Tanzu que mejor se adapte a sus necesidades.

Si quiere más información sobre VMware Tanzania, consulte https://tanzu.vmware.com/tanzu["Descripción general de VMware Tanzania"^]. Esta revisión incluye casos de uso, adiciones disponibles y mucho más sobre VMware Tanzu.

[cols="5a, 5a, 5a"]
|===


 a| 
Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 1

video::ZtbXeOJKhrc[youtube,width=360] a| 
Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 2

video::FVRKjWH7AoE[youtube,width=360] a| 
Cómo utilizar vVols con NetApp y VMware Tanzu Basic, parte 3

video::Y-34SUtTTtU[youtube,width=360]
|===
====