---
sidebar: sidebar 
permalink: virtualization/vsphere_auto_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Esta página describe las ventajas de automatizar la funcionalidad básica de ONTAP en un entorno VMware vSphere. 
---
= Introducción a la automatización para ONTAP y vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Automatización de VMware

La automatización ha sido un aspecto integral de la gestión de entornos VMware desde los primeros días de VMware ESX. La capacidad de poner en marcha infraestructura como código y ampliar las prácticas en operaciones de cloud privado ayuda a paliar las cuestiones relacionadas con el escalado, la flexibilidad, el aprovisionamiento automático y la eficiencia.

La automatización se puede organizar en las siguientes categorías:

* *Implementación de infraestructura virtual*
* *Operaciones de máquina invitada*
* *Operaciones en la nube*


Los administradores tienen a su disposición muchas opciones en lo que respecta a la automatización de su infraestructura. Ya sea mediante el uso de funciones nativas de vSphere como Perfiles de host o especificaciones de personalización para máquinas virtuales hasta las API disponibles en los componentes de software, los sistemas operativos y los sistemas de almacenamiento de NetApp, existe una documentación y guía significativas disponibles.

Data ONTAP 8.0.1 y versiones posteriores admiten ciertas funciones de API de VMware vSphere para la integración de cabinas (VAAI) cuando el host ESX ejecuta ESX 4.1 o versiones posteriores. VAAI es un conjunto de API que permiten la comunicación entre hosts ESXi de VMware vSphere y dispositivos de almacenamiento. Estas funciones ayudan a descargar las operaciones del host ESX al sistema de almacenamiento y aumentan el rendimiento de la red. El host ESX habilita las funciones automáticamente en el entorno correcto. Puede determinar la extensión hasta la cual el sistema utiliza las funciones de VAAI si se comprueban las estadísticas contenidas en los contadores VAAI.

El punto de partida más común para automatizar la puesta en marcha de un entorno VMware es el aprovisionamiento de almacenes de datos basados en bloques o archivos. Es importante trazar el mapa de los requisitos de las tareas reales antes de desarrollar la automatización correspondiente.

Si quiere más información sobre la automatización de los entornos VMware, consulte los siguientes recursos:

* https://netapp.io/configuration-management-and-automation/["ThePub de NetApp"^]. Gestión y automatización de la configuración de NetApp.
* https://galaxy.ansible.com/community/vmware["La comunidad de Ansible Galaxy para VMware"^]. Una colección de recursos de Ansible para VMware.
* https://code.vmware.com/resources["Recursos de VMware {code}"^]. Los recursos necesarios para diseñar soluciones para el centro de datos definido mediante software, incluidos foros, estándares de diseño, código de muestra y herramientas de desarrollo.

