---
sidebar: sidebar 
permalink: virtualization/vsphere_ontap_auto_block.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, iSER, iSCSI, FCoE,SAN, ONTAP tools 
summary: Esta página proporciona los pasos para implementar un almacén de datos VMFS iSCSI en un entorno de VMware vSphere en un almacenamiento ONTAP de NetApp. 
---
= Aprovisionamiento de almacenamiento en bloques vSphere tradicional con ONTAP
:allow-uri-read: 


[role="lead"]
VMware vSphere admite las siguientes opciones de almacenes de datos VMFS con la compatibilidad con el protocolo SAN de ONTAP indicada.

[cols="50,50"]
|===
| Opciones de almacén de datos VMFS | Compatibilidad con el protocolo SAN de ONTAP 


| link:vsphere_ontap_auto_block_fc.html["Fibre Channel (FC)"] | sí 


| link:vsphere_ontap_auto_block_fcoe.html["Fibre Channel sobre Ethernet (FCoE)"] | sí 


| link:vsphere_ontap_auto_block_iscsi.html["ISCSI"] | sí 


| Extensiones iSCSI para RDMA (Iser) | no 


| link:vsphere_ontap_auto_block_nvmeof.html["NVMe sobre estructura con FC (NVMe/FC)"] | sí 


| NVMe over Fabric con RDMA sobre Ethernet convergente (NVMe/roce) | no 
|===

NOTE: Si se requiere Iser o VMFS NVMe/roce, compruebe los sistemas de almacenamiento basados en SANtricity.
