---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Esta página describe las prácticas recomendadas para implementar una solución de almacenamiento ONTAP de NetApp en un entorno de VMware vSphere. 
---
= Introducción a ONTAP para administradores de vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== ¿Por qué elegir ONTAP para vSphere?

ONTAP de NetApp simplifica las operaciones de almacenamiento y gestión de datos y complementa claramente los entornos VMware, ya sea con la implementación en las instalaciones o en el cloud. La mejor protección de datos de NetApp, innovaciones en eficiencia del almacenamiento y un excelente rendimiento en arquitecturas de VMware basadas tanto en SAN COMO en NAS son algunos de los motivos por los que decenas de miles de clientes han seleccionado ONTAP como solución de almacenamiento para puestas en marcha de vSphere.

NetApp proporciona numerosos complementos, validaciones y calificaciones de VMware de varios productos VMware para responder a los clientes que se enfrentan a los retos únicos de administrar un entorno de virtualización. NetApp logra el almacenamiento y la gestión de datos lo que VMware hace para la virtualización, lo que permite a los clientes centrarse en sus competencias principales en lugar de gestionar el almacenamiento físico. Esta 20 alianza entre VMware y NetApp continúa evolucionando y añadiendo valor al cliente a medida que surgen nuevas tecnologías, como VMware Cloud Foundation y Tanzu, al tiempo que continúa dando soporte a las bases de vSphere.

Algunos de los factores clave que valoran los clientes son:

* *Almacenamiento unificado*
* *Eficiencia del almacenamiento*
* *Gestión basada en normativas de almacenamiento y volúmenes virtuales*
* *Cloud híbrido*


Si desea obtener más información sobre las soluciones de NetApp y VMware admitidas, consulte los siguientes recursos:

* https://mysupport.netapp.com/matrix/#welcome["La herramienta de matriz de interoperabilidad de NetApp"^] (IMT). La IMT define los componentes y versiones cualificadas que puede utilizar para crear configuraciones FC/FCoE, iSCSI, NFS y CIFS.
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guía de compatibilidad de VMware"^]. En la guía de compatibilidad de VMware se muestra la compatibilidad del sistema, la E/S, el almacenamiento/SAN y el backup con VMware Infrastructure y los productos de software
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["Herramientas de ONTAP de NetApp para VMware"^]. Las herramientas de ONTAP para VMware vSphere son un único complemento de vCenter Server que incluye las extensiones VSC, VASA Provider y el adaptador de replicación de almacenamiento (SRA).

