---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Esta página ofrece una introducción a los vídeos y tutoriales. 
---
= Vídeos y demostraciones sobre cloud híbrido, virtualización y contenedores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Vea los siguientes vídeos y demostraciones en los que se destacan características específicas de las soluciones de cloud híbrido, virtualización y contenedores.

.Herramientas de ONTAP de NetApp para VMware vSphere
[%collapsible]
====
.Herramientas de ONTAP para VMware: Información general
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.Aprovisionamiento de almacén de datos iSCSI de VMware con ONTAP
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.Aprovisionamiento del almacén de datos NFS de VMware con ONTAP
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.VMware Cloud en AWS con AWS FSX para ONTAP de NetApp
[%collapsible]
====
.Almacenamiento conectado como invitado de Windows con FSX ONTAP mediante iSCSI
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.Almacenamiento conectado invitado de Linux con FSX ONTAP mediante NFS
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.Ahorro de VMware Cloud en AWS TCO con Amazon FSX para ONTAP de NetApp
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.VMware Cloud en un almacén de datos complementario con Amazon FSX para ONTAP de NetApp
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.Migración de VMware Cloud en AWS con FSxN o VMware HCX
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure VMware Services en Azure con Azure NetApp Files (ANF)
[%collapsible]
====
.Descripción general adicional del almacén de datos de la solución para VMware Azure con Azure NetApp Files
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Recuperación ante desastres de la solución VMware para Azure con Cloud Volumes ONTAP, SnapCenter y JetStream
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Migración de la solución VMware para Azure con ANF, VMware HCX
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.Plugin de SnapCenter para VMware vSphere
[%collapsible]
====
El software SnapCenter de NetApp es una plataforma empresarial fácil de usar para coordinar y administrar de un modo seguro la protección de datos en todas las aplicaciones, bases de datos y sistemas de archivos.

El plugin de SnapCenter para VMware vSphere permite ejecutar operaciones de backup, restauración y conexión para máquinas virtuales, así como operaciones de backup y montaje para almacenes de datos que se registran en SnapCenter directamente en VMware vCenter.

Para obtener más información sobre el plugin de SnapCenter para VMware vSphere, consulte link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Información general sobre el plugin de SnapCenter de NetApp para VMware vSphere"].

.Plugin de SnapCenter para VMware vSphere: Requisitos previos de la solución
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.Plugin de SnapCenter para VMware vSphere: Implementación
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de backup
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de restauración
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter - flujo de trabajo de restauración SQL
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp con VMware Tanzania
[%collapsible]
====
VMware Tanzania permite a los clientes poner en marcha, administrar y gestionar su entorno de Kubernetes a través de vSphere o de VMware Cloud Foundation. Esta cartera de productos de VMware permite a los clientes gestionar todos sus clústeres de Kubernetes relevantes desde un único plano de control al elegir la edición de VMware Tanzu que mejor se adapte a sus necesidades.

Si quiere más información sobre VMware Tanzania, consulte https://tanzu.vmware.com/tanzu["Descripción general de VMware Tanzania"^]. Esta revisión incluye casos de uso, adiciones disponibles y mucho más sobre VMware Tanzu.

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 1"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 2"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["Cómo utilizar vVols con NetApp y VMware Tanzu Basic, parte 3"^]


====
.NetApp con Red Hat OpenShift
[%collapsible]
====
Red Hat OpenShift, una plataforma de Kubernetes para empresas, le permite ejecutar aplicaciones basadas en contenedores con una estrategia de cloud híbrido abierta. Red Hat OpenShift, disponible como servicio de nube en clouds públicos líderes o como software autogestionado, ofrece a los clientes la flexibilidad que necesitan al diseñar su solución basada en contenedores.

Para obtener más información sobre Red Hat OpenShift, consulte este tema https://www.redhat.com/en/technologies/cloud-computing/openshift["Visión general de Red Hat OpenShift"^]. También puede consultar la documentación del producto y las opciones de implementación para obtener más información sobre Red Hat OpenShift.

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["Migración de cargas de trabajo: Red Hat OpenShift con NetApp"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Implementación de Red Hat OpenShift en RHV: Red Hat OpenShift con NetApp"^]


====