---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_conclusion.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, vcenter, disaster 
summary: VMware vCenter Site Recovery Manager es una oferta de recuperación ante desastres que proporciona orquestación automatizada y pruebas no disruptivas de planes de recuperación centralizados para simplificar la gestión de recuperación ante desastres de todas las aplicaciones virtualizadas. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
VMware vCenter Site Recovery Manager es una oferta de recuperación ante desastres que proporciona orquestación automatizada y pruebas no disruptivas de planes de recuperación centralizados para simplificar la gestión de recuperación ante desastres de todas las aplicaciones virtualizadas.

Al poner en marcha Site Recovery Manager en sistemas ONTAP de NetApp, puede reducir de forma drástica el coste y la complejidad de la recuperación ante desastres. Con dispositivos de almacenamiento de alto rendimiento, fáciles de gestionar y escalables, y sólidas ofertas de software, NetApp ofrece soluciones flexibles de gestión de datos y almacenamiento para dar soporte a entornos vSphere.

Las mejores prácticas y recomendaciones que se ofrecen en esta guía no son una solución única para todos. Este documento contiene una colección de prácticas recomendadas y recomendaciones que proporcionan directrices para planificar, implementar y gestionar planes de recuperación ante desastres de SRM. Póngase en contacto con un experto local de VMware de NetApp cuando planifique e implemente entornos de recuperación de sitio de VMware vCenter en el almacenamiento de NetApp. Los expertos de VMware de NetApp pueden identificar rápidamente las necesidades y exigencias de cualquier entorno vSphere y pueden ajustar la solución de almacenamiento según corresponda.
