---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_additional_information.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, additional, information 
summary: Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos o sitios web. 
---
= Información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* TR-4597: VMware vSphere para ONTAPhttps://["https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html"^]
* TR-4400: VMware vSphere Virtual Volumes con ONTAPhttps://["https://www.netapp.com/pdf.html?item=/media/13555-tr4400.pdf"^]
* TR-4015 Guía de mejores prácticas para la configuración de SnapMirror para ONTAP 9https://[]
* RBAC User Creator para ONTAPhttps://["https://mysupport.netapp.com/site/tools/tool-eula/rbac"^]
* Herramientas de ONTAP para recursos de VMware vSpherehttps://["https://mysupport.netapp.com/site/products/all/details/otv/docsandkb-tab"^]
* Documentación de VMware Site Recovery Managerhttps://["https://docs.vmware.com/en/Site-Recovery-Manager/index.html"^]


Consulte la http://["Herramienta de matriz de interoperabilidad (IMT)"^] En el sitio de soporte de NetApp, con el fin de validar que las versiones exactas del producto y las funciones descritas en este documento son compatibles con su entorno concreto. La cabina IMT de NetApp define los componentes y las versiones del producto que pueden utilizarse para crear configuraciones que sean compatibles con NetApp. Los resultados específicos dependen de la instalación que realice cada cliente de acuerdo con las especificaciones publicadas.
