---
sidebar: sidebar 
permalink: virtualization/vvols-overview.html 
keywords: tr-4400, vvols, ontap, virtual volumes 
summary:  
---
= TR-4400: VMware vSphere Virtual Volumes (vVols) con ONTAP de NetApp
:allow-uri-read: 


[role="lead"]
Autor(es): Chance Bingen, NetApp



== ¿Por qué elegir vVols para vSphere?

El software ONTAP^®^ de NetApp lleva más de dos décadas siendo una solución de almacenamiento líder para entornos VMware vSphere y continúa añadiendo funcionalidades innovadoras para simplificar la gestión y reducir los costes. Este documento trata las funcionalidades de ONTAP para VMware vSphere Virtual Volumes (vVols), incluida la información más reciente sobre el producto y los casos de uso, junto con las prácticas recomendadas y otra información para optimizar la puesta en marcha y reducir los errores.

Las prácticas recomendadas complementan otros documentos, como guías y listas de compatibilidad. Se desarrollan según pruebas de laboratorio y una amplia experiencia de campo por parte de ingenieros y clientes de NetApp. Puede que no sean las únicas prácticas que funcionan o son compatibles, pero generalmente son las soluciones más simples que satisfacen las necesidades de la mayoría de los clientes.


TIP: Este documento se ha actualizado para incluir las nuevas funciones de vVols que se encuentran en vSphere 8,0 update 1 que son compatibles con la versión ONTAP tools 9,12.
