---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_conclusion.html 
keywords: bare metal, infrastructure, stateful, Trident 
summary: Anthos con configuraciones básicas de NetApp proporciona una plataforma robusta para ejecutar cargas de trabajo basadas en contenedores de manera eficiente al permitir la personalización de la infraestructura puesta en marcha. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Anthos con configuraciones básicas de NetApp proporciona una plataforma robusta para ejecutar cargas de trabajo basadas en contenedores de manera eficiente al permitir la personalización de la infraestructura puesta en marcha. Los clientes pueden utilizar la infraestructura de servidor y el sistema operativo compatible de su elección o incluso poner en marcha la solución dentro de su infraestructura existente. La potencia y la flexibilidad de estos entornos aumentan enormemente gracias a la integración de ONTAP de NetApp y Astra Trident de NetApp, que admiten cargas de trabajo de aplicaciones con estado mediante el aprovisionamiento y la gestión eficientes del almacenamiento persistente para contenedores. Al ampliar el potencial de Google Cloud a su centro de datos con tecnología de NetApp, un cliente puede conocer las ventajas de una solución de Kubernetes totalmente compatible, de alta disponibilidad, fácilmente escalable y totalmente gestionada para el desarrollo y la producción de las cargas de trabajo de sus aplicaciones.

link:bmanthos_where_to_find_additional_information.html["Siguiente: Dónde encontrar información adicional."]
