---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: NetApp y Google Cloud han mantenido una sólida relación desde hace varios años, con la primera introducción de servicios de datos en el cloud en Google Cloud con Cloud Volumes ONTAP y Cloud Volumes Service. Esta relación se amplió después mediante la validación de la plataforma NetApp HCI para su uso con Google Cloud Anthos en las instalaciones, una solución Kubernetes híbrida basada en hipervisores y basada en hipervisores puesta en marcha en VMware vSphere. A continuación, NetApp superó la cualificación Anthos preparada para NetApp Astra Trident, ONTAP y el protocolo NFS para proporcionar almacenamiento persistente dinámico para contenedores. 
---
= WP-7337: Anthos en Bare Metal
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Alan Cowles y Nikhil M Kulkarni, NetApp

NetApp y Google Cloud han mantenido una sólida relación desde hace varios años, con la primera introducción de servicios de datos en el cloud para Google Cloud con Cloud Volumes ONTAP y Cloud Volumes Service. Esta relación se amplió después mediante la validación de la plataforma NetApp HCI para su uso con Google Cloud Anthos en las instalaciones, una solución Kubernetes híbrida basada en hipervisores y basada en hipervisores puesta en marcha en VMware vSphere. A continuación, NetApp superó la cualificación Anthos preparada para NetApp Astra Trident, ONTAP y el protocolo NFS para proporcionar almacenamiento persistente dinámico para contenedores.

Anthos puede instalarse ahora directamente en servidores con configuración básica en el entorno de un cliente, lo que agrega una opción adicional para que los clientes puedan ampliar Google Cloud a sus centros de datos locales sin un hipervisor. Además, al aprovechar las funcionalidades del sistema operativo de almacenamiento ONTAP de NetApp y Astra Trident de NetApp, puede ampliar sus funciones mediante la integración del almacenamiento persistente para contenedores.

Esta combinación le permite aprovechar todo el potencial de sus servidores, almacenamiento y red, en combinación con el soporte, los niveles de servicio, la facturación mensual y la flexibilidad bajo demanda que proporciona Google Cloud. Dado que utiliza su propio hardware, red y almacenamiento, dispone de control directo sobre la escala de las aplicaciones, la seguridad y la latencia de la red, así como de la ventaja de las aplicaciones gestionadas y en contenedores con Anthos en entornos bare metal.

link:bmanthos_solution_overview.html["Siguiente: Descripción general de la solución."]
