= 
:allow-uri-read: 


. Para utilizar los libros de estrategia de Ansible que ponen en marcha Astra Control Center, debe tener una máquina Ubuntu/RHEL con Ansible instalada. Siga este https://docs.netapp.com/us-en/netapp-solutions/automation/automation_ubuntu_debian_setup.html["procedimiento"^] Para Ubuntu y esto https://docs.netapp.com/us-en/netapp-solutions/automation/automation_rhel_centos_setup.html["procedimiento"^] Para RHEL.
. Clone el repositorio de GitHub que aloja el contenido de Ansible.
+
[source, cli]
----
git clone https://github.com/NetApp-Automation/na_astra_control_suite.git
----
. Inicie sesión en el sitio de soporte de NetApp y descargue la versión más reciente de Astra Control Center de NetApp. Para ello, es necesario disponer de una licencia adjunta a su cuenta de NetApp. Después de descargar el tarball, transfiéralo a la estación de trabajo.
+

NOTE: Para empezar con una licencia de prueba de Astra Control, visite https://cloud.netapp.com/astra-register["Sitio de registro de Astra"^].

. Cree o obtenga el archivo kubeconfig con acceso de administrador al clúster {k8s_usercluster_name} en el que se va a instalar Astra Control Center.
. Cambie el directorio a. `na_astra_control_suite`.
+
[source, cli]
----
cd na_astra_control_suite
----
. Edite el `vars/vars.yml` archive y rellene las variables con la información necesaria.
+
[source, cli]
----
#Define whether or not to push the Astra Control Center images to your private registry [Allowed values: yes, no]
push_images: yes

#The directory hosting the Astra Control Center installer
installer_directory: /home/admin/

#Specify the ingress type. Allowed values - "AccTraefik" or "Generic"
#"AccTraefik" if you want the installer to create a LoadBalancer type service to access ACC, requires MetalLB or similar.
#"Generic" if you want to create or configure ingress controller yourself, installer just creates a ClusterIP service for traefik.
ingress_type: "AccTraefik"

#Name of the Astra Control Center installer (Do not include the extension, just the name)
astra_tar_ball_name: astra-control-center-22.04.0

#The complete path to the kubeconfig file of the kubernetes/openshift cluster Astra Control Center needs to be installed to.
hosting_k8s_cluster_kubeconfig_path: /home/admin/cluster-kubeconfig.yml

#Namespace in which Astra Control Center is to be installed
astra_namespace: netapp-astra-cc

#Astra Control Center Resources Scaler. Leave it blank if you want to accept the Default setting.
astra_resources_scaler: Default

#Storageclass to be used for Astra Control Center PVCs, it must be created before running the playbook [Leave it blank if you want the PVCs to use default storageclass]
astra_trident_storageclass: basic

#Reclaim Policy for Astra Control Center Persistent Volumes [Allowed values: Retain, Delete]
storageclass_reclaim_policy: Retain

#Private Registry Details
astra_registry_name: "docker.io"

#Whether the private registry requires credentials [Allowed values: yes, no]
require_reg_creds: yes

#If require_reg_creds is yes, then define the container image registry credentials
#Usually, the registry namespace and usernames are same for individual users
astra_registry_namespace: "registry-user"
astra_registry_username: "registry-user"
astra_registry_password: "password"

#Kuberenets/OpenShift secret name for Astra Control Center
#This name will be assigned to the K8s secret created by the playbook
astra_registry_secret_name: "astra-registry-credentials"

#Astra Control Center FQDN
acc_fqdn_address: astra-control-center.cie.netapp.com

#Name of the Astra Control Center instance
acc_account_name: ACC Account Name

#Administrator details for Astra Control Center
admin_email_address: admin@example.com
admin_first_name: Admin
admin_last_name: Admin
----
. Ejecute el libro de estrategia para implementar Astra Control Center. El libro de estrategia requiere privilegios raíz para determinadas configuraciones.
+
Ejecute el siguiente comando para ejecutar el libro de estrategia si el usuario que ejecuta la tableta playbook es raíz o tiene un sudo configurado sin contraseñas.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml
----
+
Si el usuario tiene configurado un acceso sudo basado en contraseña, ejecute el siguiente comando para ejecutar la libro de estrategia y, a continuación, introduzca la contraseña sudo.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml -K
----

