= 
:allow-uri-read: 


. Configure las credenciales.
. Crear tipos de credenciales. En el caso de las soluciones que implican ONTAP, debe configurar el tipo de credencial para que coincida con las entradas de nombre de usuario y contraseña, también añadiremos entradas para Cloud Central y AWS.
+
.. Desplácese hasta Administration → Credential Types y haga clic en Add.
.. Escriba el nombre y la descripción.
.. Pegue el siguiente contenido en Configuración de entrada:
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Pegue el siguiente contenido en Injector Configuration y haga clic en Save:
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. Cree credenciales para ONTAP/CVO/AWS
+
.. Desplácese hasta Resources → Credentials y haga clic en Add.
.. Introduzca los detalles de nombre y organización para los credenciales de ONTAP
.. Seleccione el tipo de credencial que se creó en el paso anterior.
.. En Type Details, introduzca el nombre de usuario y la contraseña de los clústeres de origen y CVO, Cloud Central/Manager, AWS Access/Secret Key y Cloud Central Refresh Token.
.. Haga clic en Guardar


. Crear credenciales para Oracle (origen)
+
.. Desplácese hasta Resources → Credentials y haga clic en Add.
.. Introduzca los detalles de nombre y organización del host de Oracle
.. Seleccione el tipo de credencial máquina.
.. En Type Details, introduzca el nombre de usuario y la contraseña para los hosts de Oracle.
.. Seleccione el método de escalamiento de privilegios correcto e introduzca el nombre de usuario y la contraseña.
.. Haga clic en Guardar


. Crear credenciales para el destino Oracle
+
.. Desplácese hasta Resources → Credentials y haga clic en Add.
.. Introduzca los detalles de nombre y organización para el host de recuperación ante desastres de Oracle
.. Seleccione el tipo de credencial máquina.
.. En Type Details, introduzca el nombre de usuario (ec2-user o si lo ha cambiado de valor predeterminado introduzca ese valor) y la clave privada SSH
.. Seleccione el método de escalado de privilegios correcto (sudo) e introduzca el nombre de usuario y la contraseña si es necesario.
.. Haga clic en Guardar



