= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS admite almacenamiento de NetApp con las siguientes configuraciones:

* FSX ONTAP como almacenamiento conectado como invitado
* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* FSX ONTAP como almacén de datos NFS complementario


Vea el detalles link:aws/aws-guest.html["Opciones de almacenamiento de conexión para invitado para VMC"]. Vea el detalles link:aws/aws-native-nfs-datastore-option.html["Opciones suplementarias de almacén de datos de NFS para VMC"].

Vea el detalles link:aws-guest.html["Opciones de almacenamiento de conexión para invitado para VMC"]. Vea el detalles link:aws-native-nfs-datastore-option.html["Opciones suplementarias de almacén de datos de NFS para VMC"].

--
.Azure / AVS
--
Azure admite almacenamiento de NetApp en las siguientes configuraciones:

* Azure NetApp Files (ANF) como almacenamiento conectado como invitado
* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Azure NetApp Files (ANF) como almacén de datos NFS complementario


Vea el detalles link:azure/azure-guest.html["Opciones de almacenamiento de Guest Connect para AVS"]. Vea el detalles link:azure/azure-native-nfs-datastore-option.html["Opciones complementarias de almacén de datos NFS para AVS"].

Vea el detalles link:azure-guest.html["Opciones de almacenamiento de Guest Connect para AVS"]. Vea el detalles link:azure-native-nfs-datastore-option.html["Opciones complementarias de almacén de datos NFS para AVS"].

--
.GCP/GCVE
--
Google Cloud es compatible con almacenamiento de NetApp en las siguientes configuraciones:

* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* Cloud Volumes Service (CVS) como almacenamiento conectado como invitado
* Cloud Volumes Service (CVS) como almacén de datos NFS complementario


Vea el detalles link:gcp/gcp-guest.html["Opciones de almacenamiento de Guest Connect para GCVE"].

Vea el detalles link:gcp-guest.html["Opciones de almacenamiento de Guest Connect para GCVE"].

Más información acerca de link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Soporte de almacén de datos de Cloud Volumes Service de NetApp para Google Cloud VMware Engine (blog de NetApp)"^] o. link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Cómo usar CVS de NetApp como almacenes de datos para Google Cloud VMware Engine (blog de Google)"^]

--
====