= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
En esta sección se describe cómo configurar y gestionar VMware Cloud en AWS SDDC y utilizarlo en combinación con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP a VMC de AWS.

El proceso de configuración puede dividirse en los siguientes pasos:

* Poner en marcha y configurar VMware Cloud para AWS
* Conecte VMware Cloud a FSX ONTAP


Vea el detalles link:aws-setup.html["Pasos de configuración para VMC"].

Vea el detalles link:aws-setup.html["Pasos de configuración para VMC"].

--
.Azure / AVS
--
En esta sección se describe cómo configurar y gestionar la solución VMware de Azure y utilizarla en combinación con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento en invitado es el único método compatible para conectar Cloud Volumes ONTAP a la solución VMware Azure.

El proceso de configuración puede dividirse en los siguientes pasos:

* Registre el proveedor de recursos y cree un cloud privado
* Conéctese a una puerta de enlace de red virtual ExpressRoute nueva o existente
* Validar la conectividad de red y acceder al cloud privado


Vea el detalles link:azure-setup.html["Pasos de configuración para AVS"].

Vea el detalles link:azure-setup.html["Pasos de configuración para AVS"].

--
.GCP/GCVE
--
En esta sección se describe cómo configurar y gestionar GCVE y cómo utilizarlo junto con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP y Cloud Volumes Services a GCVE.

El proceso de configuración puede dividirse en los siguientes pasos:

* Implementar y configurar GCVE
* Active el acceso privado a GCVE


Vea el detalles link:gcp-setup.html["Pasos de configuración para GCVE"].

Vea el detalles link:gcp-setup.html["Pasos de configuración para GCVE"].

--
====