---
sidebar: sidebar 
permalink: databases/azure_ora_nfile_usecase.html 
summary: Esta guía de mejores prácticas ofrece detalles de una solución para poner en marcha y proteger bases de datos de Oracle en almacenamiento de archivos Azure NetApp y Azure VM. 
keywords: database, Oracle, Azure NetApp files, Azure 
---
= TR-4954: Puesta en marcha y protección de bases de datos de Oracle en Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta guía de mejores prácticas ofrece detalles de una solución para poner en marcha y proteger bases de datos de Oracle en almacenamiento de archivos Azure NetApp y Azure VM.

Autor(es): Allen Cao, Niyaz Mohamed, NetApp



== Descripción general

Muchas bases de datos empresariales críticas para la misión de Oracle aún se encuentran en las instalaciones, y muchas empresas tratan de migrar estas bases de datos de Oracle a un cloud público. A menudo, estas bases de datos de Oracle están centradas en aplicaciones y, por ello, requieren configuraciones específicas del usuario, una funcionalidad que falta en muchas ofertas de cloud público de base de datos como servicio. Por lo tanto, el panorama actual de las bases de datos exige una solución de base de datos de Oracle basada en el cloud público creada a partir de un servicio de almacenamiento y computación escalable de alto rendimiento que pueda satisfacer requisitos particulares. Las instancias de computación de máquina virtual de Azure y el servicio de almacenamiento de Azure NetApp Files pueden ser las piezas que faltan de este rompecabezas para crear y migrar sus cargas de trabajo de bases de datos de Oracle esenciales a una nube pública.



== Máquina virtual de Azure

Las máquinas virtuales de Azure son uno de los diversos tipos de recursos de computación bajo demanda y escalables que ofrece Azure. Por lo general, se elige una máquina virtual cuando se necesita más control sobre el entorno de computación de lo que ofrecen las otras opciones. Las máquinas virtuales Azure ofrecen una forma rápida y sencilla de crear un equipo con configuraciones específicas necesarias para ejecutar su base de datos de Oracle, ya sea para cargas de trabajo con un uso intensivo de la computación o de la memoria. Las máquinas virtuales de una red virtual de Azure se pueden conectar fácilmente a la red de la organización, por ejemplo, a través de un túnel VPN seguro.



== Azure NetApp Files (ANF)

Azure NetApp Files es un servicio de Microsoft totalmente gestionado que llevará la carga de trabajo de su base de datos al cloud de forma más rápida y segura que nunca. Se ha diseñado para satisfacer los requisitos centrales de la ejecución de cargas de trabajo de alto rendimiento, como las bases de datos de Oracle en el cloud, y proporciona niveles de rendimiento que reflejan la gama real de demandas de IOPS, baja latencia, alta disponibilidad, alta durabilidad, capacidad de gestión a escala, así como backup, recuperación y clonado rápidos y eficientes. Estas funcionalidades son posibles porque Azure NetApp Files se basa en los sistemas ONTAP all-flash físicos de NetApp que se ejecutan en el entorno de centro de datos Azure. Azure NetApp Files está completamente integrado en los centros de datos y el portal de Azure y los clientes pueden utilizar las mismas API y la misma interfaz gráfica para crear y gestionar archivos compartidos que cualquier otro objeto de Azure. Con Azure NetApp File, puede desbloquear todas las funcionalidades de Azure sin riesgos adicionales, costes ni tiempo, y confiar en el único servicio de archivos empresariales nativo de Azure.



== Conclusión

En esta documentación se describe detalladamente cómo implementar, configurar y proteger una base de datos de Oracle con un servicio de máquina virtual de Azure y almacenamiento de Azure NetApp Files que ofrece rendimiento y durabilidad similares a un sistema en las instalaciones. Para obtener instrucciones sobre prácticas recomendadas, consulte TR-4780 link:https://www.netapp.com/media/17105-tr4780.pdf["Bases de datos de Oracle en Microsoft Azure"^]. Y lo que es más importante, NetApp también proporciona kits de herramientas de automatización que automatizan la mayoría de las tareas necesarias para la puesta en marcha, la configuración, la protección de datos, la migración y la gestión de la carga de trabajo de la base de datos de Oracle en el cloud público de Azure. Los kits de herramientas de automatización están disponibles para su descarga en el sitio público de GitHub de NetApp: link:https://github.com/NetApp-Automation/["Automatización de NetApp"^].
