---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prerequisite.html 
summary: Ciertos requisitos previos deben configurarse tanto en las instalaciones como en el cloud antes de ejecutar las cargas de trabajo de las bases de datos del cloud híbrido. En la siguiente sección se proporciona un resumen de alto nivel de este proceso, y los siguientes enlaces proporcionan información adicional sobre la configuración necesaria del sistema. 
keywords: workflow, prerequisites, licensing, networking, security 
---
= Configuración de requisitos previos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_requirements.html["Anterior: Requisitos de las soluciones."]

Ciertos requisitos previos deben configurarse tanto en las instalaciones como en el cloud antes de ejecutar las cargas de trabajo de las bases de datos del cloud híbrido. En la siguiente sección se proporciona un resumen de alto nivel de este proceso, y los siguientes enlaces proporcionan información adicional sobre la configuración necesaria del sistema.



== En el entorno local

* Instalación y configuración de SnapCenter
* Configuración del almacenamiento del servidor de bases de datos local
* Requisitos de licencia
* Redes y seguridad
* Automatización




== Cloud público

* Un inicio de sesión en Cloud Central de NetApp
* Acceso a la red desde un explorador Web hasta varios puntos finales
* Una ubicación de red para un conector
* Permisos del proveedor de cloud
* Creación de redes para servicios individuales


Consideraciones importantes:

. ¿Dónde se debe poner en marcha Cloud Manager Connector?
. Ajuste de tamaño y arquitectura de Cloud Volume ONTAP
. ¿Nodo único o alta disponibilidad?


Los siguientes enlaces proporcionan más información:

link:hybrid_dbops_snapcenter_prereq_onprem.html["En el entorno local"]

link:hybrid_dbops_snapcenter_prereq_cloud.html["Cloud público"]

link:hybrid_dbops_snapcenter_prereq_onprem.html["Siguiente: Requisitos previos en las instalaciones."]
