---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_getting_started.html 
summary: En esta sección se proporciona un resumen de las tareas que deben completarse para cumplir los requisitos previos, tal como se describen en la sección anterior. En la siguiente sección, se proporciona una lista de tareas de alto nivel para las operaciones de cloud público y en las instalaciones. Se puede acceder a los procesos y procedimientos detallados haciendo clic en los enlaces correspondientes. 
keywords: introduction, workflow 
---
= Información general del inicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


[role="lead"]
En esta sección se proporciona un resumen de las tareas que deben completarse para cumplir los requisitos previos, tal como se describen en la sección anterior. En la siguiente sección, se proporciona una lista de tareas de alto nivel para las operaciones de cloud público y en las instalaciones. Se puede acceder a los procesos y procedimientos detallados haciendo clic en los enlaces correspondientes.



== Localmente

* Configure el usuario administrador de la base de datos en SnapCenter
* Requisitos previos de instalación del plugin de SnapCenter
* Instalación del complemento de host de SnapCenter
* Descubrimiento de recursos DE BASE de datos
* Configurar la conexión entre iguales de clústeres de almacenamiento y la replicación de volúmenes de base de datos
* Añada la SVM de almacenamiento de base de datos de CVO a SnapCenter
* Configure la política de backup de la base de datos en SnapCenter
* Implemente una política de backup para proteger la base de datos
* Validar el backup




== Cloud público de AWS

* Comprobación previa al vuelo
* Pasos para implementar Cloud Manager y Cloud Volumes ONTAP en AWS
* Ponga en marcha la instancia de EC2 para cargas de trabajo de bases de datos


Haga clic en los siguientes enlaces para obtener información detallada:

link:hybrid_dbops_snapcenter_getting_started_onprem.html["En el entorno local"], link:hybrid_dbops_snapcenter_getting_started_aws.html["Cloud público: AWS"]
