---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Esta página describe el método automatizado para poner en marcha Oracle19c en el almacenamiento ONTAP de NetApp. 
---
= Descripción general de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Puesta en marcha automatizada de Oracle19c para ONTAP en NFS

Las organizaciones están automatizando sus entornos para conseguir eficiencias, acelerar las puestas en marcha y reducir el esfuerzo manual. Se están utilizando herramientas de gestión de configuraciones como Ansible para optimizar las operaciones de las bases de datos empresariales. En esta solución, demostramos cómo puede usar Ansible para automatizar el aprovisionamiento y la configuración de Oracle 19c con ONTAP de NetApp. Al permitir que los administradores de almacenamiento, los administradores de sistemas y los administradores de bases de datos instalen de forma constante y rápida almacenamiento nuevo, configuren los servidores de la base de datos e instalen el software Oracle 19c, obtiene las siguientes ventajas:

* Elimine las complejidades de diseño y los errores humanos e implemente una puesta en marcha consistente y mejores prácticas repetibles
* Reducir el tiempo de aprovisionamiento del almacenamiento, configuración de hosts de bases de datos e instalación de Oracle
* Aumente la productividad de los administradores de bases de datos, de sistemas y de almacenamiento
* Facilite un escalado del almacenamiento y las bases de datos


NetApp proporciona a los clientes módulos y funciones Ansible validados para acelerar la puesta en marcha, la configuración y la gestión del ciclo de vida de su entorno de base de datos de Oracle. Esta solución proporciona instrucciones y el código del libro de estrategia de Ansible, para ayudarle a:

* Crear y configurar el almacenamiento NFS de ONTAP para la base de datos de Oracle
* Instale Oracle 19c en RedHat Enterprise Linux 7/8 o Oracle Linux 7/8
* Configurar Oracle 19c en el almacenamiento NFS de ONTAP


Para obtener más información o para empezar, consulte los vídeos de resumen que aparecen a continuación.



=== Implementaciones de AWX/Tower

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d844a9c3-4eb3-4512-bf21-b01200f09f66["Parte 1: Introducción, requisitos, detalles de automatización y configuración inicial de AWX/Tower"]
* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6da1b960-e1c9-4950-b750-b01200f0bdfa["Parte 2: Variables y ejecución de la guía"]




=== Puesta en marcha de CLI

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=373e7f2a-c101-4292-a3e4-b01200f0d078["Parte 1: Introducción, requisitos, detalles de la automatización y configuración del host de Ansible Control"]
* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d58ebdb0-8bac-4ef9-b4d1-b01200f95047["Parte 2: Variables y ejecución de la guía"]

