---
sidebar: sidebar 
permalink: databases/sql-srv-anf_conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: Tanto si va a centrarse en un cloud híbrido o en un cloud integral con bases de datos con ampliación, Azure NetApp Files ofrece opciones excelentes para poner en marcha y gestionar las cargas de trabajo de las bases de datos, a la vez que reduce el TCO y permite que los requisitos de datos se reduzcan hasta la capa de la aplicación. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Tanto si va a centrarse en un cloud híbrido o en un cloud integral con bases de datos con ampliación, Azure NetApp Files ofrece opciones excelentes para poner en marcha y gestionar las cargas de trabajo de las bases de datos, a la vez que reduce el TCO y permite que los requisitos de datos se reduzcan hasta la capa de la aplicación.

En este documento se tratan recomendaciones para la planificación, el diseño, la optimización y el escalado de implementaciones de Microsoft SQL Server con Azure NetApp Files, que pueden variar en gran medida entre implementaciones. Una solución adecuada depende tanto de los detalles técnicos de la implantación como de los requisitos empresariales que impulsan el proyecto.



== Puntos

Los puntos clave de este documento son:

* Ahora puede utilizar Azure NetApp Files para alojar la base de datos y el testigo de recurso compartido de archivos para el clúster de SQL Server.
* Puede aumentar los tiempos de respuesta de las aplicaciones y ofrecer una disponibilidad del 99.9999 % para proporcionar acceso a los datos de SQL Server cuando y donde sea necesario.
* Puede simplificar la complejidad general de la puesta en marcha y la gestión continua de SQL Server, como la segmentación de RAID, con redimensionamiento sencillo e instantáneo.
* Puede confiar en las funciones de operaciones inteligentes para ayudarle a poner en marcha bases de datos de SQL Server en cuestión de minutos y acelerar los ciclos de desarrollo.
* Si Azure Cloud es el destino, Azure NetApp Files es la solución de almacenamiento adecuada para una puesta en marcha optimizada.

