---
sidebar: sidebar 
permalink: databases/tr-4250-link.html 
keywords:  
summary:  
---
= TR-4250: SAP con Oracle en UNIX y NFS con Clustered Data ONTAP de NetApp y SnapManager para SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer: NetApp

El TR-4250 aborda los retos que se presentan al diseñar soluciones de almacenamiento compatibles con los productos paquete empresarial de SAP mediante una base de datos de Oracle. El objetivo principal de este documento es los retos comunes de diseño, puesta en marcha, funcionamiento y gestión de la infraestructura de almacenamiento a los que se enfrentan los líderes de negocio Y DE TI que utilizan la última generación de soluciones SAP. Las recomendaciones de este documento son genéricas; no son específicas de una aplicación SAP ni del tamaño y alcance de la implementación SAP. En TR-4250 se asume que el lector tiene conocimientos básicos de la tecnología y el funcionamiento de los productos de NetApp y SAP. TR-4250 se desarrolló en función de la interacción del personal técnico de NetApp, SAP, Oracle y nuestros clientes.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["TR-4250: SAP con Oracle en UNIX y NFS con Clustered Data ONTAP de NetApp y SnapManager para SAP 3.4"^]
