---
sidebar: sidebar 
permalink: databases/tr-4722.html 
keywords:  
summary:  
---
= TR-4722: Mejores prácticas de base de datos de MySQL en NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Anup Bharti, Manohar Kulkarni y Jeffrey Steiner NetApp

MySQL y sus variantes, como MariaDB y Percona, son ampliamente utilizados en muchas aplicaciones empresariales. Estas aplicaciones van desde sitios de redes sociales globales y sistemas masivos de comercio electrónico hasta sistemas de alojamiento de pymes que contienen miles de instancias de bases de datos. Este documento describe los requisitos de configuración y proporciona orientación sobre la configuración de ajuste y almacenamiento para implementar MySQL en el software de gestión de datos NetApp® ONTAP®. Para determinar si el entorno, las configuraciones y las versiones especificadas en este informe admiten su entorno, consulte la herramienta de matriz de interoperabilidad (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["TR-4722: Mejores prácticas de base de datos de MySQL en NetApp ONTAP"^]
