---
sidebar: sidebar 
permalink: ehc/dro/azure-dro-overview.html 
keywords: NetApp Solutions, hybrid, multicloud, multi cloud, hyperscalers, vmware, disaster recovery orchestrator, DRO 
summary:  
---
= TR-4955: Recuperación ante desastres con Azure NetApp Files (ANF) y la solución VMware de Azure (AVS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Niyaz Mohamed, NetApp



== Descripción general



== Primeros pasos



== Instalación DE DRO



== Configuración DE DRO



== Beneficios

* El uso de la replicación SnapMirror eficiente y resiliente.
* Recuperación en cualquier momento disponible con la retención de copias de Snapshot.
* Automatización completa de todos los pasos necesarios para recuperar cientos o miles de equipos virtuales a partir de los pasos de almacenamiento, informática, red y validación de aplicaciones.
* Recuperación de la carga de trabajo con la tecnología FlexClone de ONTAP mediante un método que no cambia el volumen replicado.
+
** Evita el riesgo de que se dañen los datos para volúmenes o copias Snapshot.
** Evita interrupciones de replicación durante los flujos de trabajo de pruebas de recuperación ante desastres.
** Uso potencial de datos de recuperación ante desastres con recursos de cloud computing para flujos de trabajo más allá de la recuperación ante desastres, como DevTest, pruebas de seguridad, pruebas de parches o actualizaciones, y pruebas de corrección.


* Optimización de la CPU y la RAM para ayudar a reducir los costes del cloud al permitir la recuperación en clústeres informáticos más pequeños.

