---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-data-encryption-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: Todos los volúmenes de Cloud Volumes Service se cifran en reposo mediante el cifrado AES-256, lo que significa que todos los datos de usuario escritos en medios se cifran y solo se pueden descifrar con una clave por volumen. 
---
= Cifrado de datos en reposo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-data-encryption-in-transit.html["Anterior: Cifrado de datos en tránsito."]

[role="lead"]
Todos los volúmenes de Cloud Volumes Service se cifran en reposo mediante el cifrado AES-256, lo que significa que todos los datos de usuario escritos en medios se cifran y solo se pueden descifrar con una clave por volumen.

* Para CVS-SW, se usan claves generadas por Google.
* Para CVS-Performance, las claves por volumen se almacenan en un gestor de claves incorporado en Cloud Volumes Service.


A partir de noviembre de 2021, ya estaba disponible la funcionalidad de obtener una vista previa de las claves de cifrado gestionadas por el cliente (CMEK). Esto permite cifrar las claves por volumen con una clave maestra por proyecto y por región alojada en https://["Servicio de administración de claves (KMS) de Google."^] KMS le permite asociar gestores de claves externos.

Para obtener información acerca de la configuración de KMS para CVS-Performance, consulte https://["Configurar las claves de cifrado gestionadas por el cliente"^].

link:ncvs-gc-firewall.html["Siguiente: Firewall."]
