---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-additional-information.html 
keywords:  
summary:  
---
= Información adicional, historial de versiones e información de contacto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-service-operation.html["Anterior: Operación de mantenimiento."]

[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Documentación de Google Cloud para Cloud Volumes Service
+
https://["https://cloud.google.com/architecture/partners/netapp-cloud-volumes/"^]

* Acceso a servicios privados de Google
+
https://["https://cloud.google.com/vpc/docs/private-services-access?hl=en_US"^]

* Documentación de productos de NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]

* Programa de módulos de validación criptográfico—NetApp CryptoMod
+
https://["https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144"^]

* La solución de NetApp para ransomware
+
https://["https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745"^]

* TR-4616: Kerberos de NFS en ONTAP
+
https://["https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Mayo de 2022 | Versión inicial. 
|===


== Póngase en contacto con nosotros

Háganos saber cómo podemos mejorar este informe técnico.

Póngase en contacto con nosotros en correo electrónico: doccomments@netapp.com[doccomments@netapp.com]. Incluir EL INFORME TÉCNICO 4918 en el asunto.
