---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-dual-protocol-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: Cloud Volumes Service ofrece la capacidad de compartir los mismos conjuntos de datos tanto a clientes SMB como NFS, a la vez que mantiene permisos de acceso adecuados de doble protocolo. Esto se realiza coordinando la asignación de identidades entre protocolos y utilizando un servidor LDAP de backend centralizado para proporcionar las identidades de UNIX a Cloud Volumes Service. Puede utilizar Windows Active Directory para proporcionar facilidad de uso a los usuarios de Windows y UNIX. 
---
= Protocolo doble/multiprotocolo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Cloud Volumes Service permite compartir los mismos conjuntos de datos tanto con clientes SMB como NFS, a la vez que mantiene los permisos de acceso adecuados (https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["protocolo dual"^]). Esto se realiza coordinando la asignación de identidades entre protocolos y utilizando un servidor LDAP de backend centralizado para proporcionar las identidades de UNIX a Cloud Volumes Service. Puede utilizar Windows Active Directory para proporcionar facilidad de uso a los usuarios de Windows y UNIX.



== Control de acceso

* *Controles de acceso compartido.* determine qué clientes y/o usuarios y grupos pueden acceder a un recurso compartido NAS. Para NFS, las reglas y políticas de exportación controlan el acceso del cliente a las exportaciones. Las exportaciones NFS se gestionan desde la instancia de Cloud Volumes Service. SMB utiliza recursos compartidos de CIFS/SMB y ACL de uso compartido para proporcionar un control más granular a nivel de usuarios y grupos. Solo puede configurar las ACL a nivel de uso compartido desde clientes de SMB mediante https://library.netapp.com/ecmdocs/ECMP1401220/html/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html["Administración de MMC/Computer"^] Con una cuenta que tiene derechos de administrador en la instancia de Cloud Volumes Service (consulte la sección link:ncvs-gc-smb.html#accounts-with-local/builtin-administrator/backup-rights["“Cuentas con derechos de administrador/copia de seguridad local/BUILTIN.”"]).
* *Controles de acceso a archivos.* Controle los permisos a nivel de archivo o carpeta y siempre se administran desde el cliente NAS. Los clientes NFS pueden utilizar bits de modo tradicional (rwx) o ACL de NFSv4. Los clientes de SMB aprovechan los permisos NTFS.


El control de acceso de los volúmenes que sirven datos tanto a NFS como a SMB depende del protocolo en uso. Para obtener información sobre los permisos con protocolo dual, consulte la sección “<<Modelo de permisos>>.”



== Asignación de usuarios

Cuando un cliente accede a un volumen, Cloud Volumes Service intenta asignar el usuario entrante a un usuario válido en la dirección opuesta. Esto es necesario para que se determine el acceso adecuado a través de los protocolos y para garantizar que el usuario que solicita acceso sea realmente lo que afirma ser.

Por ejemplo, si un usuario de Windows llamado `joe` Intenta acceder a un volumen con permisos UNIX a través del bloque de mensajes del servidor y, a continuación, Cloud Volumes Service realiza una búsqueda para encontrar el usuario UNIX correspondiente llamado `joe`. Si existe, los archivos que se escriben en un recurso compartido SMB como usuario de Windows `joe` Aparece como usuario UNIX `joe` De clientes NFS.

Como alternativa, si un usuario de UNIX llamado `joe` Intenta acceder al volumen Cloud Volumes Service con permisos de Windows y el usuario UNIX debe poder asignarlo a un usuario de Windows válido. De lo contrario, se deniega el acceso al volumen.

Actualmente, sólo se admite Active Directory para la gestión de identidades de UNIX externas con LDAP. Para obtener más información acerca de cómo configurar el acceso a este servicio, consulte https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["Creación de una conexión AD"^].



== Modelo de permisos

Cuando se utilizan configuraciones de protocolo dual, Cloud Volumes Service utiliza estilos de seguridad para volúmenes para determinar el tipo de ACL. Estos estilos de seguridad se establecen en función de la especificación del protocolo NAS, o en el caso del protocolo dual, es la opción elegida en el momento de la creación del volumen de Cloud Volumes Service.

* Si solo utiliza NFS, los volúmenes de Cloud Volumes Service utilizan permisos de UNIX.
* Si solo utiliza SMB, los volúmenes de Cloud Volumes Service utilizan permisos NTFS.


Si se crea un volumen de protocolo doble, se puede elegir el estilo de ACL al crear un volumen. Esta decisión debe tomarse en función de la administración de permisos deseada. Si los usuarios gestionan permisos desde clientes de Windows/SMB, seleccione NTFS. Si sus usuarios prefieren usar clientes NFS y chmod/chown, utilice los estilos de seguridad de UNIX.
