---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funcionalidades de NetApp para VMC de AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Obtenga más información acerca de las funcionalidades que NetApp aporta al cloud VMware Cloud (VMC) de AWS: Desde NetApp como dispositivo de almacenamiento conectado como invitado o un almacén de datos NFS complementario a la migración de flujos de trabajo, extensión o repartición al cloud, backup/restauración y recuperación ante desastres.

Para ir a la sección del contenido deseado, seleccione una de las siguientes opciones:

* link:#config["Configuración de VMC en AWS"]
* link:#datastore["Opciones de almacenamiento de NetApp para VMC"]
* link:#solutions["Soluciones cloud de NetApp/VMware"]




== Configuración de VMC en AWS

Al igual que en las instalaciones, la planificación de un entorno de virtualización basado en cloud es crucial para tener un entorno preparado para la producción con éxito a la hora de crear equipos virtuales y migración.

En esta sección se describe cómo configurar y gestionar VMware Cloud en AWS SDDC y utilizarlo en combinación con las opciones disponibles para conectar el almacenamiento de NetApp.


NOTE: El almacenamiento invitado es el único método compatible para conectar Cloud Volumes ONTAP a VMC de AWS.

El proceso de configuración puede dividirse en los siguientes pasos:

* Poner en marcha y configurar VMware Cloud para AWS
* Conecte VMware Cloud a FSX ONTAP


Vea el detalles link:aws-setup.html["Pasos de configuración para VMC"].



== Opciones de almacenamiento de NetApp para VMC

El almacenamiento de NetApp se puede utilizar de varias maneras, ya sea como almacenes de datos NFS conectados o como almacenes de datos NFS complementarios, en VMC de AWS.

Visite link:../ehc-support-configs.html["Opciones de almacenamiento de NetApp admitidas"] si quiere más información.

AWS admite almacenamiento de NetApp con las siguientes configuraciones:

* FSX ONTAP como almacenamiento conectado como invitado
* Cloud Volumes ONTAP (CVO) como almacenamiento conectado como invitado
* FSX ONTAP como almacén de datos NFS complementario


Vea el detalles link:aws-guest.html["Opciones de almacenamiento de conexión para invitado para VMC"]. Vea el detalles link:aws-native-nfs-datastore-option.html["Opciones suplementarias de almacén de datos de NFS para VMC"].



== Casos de uso de soluciones

Con las soluciones de cloud de NetApp y VMware, la puesta en marcha de muchos casos de uso es sencilla en su AWS VMC. Los casos de uso se definen para cada una de las áreas cloud definidas por VMware:

* Protect (incluye recuperación ante desastres y backup/restauración)
* Extender
* Migración


link:aws-solutions.html["Consulte las soluciones de NetApp para AWS VMC"]
