---
sidebar: sidebar 
permalink: ehc/aws/aws-solutions.html 
keywords: NetApp Solutions, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Soluciones de NetApp para Amazon VMware Managed Cloud (VMC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Más información acerca de las soluciones que NetApp aporta a AWS.

VMware define las cargas de trabajo del cloud en una de estas tres categorías:

* Protección (incluida tanto recuperación ante desastres como backup/restauración)
* Migración
* Extender


Consulte las soluciones disponibles en las siguientes secciones.

[role="tabbed-block"]
====
.Proteger
--
* link:aws-guest-dr-solution-overview.html["Recuperación ante desastres con VMC en AWS (invitado conectado)"]
* link:aws-vmc-veeam-fsx-solution.html["Veeam Backup  Restaura en VMC con FSx para ONTAP"]
* link:../dro/dro-overview.html["Recuperación ante desastres (DRO) con FSX para ONTAP y VMC"]


--
.Migración
--
* link:aws-migrate-vmware-hcx.html["Migrar cargas de trabajo al almacén de datos FSxN mediante VMware HCX"]


--
.Extender
--
¡PRÓXIMAMENTE!

--
====