---
sidebar: sidebar 
permalink: vmware/netapp-vsphere8.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Compatibilidad de NetApp para vSphere 8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La alianza de NetApp y VMware es la única alianza donde un único sistema de almacenamiento aborda todos los casos prácticos clave definidos por VMware.



== All-Flash Modern y conectado al cloud para vSphere 8

Las implementaciones de ONTAP se ejecutan en una variedad de plataformas, incluidos dispositivos de ingeniería de NetApp, hardware genérico y en el cloud público. ONTAP ofrece almacenamiento unificado tanto si accede a través de protocolos SAN o NAS como en configuraciones que van desde flash de alta velocidad hasta medios de bajo coste y hasta almacenamiento basado en el cloud. NetApp también ofrece plataformas flash diseñadas específicamente para simplificar y segmentar sus necesidades de almacenamiento sin la creación de silos. Además, NetApp ofrece software que permite mover datos fácilmente entre las instalaciones y el cloud. Por último, NetApp BlueXP proporciona un único panel para gestionar todas estas relaciones y tu huella de almacenamiento.

* link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Plataformas NetApp"]
* link:../ehc/index.html["Multicloud híbrido de NetApp con soluciones de VMware"]

