---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= Multicloud híbrido
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las arquitecturas de multicloud híbrido de VMware con NetApp permiten una integración fluida entre la infraestructura local y los servicios de cloud público, lo que proporciona flexibilidad y escalabilidad.



== Introducción

Este enfoque permite a las empresas migrar fácilmente las cargas de trabajo, optimizar el uso de recursos y mantener operaciones consistentes en ambos entornos.

Para obtener más información sobre escenarios de cloud híbrido con VMware y NetApp, consulte link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["Información general del multicloud híbrido de NetApp con VMware"].



== Escenarios de puesta en marcha de VMware con NetApp

Esta sección describe diversas opciones de puesta en marcha para entornos de VMware en nubes públicas y on-premises. Cada uno de los proveedores de cloud admite una pila de centro de datos definido por software (SDDC) de VMware o una pila de VMware Cloud Foundation (VCF) dentro de sus respectivas ofertas de cloud público.

* *VMware en las instalaciones*


La utilización de VMware con almacenamiento NetApp en las instalaciones proporciona un entorno de virtualización sólido, escalable y flexible. Al emparejar las funciones avanzadas de gestión de datos de NetApp, como la deduplicación, la compresión y las copias Snapshot eficientes con el sistema de almacenamiento adecuado con tecnología de ONTAP, los clientes pueden elegir la plataforma que más les convenga. Esta combinación garantiza un alto rendimiento, fiabilidad y gestión simplificada para cargas de trabajo virtualizadas, lo que mejora la eficiencia general del centro de datos.

* * Solución de Azure VMware*


La solución de VMware para Azure es un servicio de cloud híbrido que permite centros de datos SDDC de VMware completamente funcionales dentro del cloud público de Microsoft Azure. Azure VMware Solution es una solución de primera parte totalmente gestionada y con soporte de Microsoft, verificada por VMware aprovechando la infraestructura de Azure. Esto significa que, cuando se pone en marcha la solución VMware para Azure, el cliente obtiene ESXi de VMware para virtualización informática, VSAN para almacenamiento hiperconvergente NSX y NSX para redes y seguridad, todo ello al tiempo que aprovecha la presencia global de Microsoft Azure, las mejores instalaciones de los centros de datos de su clase y la proximidad al amplio ecosistema de servicios y soluciones de Azure nativos.

* *VMware Cloud en AWS*


VMware Cloud en AWS aporta el software SDDC empresarial de VMware al cloud de AWS con acceso optimizado a los servicios nativos de AWS. Con la tecnología de VMware Cloud Foundation, VMware Cloud en AWS integra los productos de virtualización de redes, almacenamiento e informática de VMware (vSphere de VMware, VSAN de VMware y NSX de VMware) junto con la gestión de VMware vCenter Server, optimizada para ejecutarse en una infraestructura de AWS dedicada, elástica y con configuración básica.

* *Google Cloud VMware Engine*


Google Cloud VMware Engine es una oferta de infraestructura como servicio (IaaS) basada en la infraestructura escalable de alto rendimiento de Google Cloud y la pila de VMware Cloud Foundation: VMware vSphere, vCenter, vSAN y NSX-T. Este servicio permite una ruta rápida a la nube, migrando o ampliando sin problemas las cargas de trabajo de VMware existentes desde entornos on-premises a Google Cloud Platform sin los costes, esfuerzos o riesgos de rediseñar las aplicaciones o rediseñar las operaciones. Se trata de un servicio que vende y recibe soporte de Google, en estrecha colaboración con VMware.
