---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-sc.html 
keywords: vmware, vcf, protect, snapcenter 
summary:  
---
= Proteger cargas de trabajo con SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El complemento de SnapCenter para VMware vSphere mejora la base cloud de VMware al simplificar el backup y la recuperación de datos, garantizar backups consistentes con las aplicaciones y optimizar el almacenamiento con las tecnologías de eficiencia de NetApp.

Admite flujos de trabajo automatizados y operaciones escalables, a la vez que proporciona una integración sin problemas con el cliente vSphere. Con la replicación de SnapMirror que ofrece un backup secundario en las instalaciones o en el cloud, ofrece protección de datos sólida y eficiencia operativa en entornos virtualizados.

Consulte las siguientes soluciones para obtener más información.

* link:vmw-vcf-scv-wkld.html["Proteger dominio de carga de trabajo de VCF"]
* link:vmw-vcf-scv-multiwkld.html["Proteger dominios de carga de trabajo múltiple de VCF"]
* link:vmw-vcf-scv-nvme.html["Proteja el dominio de carga de trabajo de VCF con NVMe"]
* link:vmw-vcf-scv-321.html["3-2-1 Protección de datos para VMware con complemento SnapCenter y backup y recuperación de datos de BlueXP para máquinas virtuales"]

