---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security-ransomware.html 
keywords:  
summary:  
---
= Abordar la seguridad y el ransomware para cargas de trabajo de VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mitigar el riesgo de interrupciones en un entorno VMware es importante para mantener las operaciones empresariales continuas, garantizar la alta disponibilidad de aplicaciones críticas y protegerse frente a la pérdida de datos.



== Introducción

Al aprovechar las funcionalidades avanzadas de NetApp ONTAP en entornos de VMware, las organizaciones pueden garantizar la integridad, la disponibilidad y la seguridad de sus datos.

Vea a continuación cómo estas tecnologías trabajan juntas para ofrecer *seguridad* y *beneficios de respaldo* con mayor detalle.



== Seguridad y ransomware

La seguridad es una preocupación fundamental en los entornos virtualizados y NetApp ONTAP ofrece funciones sólidas para mejorar la seguridad en infraestructuras de VMware. ONTAP ofrece cifrado para datos en reposo y en tránsito, garantizando que la información confidencial esté protegida frente al acceso no autorizado. Las claves de cifrado se gestionan de forma segura y ONTAP admite tanto soluciones de cifrado basadas en software como basadas en hardware. Al integrarse con las herramientas de seguridad de VMware, como las funciones de seguridad integradas de vSphere y las soluciones de seguridad de terceros, ONTAP ayuda a crear un entorno seguro y conforme a las normativas.



== Protección contra ransomware

Los ataques de ransomware representan una amenaza importante para las organizaciones y la combinación de VMware y ONTAP proporciona un sólido mecanismo de defensa. La tecnología Snapshot de ONTAP permite crear copias de Snapshot inmutables que el ransomware no puede modificar ni eliminar. En caso de un ataque, estos snapshots se pueden usar para restaurar rápidamente las máquinas virtuales y los almacenes de datos afectados a su estado previo al ataque, lo que minimiza el tiempo de inactividad y la pérdida de datos. Además, la integración de ONTAP con los sistemas de gestión de eventos e información de seguridad (SIEM) permite supervisar y alertar de forma proactiva de actividades sospechosas. ONTAP también admite la autenticación multifactor (MFA) y el control de acceso basado en roles (RBAC) para mejorar aún más la seguridad.



== Garantía de recuperación frente a ransomware

La garantía contra ransomware de NetApp ofrece a las organizaciones una solución robusta y fiable para protegerse contra los ataques de ransomware. Al aprovechar las funcionalidades avanzadas de NetApp ONTAP, las organizaciones pueden garantizar la seguridad y disponibilidad de sus datos. La garantía aporta tranquilidad: Sabe que, en caso de un ataque de ransomware, los datos se pueden restaurar de forma rápida y eficaz, lo que minimiza el tiempo de inactividad, la pérdida de datos y el impacto económico. Este compromiso con la seguridad y la resiliencia de los datos hace de NetApp un partner ideal para organizaciones que buscan proteger sus activos cruciales frente a las ciberamenazas en constante evolución.



== Funcionalidades de seguridad avanzadas

ONTAP incluye funciones de seguridad avanzadas como multi-tenancy seguro, que aísla los datos y los recursos en entornos multi-tenant, y la auditoría de cumplimiento de normativas, que realiza un seguimiento y registra el acceso a datos confidenciales. Estas funciones garantizan la seguridad de los datos y que las organizaciones pueden demostrar que cumplen con las normativas y reglamentos del sector.



== Resumen

La integración de las funciones de seguridad de ONTAP, como el cifrado, las copias Snapshot inmutables y los controles de acceso avanzados, con las herramientas de VMware proporciona una sólida defensa contra las amenazas cibernéticas, incluido el ransomware. La compatibilidad de ONTAP para multi-tenancy seguro y auditoría de cumplimiento garantiza la protección de datos y el cumplimiento de normativas.

Juntos, NetApp ONTAP y VMware ofrecen una completa solución para asegurar entornos virtualizados que permite a las organizaciones proteger los datos, minimizar el tiempo de inactividad y mantener la continuidad del negocio. La implementación de estas tecnologías ayuda a las empresas a abordar los desafíos de TI modernos y a proteger los activos críticos contra las amenazas de seguridad en constante evolución.
