---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Migrar máquinas virtuales a almacenes de datos respaldados por ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La migración de cargas de trabajo de VMware a NetApp ONTAP simplifica la gestión de datos y mejora el rendimiento mediante funciones de almacenamiento avanzadas de ONTAP, como la deduplicación, la compresión y copias Snapshot eficientes.



== Introducción

Esta migración facilita una integración sin problemas, mejora la protección de datos y una mayor flexibilidad en la gestión de entornos virtualizados, lo que garantiza una transición sin problemas con un tiempo de inactividad mínimo.

Si quiere más información sobre la migración de cargas de trabajo de VMware a almacenes de datos respaldados por ONTAP, consulte el link:https://docs.netapp.com/us-en/netapp-solutions/vmware/migrate-vms-to-ontap-datastore.html["Migrar máquinas virtuales a almacenes de datos de ONTAP"].



== Casos de uso

Hay muchas opciones de migración en términos de origen y destino cuando se piensa en la migración a almacenes de datos respaldados por ONTAP.

* Migración de sistemas de almacenamiento de terceros (incluido vSAN) a almacenes de datos ONTAP.
* Migración de equipos virtuales en el mismo clúster de vSphere
* Migración de equipos virtuales entre varios clústeres de vSphere
* Migración de equipos virtuales entre servidores de vCenter en el mismo dominio de SSO
* Migración de equipos virtuales entre servidores de vCenter en dominios de SSO diferentes
* Migración de máquinas virtuales en distintas ubicaciones de centros de datos
* Migración de sistemas de almacenamiento de terceros (incluido vSAN) a almacenes de datos ONTAP.
* Migración de máquinas virtuales en un entorno de cloud híbrido

