---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Alta disponibilidad con VMware vSphere Metro Storage Cluster (VMSC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La alta disponibilidad de NetApp ONTAP, integrada con VMware vSphere Metro Storage Cluster (VMSC), proporciona una solución sólida para la gestión de VMware Cloud Foundation (VCF) y los dominios de cargas de trabajo de VI.

Esta combinación garantiza una disponibilidad continua de datos, una conmutación fluida al respaldo y recuperación ante desastres entre ubicaciones geográficamente dispersas, lo que mejora la resiliencia y la continuidad operativa para cargas de trabajo críticas. La sincronización activa de SnapMirror permite que los servicios empresariales sigan funcionando incluso si se produce un fallo completo del sitio, permitiendo a las aplicaciones conmutar al respaldo de forma transparente mediante una copia secundaria. No se requiere intervención manual ni secuencias de comandos personalizadas para activar una conmutación por error con SnapMirror Active Sync.

Consulte las siguientes soluciones para obtener más información.

* link:vmw-vcf-vmsc-mgmt-smas.html["Cluster de ampliación para dominio de gestión mediante sincronización activa de SnapMirror"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Stretch Cluster para el dominio de gestión mediante MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Cluster ampliado para dominio de cargas de trabajo VI mediante sincronización activa de SnapMirror"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Cluster ampliado para el dominio de cargas de trabajo de VI mediante MetroCluster"]

