---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-tools-for-vmware.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= Herramientas de ONTAP para VMware (OTV)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere proporcionan una gestión del ciclo de vida integral para máquinas virtuales en entornos VMware que usan los sistemas de almacenamiento de NetApp.



== Introducción

Permite a los administradores gestionar el almacenamiento desde vCenter Server directamente y simplificar el almacenamiento y la gestión de datos para entornos VMware. La herramienta del complemento VMware vSphere Client está diseñada para integrar la funcionalidad del plugin en vSphere Client sin necesidad de ejecutarse dentro de vCenter Server. Esto ofrece aislamiento de complementos y permite la escalabilidad horizontal de complementos que funcionan en entornos vSphere grandes.



== Componentes de Herramientas de ONTAP

* *Virtual Storage Console (VSC)* El VSC incluye la interfaz integrada con el cliente vSphere, donde puede agregar controladores de almacenamiento, aprovisionar almacenes de datos, supervisar el rendimiento de los almacenes de datos y ver y actualizar la configuración del host ESXi.
* * Proveedor VASA* El proveedor de API de VMware vSphere para ONTAP envía información sobre el almacenamiento utilizado por VMware vSphere al servidor vCenter, lo que permite el aprovisionamiento de almacenes de datos de VMware Virtual Volumes (vVols), la creación y el uso de perfiles de capacidad de almacenamiento, la verificación de cumplimiento y la supervisión del rendimiento.
* *Adaptador de replicación de almacenamiento (SRA)* Cuando se habilita y se usa con VMware Site Recovery Manager (SRM), SRA facilita la recuperación de los almacenes de datos de vCenter Server y las máquinas virtuales en caso de fallo, lo que permite la configuración de sitios protegidos y sitios de recuperación para la recuperación ante desastres.


Para obtener más información sobre las herramientas de NetApp ONTAP para VMware, consulte https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Herramientas de ONTAP para documentación de VMware vSphere"].
