---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Plugin de SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El plugin de SnapCenter para VMware vSphere ofrece operaciones de backup y restauración rápidas, eficientes y consistentes con las máquinas virtuales (VM), almacenes de datos y VMDK. Funciona junto con SnapCenter Server, lo que permite la funcionalidad de backup y restauración basadas en aplicaciones para complementos específicos de aplicaciones de SnapCenter.



== Recursos de documentación

Consulte los siguientes recursos de la documentación para obtener más información.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentación del plugin de SnapCenter para VMware vSphere"]




== Recursos de la solución

Consulte la siguiente solución de backup 3-2-1 que incluye el plugin de SnapCenter para VMware vSphere y backup y recuperación de BlueXP para máquinas virtuales.

Informe técnico: link:../ehc/bxp-scv-hybrid-solution.html["3-2-1 Protección de datos para VMware con complemento SnapCenter y backup y recuperación de datos de BlueXP para máquinas virtuales"]

Blog de Tech OnTap: link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1 Protección de datos para VMware con complemento SnapCenter y backup y recuperación de datos de BlueXP para máquinas virtuales"]



== Recursos de vídeo

.Plugin de SnapCenter para VMware vSphere: Requisitos previos de la solución
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.Plugin de SnapCenter para VMware vSphere: Implementación
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de restauración
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - flujo de trabajo de restauración SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]