---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vm-data-collector.html 
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc 
summary:  
---
= Recopilador de datos de VM (VMDC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un componente clave a la hora de ajustar el tamaño y proyectar las posibles oportunidades de optimización es comprender el estado actual del entorno de VMware.



== Introducción

Virtual Machine Data Collector (VMDC) es un kit de herramientas gratuito, ligero y sencillo basado en una interfaz gráfica de usuario para entornos de VMware que permite a los usuarios recopilar información detallada de inventario sobre sus máquinas virtuales, hosts, almacenamiento y redes.

Para obtener más información sobre el recopilador de datos de máquina virtual, consulte link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html["Documentación del recopilador de datos de máquina virtual"].



== Capacidades de VMDC

VMDC es solo una piedra angular para recopilar estadísticas rápidas e instantáneas para proyectar posibilidades de optimización para las licencias de núcleo de VMware junto con vCPU y RAM. Información sobre la infraestructura de datos de NetApp, que requiere la instalación de AUS y recopiladores de datos, debería ser el siguiente paso obvio para comprender la topología detallada de VM, agrupar VM mediante anotaciones, para determinar el tamaño adecuado de las cargas de trabajo y proteger la infraestructura para el futuro.

Muestreo de las métricas recopiladas con VMDC:

* Información para VM
+
** Nombre de VM
** Estado de energía de VM
** Información de CPU de la máquina virtual
** Información de la memoria del equipo virtual
** Ubicación de VM
** Información de red de equipos virtuales
** y sigue


* Rendimiento de VM
+
** Datos de rendimiento para equipos virtuales a un intervalo seleccionado
** Información de lectura/escritura de VM
** Información de IOPS de la máquina virtual
** Latencia de equipos virtuales
** y sigue


* Información del host ESXi
+
** Información del centro de datos del host
** Información del clúster de hosts
** Información del modelo de host
** Información de la CPU del host
** Información de la memoria del host
** y sigue



