---
sidebar: sidebar 
permalink: vmware/vmw-vcf-draas-bxp.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Recuperación ante desastres con DRaaS de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Recuperación ante desastres como servicio (DRaaS) de NetApp BlueXP  Implementación de recuperación ante desastres mediante replicación a nivel de bloque desde un sitio principal a un sitio de recuperación ante desastres.

El servicio DRaaS de BlueXP  es un método eficaz y económico para proteger las cargas de trabajo frente a fallos del sitio y problemas de integridad de los datos, incluidos los ataques de ransomware. Además, NetApp BlueXP  DRaaS mejora esta estrategia al proporcionar una solución de recuperación ante desastres gestionada basada en la nube, que garantiza una recuperación rápida y un tiempo de inactividad mínimo durante los desastres.

Consulte las siguientes soluciones para obtener información técnica.

* link:vmw-dr-draas-vmfs.html["Recuperación ante desastres mediante DRaaS de BlueXP  para almacenes de datos de VMFS"]
* link:vmw-dr-draas-nfs.html["Recuperación ante desastres mediante DRaaS de BlueXP  para almacenes de datos NFS"]

