---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-data-infrastructure-insights.html 
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii 
summary:  
---
= Información sobre la infraestructura de datos (DII)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Información sobre infraestructura de datos de NetApp es una herramienta de supervisión de infraestructuras de cloud que le ofrece una visibilidad completa de su infraestructura.



== Introducción

Con Data Infrastructure Insights, podrá supervisar, solucionar problemas y optimizar todos sus recursos, incluidos los clouds públicos y los centros de datos privados.

Para obtener más información sobre Data Infrastructure Insights, consulte link:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html["Documentación de información sobre infraestructura de datos"].



== Funcionalidades de información de infraestructura de datos

* Data Infrastructure Insights proporciona supervisión de multinube híbrida, lo que le ofrece una capacidad de observación de toda la pila de la infraestructura y las cargas de trabajo.
* Recopiladores de datos para infraestructura y cargas de trabajo heterogéneas, incluido Kubernetes
* Colector Open Telegraf y API abiertas para una fácil integración
* Notificaciones y alertas completas
* Aprendizaje automático para obtener información inteligente
* Optimización de la utilización de recursos
* Paneles integrados o personalizables con filtros avanzados para minimizar el ruido de la pantalla para responder a las preguntas
* Detectar el estado de las operaciones de almacenamiento de ONTAP 
* Proteja los activos empresariales más valiosos, los datos, desde el ransomware o el ataque de destrucción de datos

