---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Aprovisionamiento del entorno VCF con almacenamiento principal
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El almacenamiento de NetApp ONTAP sirve de solución de almacenamiento principal ideal para la gestión de VMware Cloud Foundation (VCF) y los dominios de cargas de trabajo de VI, y ofrece un alto rendimiento, escalabilidad, gestión de datos avanzada y una integración fluida, lo que mejora colectivamente la eficiencia operativa y la protección de datos.

Consulte las siguientes soluciones para obtener información técnica sobre el aprovisionamiento de un entorno VCF en el dominio adecuado y con el protocolo adecuado.

* link:vmw-vcf-mgmt-principal-fc.html["Dominio de gestión con FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Dominio de gestión con NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Dominio de carga de trabajo de infraestructura virtual con FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Dominio de carga de trabajo de infraestructura virtual con NFS"]

