---
sidebar: sidebar 
permalink: vmware/vmw-vcf-migrate.html 
keywords: vmware, vcf, migrate, import 
summary:  
---
= Migración de la infraestructura existente a VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La conversión de un entorno vSphere con almacenes de datos existentes que se ejecutan en ONTAP en un entorno de VMware Cloud Foundation (VCF) implica integrar la infraestructura existente en una arquitectura de cloud privado moderna.

Este proceso aprovecha la flexibilidad del almacenamiento ONTAP para obtener una gestión y un acceso a los datos fluidos. Una vez establecido el dominio de gestión de VCF, los administradores pueden importar eficientemente entornos vSphere adicionales al ecosistema de VCF. Esta integración mejora el uso de recursos, simplifica la gestión de la nube privada y garantiza una transición sin problemas con una interrupción mínima de las cargas de trabajo existentes.

Consulte las siguientes soluciones para conocer los detalles técnicos de cómo convertir una instancia de vCenter.

* link:vmw-vcf-mgmt-nfs.html["Convertir la instancia de vCenter existente a dominio de gestión de VCF (NFS)"]
* link:vmw-vcf-mgmt-fc.html["Convierta la instancia de vCenter (almacén de datos FC) en dominio de gestión de VCF"]

