---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= Expanda Entorno VCF con almacenamiento complementario
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) admite una amplia gama de opciones de almacenamiento complementarias para ampliar el almacenamiento en dominios de gestión VCF y de carga de trabajo VI.

Las herramientas ONTAP de NetApp para VMware vSphere ofrecen una solución eficiente para esta expansión al integrar el almacenamiento de NetApp a la perfección en el entorno VCF. Las herramientas ONTAP simplifican la configuración y la gestión de los almacenes de datos, ya que permiten a los administradores aprovisionar y gestionar el almacenamiento directamente desde vSphere Client. Las funciones avanzadas de ONTAP, como las copias Snapshot, el clonado y la protección de datos, mejoran el rendimiento del almacenamiento, la eficiencia y la escalabilidad dentro del entorno VCF.

Consulte las siguientes soluciones para conocer los detalles técnicos para ampliar el entorno VCF.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["Dominio de gestión con iSCSI"]
* link:vmw-vcf-mgmt-supplemental-fc.html["Dominio de gestión con FC"]
* link:vmw-vcf-viwld-supplemental-vvols.html["Dominio de carga de trabajo de infraestructura virtual con vVols (iSCSI)"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["Dominio de carga de trabajo de infraestructura virtual con vVols (NFS)"]
* link:vmw-vcf-viwld-supplemental-nvme.html["Dominio de carga de trabajo de infraestructura virtual con NVMe/TCP"]
* link:vmw-vcf-viwld-supplemental-fc.html["Dominio de carga de trabajo de infraestructura virtual con FC"]

