---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS en FC como almacén de datos principal de VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este escenario, mostraremos cómo implementar un almacén de datos VMFS con un backend de canal de fibra (FC) para dominios de gestión y carga de trabajo.

Autor: Suresh Thoppay



== Descripción general del escenario

El almacenamiento principal de VCF se refiere a cualquier tipo de almacenamiento que se despliegue, convierta o importe como parte del proceso de configuración del dominio de VCF. Este documento cubre los siguientes escenarios.

[cols="20% 20% 20% 20% 20%"]
|===
| Tipo de almacenamiento | Dominio de gestión - Clúster predeterminado | Dominio de gestión - Clúster adicional | Dominio de Carga de Trabajo de VI: Clúster por Defecto | Dominio de carga de trabajo de VI: Clúster adicional 


| VMFS en FC | *Herramienta de importación* | *Herramienta de importación, SDDC API* | Sí | Sí 
|===


== Requisitos previos

Este escenario requiere los siguientes componentes y configuraciones:

* Un sistema de almacenamiento ONTAP con puertos FC conectados a switches FC.
* SVM creada con LIF de FC.
* VSphere con HBA FC conectados a switches FC.
* La división en zonas objetivo-iniciador único se configura en los switches FC.
+

NOTE: Utilice la interfaz lógica de FC de SVM en la configuración de zona en lugar de puertos FC físicos en sistemas ONTAP.



NetApp recomienda multipath para LUN FC.



== Pasos de despliegue



=== Dominio de gestión - Clúster predeterminado

El almacenamiento principal FC en el clúster inicial solo es compatible con la herramienta de importación «brownfield» VCF. Si VCF se implementa con la herramienta cloudbuilder (hasta la versión 5,2.x), solo se admite VSAN. Consulte https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["Convertir el entorno de vSphere existente en el dominio de gestión"] para obtener más información.



=== Dominio de gestión - Clúster adicional

El clúster de vSphere adicional en el dominio de gestión se puede poner en marcha con las siguientes opciones: * Tener clúster adicional en el entorno de vSphere y utilizar la herramienta de importación brownfield de VCF para convertir el entorno vSphere en dominio de gestión. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Herramientas de ONTAP para VMware vSphere"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager o API de ONTAP"] Se puede utilizar para poner en marcha el almacén de datos VMFS en el clúster vSphere. * Utilice SDDC API para implementar un clúster adicional. Los hosts de vSphere deben tener configurado el almacén de datos VMFS. Utilice https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager o API de ONTAP"] para implementar hosts de LUN en vSphere. * Utilice la interfaz de usuario de SDDC Manager para implementar un clúster adicional. Pero esta opción solo crea un almacén de datos VSAN hasta la versión 5,2.x.



=== Dominio de Carga de Trabajo de VI: Clúster por Defecto

Una vez que el dominio de gestión está activo y en ejecución, se puede crear el dominio de carga de trabajo VI * mediante la interfaz de usuario de SDDC Manager. Los hosts de vSphere deben tener configurado el almacén de datos VMFS. Usar System Manager o ONTAP API para implementar LUN en hosts de vSphere. * Importar un entorno vSphere existente como nuevo dominio de carga de trabajo VI. Se pueden usar las herramientas de ONTAP para VMware vSphere, System Manager o la API de ONTAP para poner en marcha el almacén de datos de VMFS en el clúster de vSphere.



=== Dominio de carga de trabajo de VI: Clúster adicional

Una vez que la carga de trabajo de VI esté activa y en ejecución, se pueden poner en marcha clústeres adicionales con VMFS en LUN FC utilizando las siguientes opciones.

* Clústeres adicionales en el entorno de vSphere importados mediante la herramienta de importación brownfield de VCF. Se pueden usar las herramientas de ONTAP para VMware vSphere, System Manager o la API de ONTAP para poner en marcha el almacén de datos de VMFS en el clúster de vSphere.
* Usando la IU o la API de SDDC Manager para poner en marcha el clúster adicional. Los hosts de vSphere deben tener configurado el almacén de datos VMFS. Usar System Manager o ONTAP API para implementar LUN en hosts de vSphere.




== Información adicional

Para obtener información acerca de la configuración de los sistemas de almacenamiento ONTAP, consulte la link:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre la configuración de VCF, consulte link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentación de VMware Cloud Foundation"].
