---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_mgmt_stretchcluster.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, iscsi 
summary:  
---
= Stretch Cluster con ONTAP para dominios de gestión de VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta situación, mostraremos cómo utilizar las herramientas de ONTAP para VMware vSphere (OTV) para configurar un clúster ampliado para dominios de carga de trabajo y gestión de VCF.

Autor: Suresh Thoppay



== Descripción general del escenario

La solución de cluster ampliado se puede implementar en cluster predeterminado o en cluster adicional en dominios de gestión de VCF o de carga de trabajo. VMFS en FC es compatible tanto con el almacén de datos principal como con los almacenes de datos complementarios. VMFS en iSCSI solo se admite con almacenes de datos complementarios. Consulte IMT para obtener compatibilidad con VMFS en NVMe-oF con sincronización activa de SnapMirror.

.Almacenamiento principal en Management Domain
[%collapsible]
====
Con VCF 5,2 en adelante, el dominio de gestión se puede implementar sin VSAN utilizando la herramienta de importación VCF. La opción convert de la herramienta de importación de VCF permite una puesta en marcha existente de vCenter en un dominio de gestión. Todos los clústeres de vCenter formarán parte del dominio de gestión. Cada clúster debe tener su propio switch distribuido para realizar la conversión. Hasta que la herramienta de importación VCF admita varios perfiles de red, considere la posibilidad de usar VLAN de ampliación para la red de vMotion.

. Implemente hosts de vSphere
. Ponga en marcha un servidor vCenter en un almacén de datos local (vCenter debe coexistir en los hosts de vSphere que se convertirán en el dominio de gestión)
. Ponga en marcha herramientas de ONTAP para VMware vSphere
. Complemento de puesta en marcha de SnapCenter para VMware vSphere (opcional)
. Crear un almacén de datos (la configuración de la zona FC debe estar implementada)
. Migre las máquinas virtuales a un almacén de datos recién creado
. Proteja el clúster de vSphere



NOTE: Cuando el clúster se expanda o se reduzca, deberá actualizar la relación del clúster de hosts en las herramientas de ONTAP para que el clúster indique los cambios realizados en el origen o el destino.

====
.Almacenamiento complementario en Management Domain
[%collapsible]
====
Una vez que el dominio de gestión está en funcionamiento, es posible crear almacenes de datos adicionales mediante las herramientas de ONTAP, que activan la expansión del grupo de coherencia.


TIP: Si hay un clúster de vSphere protegido, todos los almacenes de datos del clúster se protegerán.

Si el entorno VCF se implementa con la herramienta Cloud Builder, para crear el almacenamiento complementario con iSCSI, implemente las herramientas de ONTAP para crear el almacén de datos iSCSI y proteger el clúster vSphere.


NOTE: Cuando el clúster se expanda o se reduzca, deberá actualizar la relación del clúster de hosts en las herramientas de ONTAP para que el clúster indique los cambios realizados en el origen o el destino.

====


== Información adicional

Para obtener información acerca de la configuración de los sistemas de almacenamiento ONTAP, consulte la link:https://docs.netapp.com/us-en/ontap["Documentación de ONTAP 9"] centro.

Para obtener información sobre la configuración de VCF, consulte link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["Documentación de VMware Cloud Foundation"].



== Demostración en vídeo de esta solución

.Cluster de ampliación para VCF con herramientas ONTAP
video::569a91a9-2679-4414-b6dc-b25d00ff0c5a[panopto,width=360]