---
sidebar: sidebar 
permalink: vmware/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: Esta página ofrece una introducción a los vídeos y tutoriales. 
---
= Vídeos y demostraciones sobre virtualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Vea los siguientes vídeos y demostraciones en los que se destacan características específicas de las soluciones de cloud híbrido, virtualización y contenedores.

.Herramientas de ONTAP de NetApp para VMware vSphere
[%collapsible]
====
.Herramientas de ONTAP para VMware: Información general
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Aprovisionamiento de almacén de datos iSCSI de VMware con ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Aprovisionamiento del almacén de datos NFS de VMware con ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.Plugin de SnapCenter para VMware vSphere
[%collapsible]
====
El software SnapCenter de NetApp es una plataforma empresarial fácil de usar para coordinar y administrar de un modo seguro la protección de datos en todas las aplicaciones, bases de datos y sistemas de archivos.

El plugin de SnapCenter para VMware vSphere permite ejecutar operaciones de backup, restauración y conexión para máquinas virtuales, así como operaciones de backup y montaje para almacenes de datos que se registran en SnapCenter directamente en VMware vCenter.

Para obtener más información sobre el plugin de SnapCenter para VMware vSphere, consulte link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Información general sobre el plugin de SnapCenter de NetApp para VMware vSphere"].

.Plugin de SnapCenter para VMware vSphere: Requisitos previos de la solución
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.Plugin de SnapCenter para VMware vSphere: Implementación
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.Plugin de SnapCenter para VMware vSphere: Flujo de trabajo de restauración
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - flujo de trabajo de restauración SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.Soluciones de protección de datos 3-2-1
[%collapsible]
====
Las soluciones de protección de datos 3-2-1 combinan backups primarios y secundarios en las instalaciones mediante la tecnología SnapMirror y copias replicadas en almacenamiento de objetos mediante el backup y la recuperación de datos de BlueXP.

.3-2-1 Protección de datos para almacenes de datos VMFS con plugin SnapCenter para VMware vSphere y backup y recuperación de BlueXP para máquinas virtuales
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud en AWS con AWS FSX para ONTAP de NetApp
[%collapsible]
====
.Almacenamiento conectado como invitado de Windows con FSX ONTAP mediante iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Almacenamiento conectado invitado de Linux con FSX ONTAP mediante NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Ahorro de VMware Cloud en AWS TCO con Amazon FSX para ONTAP de NetApp
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud en un almacén de datos complementario con Amazon FSX para ONTAP de NetApp
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Instalación y configuración de VMware HCX para VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Demostración de migración de VMotion con VMware HCX para VMC y FSxN
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Demostración de migración en frío con VMware HCX para VMC y FSxN
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure VMware Services en Azure con Azure NetApp Files (ANF)
[%collapsible]
====
.Descripción general adicional del almacén de datos de la solución para VMware Azure con Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Recuperación ante desastres de la solución VMware para Azure con Cloud Volumes ONTAP, SnapCenter y JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Demostración de migración en frío con VMware HCX para AVS y ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Demostración de VMotion con VMware HCX para AVS y ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Demostración de migración masiva con VMware HCX para AVS y ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation con NetApp ONTAP
[%collapsible]
====
.Almacenes de datos NFS como almacenamiento principal para dominios de carga de trabajo de VCF
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.Almacenes de datos iSCSI como almacenamiento complementario para dominios de gestión de VCF
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp con VMware Tanzania
[%collapsible]
====
VMware Tanzania permite a los clientes poner en marcha, administrar y gestionar su entorno de Kubernetes a través de vSphere o de VMware Cloud Foundation. Esta cartera de productos de VMware permite a los clientes gestionar todos sus clústeres de Kubernetes relevantes desde un único plano de control al elegir la edición de VMware Tanzu que mejor se adapte a sus necesidades.

Si quiere más información sobre VMware Tanzania, consulte https://tanzu.vmware.com/tanzu["Descripción general de VMware Tanzania"^]. Esta revisión incluye casos de uso, adiciones disponibles y mucho más sobre VMware Tanzu.

.Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 1
video::ZtbXeOJKhrc[youtube,width=360]
.Cómo usar vVols con NetApp y VMware Tanzu Basic, parte 2
video::FVRKjWH7AoE[youtube,width=360]
.Cómo utilizar vVols con NetApp y VMware Tanzu Basic, parte 3
video::Y-34SUtTTtU[youtube,width=360]
====
.Cloud Insights de NetApp
[%collapsible]
====
NetApp Cloud Insights es una plataforma completa de análisis y supervisión diseñada para proporcionar visibilidad y control sobre tu infraestructura on-premises y en la nube.

.NetApp Cloud Insights: Observabilidad para el centro de datos moderno
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====