---
sidebar: sidebar 
permalink: ai/a400-thinksystem-conclusion.html 
keywords: acknowledgements, additional information 
summary: Esta solución de NetApp y Lenovo es una arquitectura flexible de escalado horizontal ideal para introducir la IA en una empresa de gama media. El almacenamiento de NetApp proporciona el mismo rendimiento o superior que el almacenamiento SSD local y ofrece las siguientes ventajas a los científicos de datos, ingenieros de datos y responsables de la toma DE decisiones TECNOLÓGICAS. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La solución de NetApp y Lenovo validada aquí es una arquitectura flexible de escalado horizontal ideal para IA empresarial de gama media.

El almacenamiento de NetApp proporciona el mismo rendimiento o mejor que el almacenamiento SSD local y ofrece las siguientes ventajas a los científicos de datos, ingenieros de datos y responsables de la toma DE decisiones TECNOLÓGICAS:

* Uso compartido de datos sin esfuerzo entre sistemas de IA, análisis y otros sistemas de negocio cruciales. Este uso compartido de datos reduce la sobrecarga de la infraestructura, mejora el rendimiento y optimiza la gestión de datos en toda la empresa.
* Almacenamiento y cálculo escalables independientemente para minimizar los costes y mejorar la utilización de recursos.
* Flujos de trabajo de desarrollo y puesta en marcha optimizados que utilizan copias Snapshot y clones integrados para espacios de trabajo de usuario instantáneos con gestión eficiente del espacio, control de versiones integrado y puesta en marcha automatizada.
* Protección de datos de clase empresarial para recuperación ante desastres y continuidad empresarial.




== Reconocimientos

* Karthikeyan Nagalingam, Ingeniero Técnico de Marketing de NetApp
* Jarrett Upton, Admin, AI Lab Systems, Lenovo




== Dónde encontrar información adicional

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Página de producto de cabinas all-flash de NetApp
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* Página AFF A400 de NetApp
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* Página de producto del software de gestión de datos ONTAP de NetApp
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* Rendim. MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* Prueba de rendimiento de TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* SMI de NVIDIA (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


