---
sidebar: sidebar 
permalink: ai/a400-thinksystem-architecture-adjustments.html 
keywords: adjustments 
summary: La configuración utilizada para la validación se puede ajustar para ajustarse a otros casos de uso. 
---
= Ajustes de arquitectura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La configuración utilizada para esta validación se puede ajustar para ajustarse a otros casos prácticos.



== Ajustes de CPU

Utilizamos un procesador Intel Xeon Platinum 8360Y Skylake para esta validación, según lo recomendado por Lenovo. Esperamos que la CPU equivalente de Cascade Lake, un procesador Intel Xeon Gold 6330, proporcione un rendimiento similar porque esta carga de trabajo no está vinculada a la CPU.



== Aumente la capacidad de almacenamiento

En función de sus necesidades de capacidad de almacenamiento, puede aumentar el espacio de almacenamiento compartido (volumen NFS) bajo demanda siempre que disponga de las bandejas de discos y los modelos de controladora adicionales. Puede hacerlo desde la CLI o desde la interfaz web de NetApp del controlador de almacenamiento como usuario administrador.
