---
sidebar: sidebar 
permalink: ai/ai-sent-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Demostraciones interactivas en 3D
+
http://www.netapp.com/ai["www.netapp.com/ai"^]

* Conecte directamente con un especialista en IA de NetApp
+
https://www.netapp.com/artificial-intelligence/["https://www.netapp.com/artificial-intelligence/"^]

* Descripción de la solución NVDIA base Command Platform con NetApp
+
https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf["https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf"^]

* NetApp para IA 10: Infografía buenas razones
+
https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf["https://www.netapp.com/pdf.html?item=/media/16147-netapp-ai-10-good-reasonspdf.pdf"^]

* IA en la sanidad: Aprendizaje profundo para identificar las lesiones del COVID-19 en exploraciones pulmonares TC
+
https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf["https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf"^]

* AI en la atención sanitaria: Monitorización del uso de la máscara facial en entornos sanitarios documento técnico
+
https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf["https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf"^]

* IA en la sanidad: Informe técnico de imágenes de diagnóstico
+
https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf"^]

* IA para minoristas: Inteligencia artificial de NetApp conversacional con NVIDIA RIVA
+
link:cainvidia_executive_summary.html["Resumen ejecutivo"]

* Resumen de la solución ONTAP AI de NetApp
+
https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf["https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf"^]

* Resumen de la solución del kit de herramientas de operaciones de datos de NetApp
+
https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf["https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf"^]

* Resumen de la solución del plano de control de IA de NetApp
+
https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf["https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf"^]

* Libro electrónico "transformando el sector con los datos impulsan la IA"
+
https://www.netapp.com/pdf.html?item=/media/16968-na-337pdf.pdf["https://www.netapp.com/us/media/na-337.pdf"^]

* Resumen de la solución de IA EF-Series de NetApp
+
https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf["https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf"^]

* Resumen de la solución de NetApp AI y Lenovo ThinkSystem para la inferencia de IA
+
https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf["https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf"^]

* Resumen de la solución NetApp AI y Lenovo ThinkSystem para IA empresarial Y ML
+
https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf["https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf"^]

* NetApp y NVIDIA: Redefiniendo lo que es posible con el vídeo de IA
+
https://www.youtube.com/watch?v=38xw65SteUc["https://www.youtube.com/watch?v=38xw65SteUc"^]


