---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: En esta página se describen las tareas que se deben completar para instalar y configurar NetApp Trident en el clúster Kubernetes. 
---
= Implementación y configuración de Trident de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se describen las tareas que debe completar para instalar y configurar NetApp Trident en su clúster Kubernetes.



== Requisitos previos

Antes de realizar el ejercicio de implementación descrito en esta sección, asumimos que ya ha realizado las siguientes tareas:

. Ya existe un clúster de Kubernetes en funcionamiento y ejecuta una versión de Kubernetes compatible con Trident. Para obtener una lista de las versiones compatibles, consulte https://docs.netapp.com/us-en/trident/["Documentación de Trident"^].
. Ya existe un dispositivo de almacenamiento de NetApp, una instancia definida por software o un servicio de almacenamiento en cloud que Trident admite.




== Instale Trident

Para instalar y configurar NetApp Trident en su clúster de Kubernetes, realice las siguientes tareas desde el host de salto de implementación:

. Implemente Trident mediante uno de los siguientes métodos:
+
** Si utilizó NVIDIA DeepOps para poner en marcha su clúster de Kubernetes, también puede usar NVIDIA DeepOps para implementar Trident en el clúster de Kubernetes. Para poner en marcha Trident con DeepOps, siga https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Instrucciones de puesta en marcha de Trident"] En el sitio de NVIDIA DeepOps GitHub.
** Si no utilizó NVIDIA DeepOPS para poner en marcha su clúster de Kubernetes, o si simplemente prefiere poner en marcha Trident manualmente, puede implementar Trident siguiendo el https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["instrucciones de puesta en funcionamiento"^] En la documentación de Trident. Asegúrese de crear al menos un back-end de Trident y al menos un Kubernetes StorageClass para obtener más información acerca de cómo configurar https://docs.netapp.com/us-en/trident/trident-use/backends.html["Back-ends"^] y.. https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["Clases de almacenamiento"^] Consulte los subapartados vinculados en los documentos de NetApp.
+

NOTE: Si va a poner en marcha la solución del plano de control de IA de NetApp en un POD de IA de ONTAP, consulte link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Ejemplo de Back-ends de Trident para puestas en marcha de ONTAP AI"] Para algunos ejemplos de diferentes Back-ends de Trident que es posible que desee crear y. link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["Ejemplo de una historia Kubernetes para las puestas en marcha de IA de ONTAP"] Puede que desee crear algunos ejemplos de diferentes clases de almacenamiento de Kubernetes.




