---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline, NetApp DataOps Toolkit 
summary: 'Open Source MLOps con NetApp: Use el kit de herramientas NetApp DataOps con Kubeflow' 
---
= Use el kit de herramientas NetApp DataOps con Kubeflow
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s["Kit de herramientas para la ciencia de datos de NetApp para Kubernetes"] Se puede utilizar junto con Kubeflow. El uso del kit de herramientas para la ciencia de datos de NetApp con Kubeflow ofrece las siguientes ventajas:

* Los científicos de datos pueden llevar a cabo operaciones avanzadas de gestión de datos de NetApp, como la creación de copias Snapshot y clones, directamente desde un portátil de Jupyter.
* Las operaciones avanzadas de gestión de datos de NetApp, como la creación de snapshots y clones, se pueden incorporar en flujos de trabajo automatizados mediante el marco de Kubeflow Pipelines.


Consulte la https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s/Examples/Kubeflow["Ejemplos de Kubeflow"] Sección dentro del repositorio de Data Science Toolkit de NetApp, GitHub para obtener información sobre el uso del kit de herramientas con Kubeflow.
