---
sidebar: sidebar 
permalink: ai/aicp_conclusion.html 
keywords: NetApp AI Machine Deep Learning 
summary:  
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Empresas y organizaciones de todos los tamaños y sectores se están decantando por la inteligencia artificial (IA), el aprendizaje automático (ML) y el aprendizaje profundo (DL) para solucionar problemas del mundo real, ofrecer productos y servicios innovadores y obtener una ventaja en un mercado cada vez más competitivo. A medida que las organizaciones aumentan el uso de la IA, EL ML y el AP, deben hacer frente a numerosos retos, como la escalabilidad de la carga de trabajo y la disponibilidad de los datos. Estos desafíos se pueden abordar mediante el uso de la solución de plano de control de IA de NetApp.

Esta solución le permite clonar rápidamente un espacio de nombres de los datos. Además, le permite definir e implementar flujos de trabajo de entrenamiento de IA, ML y DL que incorporan la creación casi instantánea de bases de datos y modelos para su trazabilidad y versionado. Con esta solución, puede rastrear cada entrenamiento de modelo único que se ejecuta en los conjuntos de datos exactos con los que se ha entrenado el modelo y/o validado. Por último, esta solución le permite aprovisionar rápidamente espacios de trabajo de los portátiles Juppyter con acceso a conjuntos de datos masivos.

Dado que esta solución está dirigida a científicos e ingenieros de datos, se requiere una experiencia mínima en NetApp o ONTAP de NetApp. Con esta solución, las funciones de gestión de datos se pueden ejecutar utilizando interfaces y herramientas sencillas y conocidas. Además, esta solución utiliza componentes totalmente de código abierto y libres. Por lo tanto, si ya dispone de almacenamiento de NetApp en su entorno, puede implantar esta solución hoy mismo. Si desea probar esta solución pero no dispone de almacenamiento de NetApp, visite http://cloud.netapp.com/["cloud.netapp.com"^]Y puede tener una solución de almacenamiento de NetApp basada en cloud en un instante.
