---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: Esta página describe las tareas que debe completar para poner en marcha un clúster de Kubernetes en el que desea implementar la solución NetApp AI Control Plane. Si ya tiene un clúster de Kubernetes, puede omitir esta sección siempre que ejecute una versión de Kubernetes compatible con Kubeflow y NetApp Trident. 
---
= Puesta en marcha de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se describen las tareas que debe completar para poner en marcha un clúster de Kubernetes en el que desea implementar la solución de plano de control de IA de NetApp. Si ya tiene un clúster de Kubernetes, puede omitir esta sección siempre que ejecute una versión de Kubernetes compatible con Kubeflow y NetApp Trident. Si desea ver una lista de las versiones de Kubernetes compatibles con ubeflow, consulte la https://www.kubeflow.org/docs/started/getting-started/["Documentación oficial de Kubeflow"^]. Si desea ver una lista de las versiones de Kubernetes compatibles con Trident, consulte https://netapp-trident.readthedocs.io/["Documentación de Trident"^].

En el caso de puestas en marcha de Kubernetes en las instalaciones que incorporan nodos de reconstrucción completa con GPU de NVIDIA, NetApp recomienda usar la herramienta de puesta en marcha de Kubernetes DeepOps de NVIDIA. En esta sección, se describe la puesta en marcha de un clúster de Kubernetes con DeepOps.



== Requisitos previos

Antes de realizar el ejercicio de implementación descrito en esta sección, asumimos que ya ha realizado las siguientes tareas:

. Ya ha configurado todos los nodos Kubernetes con configuración básica (por ejemplo, un sistema NVIDIA DGX que forma parte de un pod ONTAP AI), de acuerdo con instrucciones de configuración estándar.
. Ha instalado un sistema operativo compatible en todos los nodos maestro y de trabajo de Kubernetes y en un host de salto de implementación. Para obtener una lista de los sistemas operativos compatibles con DeepOps, consulte https://github.com/NVIDIA/deepops["Sitio DeepOps GitHub"^].




== Utilice NVIDIA DeepOps para instalar y configurar Kubernetes

Para poner en marcha y configurar su clúster de Kubernetes con NVIDIA DeepOPS, realice las siguientes tareas desde un host de salto de implementación:

. Descargue NVIDIA DeepOps siguiendo las instrucciones de https://github.com/NVIDIA/deepops/tree/master/docs["Página de Inicio"^] En el sitio de NVIDIA DeepOps GitHub.
. Implemente Kubernetes en su clúster siguiendo las instrucciones que se indican en https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Página de la Guía de implementación de Kubernetes"^] En el sitio de NVIDIA DeepOps GitHub.


link:aicp_netapp_trident_deployment_and_configuration_overview.html["Siguiente: Información general sobre la implementación y la configuración de Trident de NetApp."]
