---
sidebar: sidebar 
permalink: ai/aicp_example_trident_operations_overview.html 
keywords: Trident 
summary: MLOps de código abierto con NetApp - Ejemplo de operaciones de Astra Trident 
---
= Ejemplo de operaciones de Astra Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se incluyen ejemplos de distintas operaciones que puede que desee realizar con Astra Trident.



== Importe un volumen existente

Si hay volúmenes existentes en su sistema/plataforma de almacenamiento de NetApp que desea montar en contenedores dentro de su clúster de Kubernetes, pero que no están ligados a las RVP en el clúster, debe importar estos volúmenes. Es posible usar la funcionalidad de importación de volúmenes de Trident para importar estos volúmenes.

Los comandos de ejemplo siguientes muestran la importación de un volumen denominado `pb_fg_all`. Para obtener más información acerca de las EVs, consulte https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentación oficial sobre Kubernetes"^]. Para obtener más información sobre la funcionalidad de importación de volúmenes, consulte https://docs.netapp.com/us-en/trident/index.html["Documentación de Trident"^].

An `accessModes` valor de `ReadOnlyMany` Se especifica en los archivos de especificaciones de PVC de ejemplo. Para obtener más información acerca de `accessMode` consulte https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentación oficial sobre Kubernetes"^].

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== Aprovisione un nuevo volumen

Puede usar Trident para aprovisionar un nuevo volumen en su plataforma o sistema de almacenamiento de NetApp.



=== Aprovisione un nuevo volumen mediante kubectl

Los siguientes comandos de ejemplo muestran el aprovisionamiento de un nuevo volumen FlexVol mediante kubectl.

An `accessModes` valor de `ReadWriteMany` Se especifica en el siguiente archivo de definición de PVC de ejemplo. Para obtener más información acerca de `accessMode` consulte https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentación oficial sobre Kubernetes"^].

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== Aprovisione un nuevo volumen con el kit de herramientas de DataOps de NetApp

También puedes usar el kit de herramientas de DataOps de NetApp para Kubernetes a fin de aprovisionar un volumen nuevo en tu sistema de almacenamiento o plataforma de NetApp. El kit de herramientas DataOps de NetApp para Kubernetes utiliza Trident para aprovisionar volúmenes, pero simplifica el proceso para el usuario. Consulte la link:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["documentación"] para obtener más detalles.
