---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline 
summary: Ejemplos de Juppyter Notebooks y Kubeflow Pipelines 
---
= Ejemplos de cuadernos y canalizaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La https://github.com/NetApp/netapp-data-science-toolkit/tree/main/Kubernetes["Kit de herramientas para la ciencia de datos de NetApp para Kubernetes"] Se puede utilizar junto con Kubeflow. El uso del kit de herramientas para la ciencia de datos de NetApp con Kubeflow ofrece las siguientes ventajas:

* Los científicos de datos pueden llevar a cabo operaciones avanzadas de gestión de datos de NetApp directamente desde un portátil Juppyter.
* Las operaciones avanzadas de gestión de datos de NetApp pueden incorporarse en flujos de trabajo automatizados mediante el marco de canalizaciones de Kubeflow.


Consulte la https://github.com/NetApp/netapp-data-science-toolkit/tree/main/Kubernetes/Examples/Kubeflow["Ejemplos de Kubeflow"] Sección dentro del repositorio de Data Science Toolkit de NetApp, GitHub para obtener información sobre el uso del kit de herramientas con Kubeflow.
