---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: MLOps de código abierto con NetApp - Arquitectura 
---
= Arquitectura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta solución no depende de hardware específico. La solución es compatible con cualquier dispositivo de almacenamiento físico, instancia definida por software o servicio cloud de NetApp compatible con Trident. Entre los ejemplos se incluyen un sistema de almacenamiento de NetApp AFF, Amazon FSx para NetApp ONTAP, Azure NetApp Files o una instancia de NetApp Cloud Volumes ONTAP. Además, la solución se puede implementar en cualquier clúster de Kubernetes, siempre y cuando la versión de Kubernetes utilizada sea compatible con Kubeflow y Astra Trident de NetApp. Si desea ver una lista de las versiones de Kubernetes compatibles con ubeflow, consulte la https://www.kubeflow.org/docs/started/getting-started/["Documentación oficial de Kubeflow"^]. Si desea ver una lista de las versiones de Kubernetes compatibles con Trident, consulte https://docs.netapp.com/us-en/trident/index.html["Documentación de Trident"^]. Consulte las siguientes tablas para obtener información detallada sobre el entorno que se utilizó para validar la solución.

|===
| Componente de software | Versión 


| Flujo de aire Apache | 2.0.1 


| Tabla de Helm para flujo de aire de Apache | 8.0.8 


| Kubeflow | 1,7, puesto en marcha mediante link:https://www.deploykf.org["Desplegar KF"] 0.1.1 


| Kubernetes | 1,26 


| Astra Trident de NetApp | 23,07 
|===


== Soporte técnico

NetApp no ofrece compatibilidad empresarial para Apache Airflow, Kubeflow o Kubernetes. Si está interesado en una plataforma MLOps totalmente compatible, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["Póngase en contacto con NetApp"] Acerca de las soluciones de MLOps totalmente compatibles que NetApp ofrece conjuntamente con partners.
