---
sidebar: sidebar 
permalink: ai/aicp_kubeflow_deployment_overview.html 
keywords: Kubeflow, Prerequisites, Kubernetes, cluster 
summary: 'MLOps de código abierto con NetApp: Implementación de flujo de hipertexto' 
---
= Despliegue de Kubeflow
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se describen las tareas que debe completar para poner en marcha Kubeflow en su clúster de Kubernetes.



== Requisitos previos

Antes de realizar el ejercicio de implementación descrito en esta sección, asumimos que ya ha realizado las siguientes tareas:

. Ya tiene un clúster de Kubernetes en funcionamiento y está ejecutando una versión de Kubernetes que es compatible con la versión de Kubeflow que desea implementar. Para ver una lista de las versiones de Kubernetes compatibles, consulte las dependencias de su versión de Kubeflow en la link:https://www.kubeflow.org/docs/releases/["Documentación oficial de Kubeflow"^].
. Ya ha instalado y configurado NetApp Trident en su clúster de Kubernetes. Para obtener más información sobre Trident, consulte la link:https://docs.netapp.com/us-en/trident/index.html["Documentación de Trident"].




== Establezca el tipo de almacenamiento de Kubernetes predeterminado

Antes de implementar Kubeflow, recomendamos designar un StorageClass predeterminado en su clúster de Kubernetes. El proceso de puesta en marcha de Kubeflow puede intentar aprovisionar nuevos volúmenes persistentes mediante el StorageClass predeterminado. Si no se designa ningún StorageClass como el StorageClass predeterminado, es posible que falle la implementación. Para designar un StorageClass predeterminado en el clúster, realice la siguiente tarea desde el host de salto de implementación. Si ya ha designado un tipo de almacenamiento predeterminado en el clúster, puede omitir este paso.

. Designe una de las clases de almacenamiento existentes como clase de almacenamiento predeterminada. Los comandos de ejemplo siguientes muestran la designación de un StorageClass llamado `ontap-ai-flexvols-retain` Como el tipo de almacenamiento predeterminado.



NOTE: La `ontap-nas-flexgroup` El tipo de backend de Trident tiene un tamaño de RVP mínimo que es bastante grande. De manera predeterminada, Kubeflow intenta suministrar EVs que son sólo unos pocos GBS en tamaño. Por lo tanto, no debe designar un StorageClass que utilice `ontap-nas-flexgroup` Tipo back-end como StorageClass predeterminado para la implementación de Kubeflow.

....
$ kubectl get sc
NAME                                PROVISIONER             AGE
ontap-ai-flexgroups-retain          csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1   csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2   csi.trident.netapp.io   25h
ontap-ai-flexvols-retain            csi.trident.netapp.io   3s
$ kubectl patch storageclass ontap-ai-flexvols-retain -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
storageclass.storage.k8s.io/ontap-ai-flexvols-retain patched
$ kubectl get sc
NAME                                 PROVISIONER             AGE
ontap-ai-flexgroups-retain           csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1    csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2    csi.trident.netapp.io   25h
ontap-ai-flexvols-retain (default)   csi.trident.netapp.io   54s
....


== Opciones de implementación de Kubeflow

Hay muchas opciones diferentes para implementar Kubeflow. Consulte la link:https://www.kubeflow.org/docs/started/installing-kubeflow/["Documentación oficial de Kubeflow"] para acceder a una lista de opciones de puesta en marcha y elija la opción que mejor se ajuste a sus necesidades.


NOTE: Para fines de validación, implementamos Kubeflow 1,7 utilizando link:https://www.deploykf.org["Desplegar KF"] 0,1.1.
