---
sidebar: sidebar 
permalink: ai/aicp_performance_testing.html 
keywords: Performance, Testing, benchmark, Tensorflow, Docker 
summary: Hemos realizado una comparativa simple del rendimiento como parte de la creación de esta solución. Hemos ejecutado varias tareas estándar de prueba de rendimiento de NetApp mediante Kubernetes, y comparamos los resultados de las pruebas de rendimiento con ejecuciones realizadas mediante un sencillo comando Docker run. 
---
= Pruebas de rendimiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Hemos realizado una comparativa simple del rendimiento como parte de la creación de esta solución. Hemos ejecutado varias tareas estándar de prueba de rendimiento de IA de NetApp mediante Kubernetes, y comparamos los resultados de las pruebas de rendimiento con ejecuciones realizadas mediante un sencillo comando Docker run. No observamos diferencias notables en cuanto al rendimiento. Por lo tanto, llegamos a la conclusión de que el uso de Kubernetes para orquestar trabajos de entrenamiento de IA en contenedores no afecta negativamente al rendimiento. Consulte la siguiente tabla para ver los resultados de nuestra comparativa de rendimiento.

|===
| Prueba de rendimiento | Conjunto de datos | Docker Run (imágenes/s) | Kubernetes (imágenes/s) 


| TensorFlow de un solo nodo | Datos sintéticos | 6,667.2475 | 6,661.93125 


| TensorFlow de un solo nodo | ImageNET | 6,570.2025 | 6,530.59125 


| TensorFlow distribuido síncrono de dos nodos | Datos sintéticos | 13,213.70625 | 13,218.288125 


| TensorFlow distribuido síncrono de dos nodos | ImageNET | 12,941.69125 | 12,881.33875 
|===
link:aicp_conclusion.html["Siguiente: Conclusión."]
