---
sidebar: sidebar 
permalink: ai/aipod_lenovo_NVA1172.html 
keywords:  
summary:  
---
= NVA-1172-DESIGN: NetApp AIPod con Lenovo para NVIDIA OVX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Bobby Oommen, Abhinav Singh, Roney Daniel, NetApp

[role="lead"]
Esta arquitectura de referencia combina los servidores OVX Lenovo ThinkSystem certificados por NVIDIA, impulsados por GPU NVIDIA L40S, con redes NVIDIA Spectrum para proporcionar una solución de infraestructura óptima para optimizar e implementar LLMs (modelos de lenguaje grande). El objetivo de este documento es proporcionar orientación sobre el almacenamiento de una configuración OVX. Esta plataforma es adecuada para varias cargas de trabajo de IA generativas, como RAG (Retrieval Augmented Generation), el ajuste y el entrenamiento de modelos ligeros.

link:https://www.netapp.com/pdf.html?item=/media/111933-lenovoaipod-nva-1172-design-v20.pdf["NVA-1172-DESIGN: Guía de diseño OVX de NetApp AIPod con Lenovo para NVIDIA"^]
