---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: 'NetApp AI Pod con sistemas NVIDIA DGX: Conclusión' 
---
= NetApp AI Pod con sistemas NVIDIA DGX: Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_storage.html["Anterior: NetApp AI Pod con sistemas NVIDIA DGX: Diseño de sistemas de almacenamiento y guía de tamaño."]



== Conclusión

La arquitectura de DGX BasePOD es una plataforma de aprendizaje profundo de próxima generación que requiere funcionalidades de gestión de datos y almacenamiento igualmente avanzadas. Combinando DGX BasePOD con los sistemas de NetApp AFF, esta arquitectura es posible implementar casi a cualquier escala, desde un solo DGX A100 emparejado con un sistema de almacenamiento AFF A250 hasta 48 sistemas DGX A100 en un clúster AFF A800 de 24 nodos. Gracias a la superior integración con el cloud y las capacidades definidas por software de NetApp ONTAP, AFF ofrece una completa gama de canalizaciones de datos que abarcan el perímetro, el núcleo y el cloud y que le permitirán llevar a buen puerto sus proyectos de DL.

link:aipod_nv_additional_information.html["Siguiente: NetApp AI Pod con sistemas NVIDIA DGX: Información adicional."]
