---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: 'AIPod de NetApp con sistemas NVIDIA DGX: Dónde encontrar información adicional' 
---
= NVA-1173 NetApp AIPod con sistemas DGX de NVIDIA: Conclusión e información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se incluyen referencias para obtener información adicional sobre el AIPod de NetApp con sistemas NVIDIA DGX.



== Conclusión

La arquitectura de DGX BasePOD es una plataforma de aprendizaje profundo de próxima generación que requiere funcionalidades de gestión de datos y almacenamiento igualmente avanzadas. Combinando DGX BasePOD con los sistemas de NetApp AFF, la arquitectura NetApp AIPod con los sistemas DGX se puede implementar prácticamente a cualquier escala. Gracias a la superior integración con el cloud y las capacidades definidas por software de NetApp ONTAP, AFF ofrece una completa gama de canalizaciones de datos que abarcan el perímetro, el núcleo y el cloud y que le permitirán llevar a buen puerto sus proyectos de DL.



== Información adicional

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Software de gestión de datos ONTAP de NetApp: Biblioteca de información de ONTAP
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* Sistemas DE ALMACENAMIENTO A900 DE NetApp AFF-
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* Información de RDMA de NetApp ONTAP-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* Kit de herramientas de operaciones de datos de NetApp
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* Astra Trident de NetApp
+
link:../containers/rh-os-n_overview_trident.html["Descripción general"]

* Blog sobre almacenamiento GPUDirect de NetApp-
+
https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/["https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/"]

* DGX BasePOD de NVIDIA
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* SISTEMAS DGX H100 DE NVIDIA
+
https://www.nvidia.com/en-us/data-center/dgx-h100/["https://www.nvidia.com/en-us/data-center/dgx-h100/"^]

* Conexión a redes NVIDIA
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA Magnum IO&#8482; GPUDirect&#174; almacenamiento
+
https://docs.nvidia.com/gpudirect-storage["https://docs.nvidia.com/gpudirect-storage"]

* Comando base NVIDIA
+
https://www.nvidia.com/en-us/data-center/base-command/["https://www.nvidia.com/en-us/data-center/base-command/"]

* Administrador de comandos base de NVIDIA
+
https://www.nvidia.com/en-us/data-center/base-command/manager["https://www.nvidia.com/en-us/data-center/base-command/manager"]

* IA Enterprise de NVIDIA
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Reconocimientos

Este documento es el trabajo de los equipos de Ingeniería ONTAP y Soluciones NetApp - David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar y Raghuram Sudhaakar. Los autores también quieren agradecer a NVIDIA y al equipo de ingeniería de NVIDIA DGX BasePOD su apoyo continuo.
