---
sidebar: sidebar 
permalink: ai/aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html 
keywords: toolkit, dataops, kubernetes, abstraction, python, jupyterlab 
summary: El kit de herramientas DataOPS de NetApp para Kubernetes abstrae los recursos de almacenamiento y las cargas de trabajo de Kubernetes hasta el nivel de espacio de trabajo de ciencia de datos. Estas funciones se presentan en una interfaz sencilla y fácil de usar diseñada para científicos e ingenieros de datos. 
---
= Creación de versiones de conjuntos de datos y modelos con el kit de herramientas de operaciones de datos de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_monitor_dask_and_rapids_with_prometheus_and_grafana.html["Anterior: Monitor de Dink y RAPIDS con Prometheus y Grafana."]

[role="lead"]
El kit de herramientas DataOPS de NetApp para Kubernetes abstrae los recursos de almacenamiento y las cargas de trabajo de Kubernetes hasta el nivel de espacio de trabajo de ciencia de datos. Estas funciones se presentan en una interfaz sencilla y fácil de usar diseñada para científicos e ingenieros de datos. Utilizando la forma familiar de un programa de Python, el kit de herramientas permite a científicos e ingenieros de datos aprovisionar y destruir espacios de trabajo de JuppyterLab en cuestión de segundos. Estas áreas de trabajo pueden contener terabytes o incluso petabytes de capacidad de almacenamiento, lo que permite a los científicos de datos almacenar todos sus conjuntos de datos de entrenamiento directamente en sus espacios de trabajo de proyectos. Han pasado los días de gestionar los espacios de trabajo y los volúmenes de datos por separado.

Para obtener más información, visite el Kit de herramientas https://github.com/NetApp/netapp-data-science-toolkit["Repositorio de GitHub"^].

link:aks-anf_conclusion.html["Siguiente: Conclusión."]
