---
sidebar: sidebar 
permalink: ai/aks-anf_conclusion.html 
keywords: 'Azure NetApp Files, RAPIDS AI, click-though rate (CTR) prediction, Machine Learning, Retail, E-commerce, Azure, Jupyter Notebook, Cloud computing, Digital marketing, Kubernetes' 
summary: Azure NetApp Files, RAPIDS y Dink aceleran y simplifican la puesta en marcha del procesamiento Y formación ML a gran escala, integrado con herramientas de orquestación como Docker y Kubernetes. Al unificar la canalización de datos completa, esta solución reduce la latencia y la complejidad inherentes de muchas cargas de trabajo informáticas avanzadas, y permite salvar en la práctica la brecha entre el desarrollo y las operaciones. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html["Anterior: Versiones de conjuntos de datos y modelos con el kit de herramientas de operaciones de datos de NetApp."]

[role="lead"]
Azure NetApp Files, RAPIDS y Dink aceleran y simplifican la puesta en marcha del procesamiento y formación DE ML a gran escala gracias a la integración con herramientas de orquestación como Docker y Kubernetes. Al unificar la canalización de datos completa, esta solución reduce la latencia y la complejidad inherentes de muchas cargas de trabajo informáticas avanzadas, y permite salvar en la práctica la brecha entre el desarrollo y las operaciones. Los científicos de datos pueden ejecutar consultas en grandes conjuntos de datos y compartir de forma segura datos y modelos algorítmicos con otros usuarios durante la fase de entrenamiento.

Cuando cree sus propias canalizaciones de IA/ML, configurar la integración, la gestión, la seguridad y la accesibilidad de los componentes en una arquitectura es una tarea ardua. Dar a los desarrolladores acceso y control de su entorno presenta otro conjunto de retos.

Al crear un modelo de entrenamiento distribuido completo y una canalización de datos en el cloud, demostramos dos órdenes de mejora de magnitud en el tiempo de finalización total de los flujos de trabajo en comparación con un enfoque convencional de código abierto que no utilizaba el procesamiento de datos acelerado por GPU y los marcos informáticos.

La combinación de NetApp, Microsoft, marcos de orquestación de código abierto y NVIDIA reúne las tecnologías más recientes como servicios gestionados con una gran flexibilidad para acelerar la adopción de tecnología y mejorar el plazo de comercialización de las nuevas aplicaciones de IA/ML. Estos servicios avanzados se ofrecen en un entorno nativo del cloud que se puede realizar fácilmente en las instalaciones y en arquitecturas de puesta en marcha híbrida.

link:aks-anf_where_to_find_additional_information.html["Siguiente: Dónde encontrar información adicional."]
