---
sidebar: sidebar 
permalink: ai/cainvidia_executive_summary.html 
keywords: WP-7328, wp7328, 7328, Executive Summary, NVIDIA, Jarvis, 
summary:  
---
= Artículo técnico WP-7328: La IA conversacional de NetApp con NVIDIA Jarvis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sung-han Lin, NetApp Davide Onofrío, NVIDIA

La familia de sistemas NVIDIA DGX está compuesta por los primeros sistemas basados en inteligencia artificial (IA) integrados del mundo, creados expresamente para la IA empresarial. Los sistemas de almacenamiento AFF de NetApp proporcionan un rendimiento extremo y funcionalidades de gestión de datos de cloud híbrido líderes en el sector. NetApp y NVIDIA se han asociado para crear la arquitectura de referencia de IA ONTAP de NetApp, una solución lista para usar para cargas de trabajo de IA y aprendizaje automático (ML) que ofrece rendimiento, fiabilidad y soporte de clase empresarial.

Este whitepaper proporciona instrucciones direccionales a los clientes para crear sistemas de IA conversacionales que respaldan diferentes casos de uso en diversos sectores verticales. Incluye información sobre la implementación del sistema mediante NVIDIA Jarvis. Las pruebas se llevaron a cabo con una estación DGX de NVIDIA y un sistema de almacenamiento AFF A220 de NetApp.

El público objetivo de la solución incluye los siguientes grupos:

* Arquitectos empresariales que diseñan soluciones para el desarrollo de modelos de IA y software para casos de uso de IA conversacionales como un asistente de ventas al por menor virtual
* Científicos de datos que buscan formas eficientes de lograr los objetivos de desarrollo del modelado del lenguaje
* Ingenieros de datos encargados de mantener y procesar datos de texto, como preguntas de clientes y transcripciones de diálogo
* Responsables de la toma de decisiones tecnológicas y ejecutivas y líderes de negocio interesados en transformar la experiencia de IA conversacional y lograr el plazo de comercialización más rápido de iniciativas de IA


link:cainvidia_solution_overview.html["Siguiente: Descripción general de la solución"]
