---
sidebar: sidebar 
permalink: ai/cainvidia_conclusion.html 
keywords: Conclusion 
summary:  
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un auténtico sistema de IA conversacional se involucra en un diálogo similar al humano, comprende el contexto y proporciona respuestas inteligentes. Estos modelos de IA a menudo son enormes y muy complejos. Con las GPU de NVIDIA y el almacenamiento de NetApp, se pueden formar y optimizar modelos masivos de lenguaje de última generación para ejecutar inferencia rápidamente. Se trata de una importante medida para poner fin a la compensación entre un modelo de IA que es rápido frente a uno que es grande y complejo. Los modelos de comprensión del lenguaje optimizados para GPU se pueden integrar en las aplicaciones de IA en sectores como el sanitario, el minorista y los servicios financieros. Esto hace posible que asistentes de voz digitales avanzados en altavoces inteligentes y líneas de servicio al cliente. Estos sistemas de IA conversacionales de alta calidad permiten a las empresas de sectores verticales proporcionar servicios personalizados que antes eran impensables al tratar con los clientes.

Jarvis permite el despliegue de casos de uso como asistentes virtuales, avatares digitales, sensor multimodal Fusion (CV con fusible ASR/NLP/TTS) o cualquier caso de uso independiente ASR/NLP/TTS/CV, como la transcripción. Hemos creado un asistente de venta al por menor virtual que puede responder a preguntas relacionadas con el tiempo, los puntos de interés y los precios del inventario. También demostramos cómo mejorar las funcionalidades de comprensión del lenguaje natural del sistema de IA conversacional archivando el historial de conversaciones con BlueXP Copy y Sync y entrenando modelos de Nemo en datos nuevos.
