---
sidebar: sidebar 
permalink: ai/dataops-toolkit.html 
keywords:  
summary:  
---
= Kit de herramientas de operaciones de datos de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
El kit de herramientas DataOps de NetApp es una herramienta basada en Python que simplifica la gestión de espacios de trabajo de desarrollo/formación y servidores de inferencia respaldados por un almacenamiento de NetApp de escalado horizontal y de alto rendimiento. Estas son algunas funcionalidades clave:

* Aprovisione con rapidez nuevos espacios de trabajo de JuppyterLab de alta capacidad respaldados por el almacenamiento de NetApp de escalado horizontal y de alto rendimiento.
* Aprovisione rápidamente nuevas instancias del servidor de inferencia de NVIDIA Triton, respaldadas por un almacenamiento empresarial de NetApp.
* Clone casi instantáneamente espacios de trabajo JupyterLab de gran capacidad para permitir la experimentación o la iteración rápida.
* Guarde copias Snapshot de espacios de trabajo de JupyterLab de gran capacidad casi al instante para realizar tareas de backup o trazabilidad/creación de bases de referencia.
* Aprovisionamiento, clonado y copias Snapshot casi de forma instantánea volúmenes de datos de alta capacidad y alto rendimiento.


link:https://github.com/NetApp/netapp-dataops-toolkit["Kit de herramientas de operaciones de datos de NetApp"^]
