---
sidebar: sidebar 
permalink: ai/hcaios_ontap_ai_deployment.html 
keywords: ONTAP AI, Deployment, networking, compute, storage 
summary:  
---
= Puesta en marcha de IA de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La puesta en marcha de ONTAP AI requiere la instalación y configuración de hardware de almacenamiento, computación y redes. Este documento no cubre las instrucciones específicas para la puesta en marcha de la infraestructura de IA de ONTAP. Para obtener información detallada sobre la implementación, consulte https://www.netapp.com/us/media/nva-1121-deploy.pdf["NVA-1121-PUESTA en MARCHA: ONTAP AI de NetApp, con tecnología NVIDIA"^].

Para esta validación de soluciones, se creó y montó un solo volumen en el sistema DGX-1. A continuación, ese punto de montaje se montó en los contenedores para que los datos sean accesibles para el entrenamiento. Para puestas en marcha a gran escala, Trident de NetApp automatiza la creación y el montaje de volúmenes para eliminar la sobrecarga administrativa y permitir la gestión de recursos por parte del usuario final.

link:hcaios_kubernetes_deployment.html["Siguiente: Puesta en marcha de Kubernetes"]
