---
sidebar: sidebar 
permalink: ai/hcaios_abstract.html 
keywords: NetApp Abstract ML AI 
summary:  
---
= Sinopsis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El crecimiento exponencial de los datos y el crecimiento exponencial del aprendizaje automático y la inteligencia artificial (IA) han convergido para crear una nueva economía con retos de desarrollo e implementación únicos. Normalmente, se almacenan cantidades masivas de datos en un lago de datos de bajo coste, en el que los recursos informáticos de IA de alto rendimiento, como las GPU, no pueden acceder a ellos de forma eficiente. En este informe presentamos una nueva solución en la que los profesionales de la ciencia de datos implementan un concentrador de datos y, con un solo clic, crean una caché de conjuntos de datos cerca de sus recursos informáticos, independientemente de dónde estén ubicados. Como resultado, los profesionales de la IA pueden realizar la formación de modelos de alto rendimiento con mayor facilidad gracias a la colaboración mejorada que permite un nuevo concentrador de versiones de conjuntos de datos.
