---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Si quiere obtener más información sobre el contenido de este documento, consulte los siguientes recursos:

* Nvrg.io ( https://cnvrg.io["https://cnvrg.io"^]):
+
** NÚCLEO Cnvrg (plataforma DE ML libre)
+
https://cnvrg.io/platform/core[]

** Documentos de Cnvrg
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* Servidores DGX-1 de NVIDIA:
+
** Servidores DGX-1 de NVIDIA
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** GPU de núcleo tensor NVIDIA Tesla V100
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** GPU CLOUD DE NVIDIA (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/[]



* Sistemas AFF de NetApp:
+
** Especificaciones técnicas de AFF
+
https://www.netapp.com/us/media/d-3582.pdf[]

** FlashAdvantage de NetApp para AFF
+
https://www.netapp.com/us/media/ds-3733.pdf[]

** Documentación de ONTAP 9.x.
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** Informe técnico de NetApp FlexGroup
+
https://www.netapp.com/us/media/tr-4557.pdf[]



* Almacenamiento persistente de NetApp para contenedores:
+
** Trident de NetApp
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* Matriz de interoperabilidad de NetApp:
+
** Herramienta de matriz de interoperabilidad de NetApp
+
http://support.netapp.com/matrix[]



* Redes de IA de ONTAP:
+
** Switches Cisco Nexus 3232C
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Switches Mellanox Spectrum serie 2000
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* Marco Y herramientas DE ML:
+
** DALÍ
+
https://github.com/NVIDIA/DALI[]

** TensorFlow: Un marco de aprendizaje automático de código abierto para todos
+
https://www.tensorflow.org/[]

** Horovod: El marco de Uber para el aprendizaje automático distribuido de código abierto para TensorFlow
+
https://eng.uber.com/horovod/[]

** Habilitación de GPU en el ecosistema Container Runtime
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker
+
https://docs.docker.com[]

** Kubernetes
+
https://kubernetes.io/docs/home/[]

** DeepOps de NVIDIA
+
https://github.com/NVIDIA/deepops[]

** Kubeflow
+
http://www.kubeflow.org/[]

** Servidor de portátiles Juppyter
+
http://www.jupyter.org/[]



* Conjuntos de datos y pruebas:
+
** Conjunto de datos de radiografía de tórax de los NIH
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaosong Wang, Yifan Peng, le Lu, Zhiyong Lu, Mohammadadi Bagheri, Ronald Summers, ChestX-ray8: Base de datos de rayos X en el pecho a escala de hospital y puntos de referencia sobre clasificación y localización de enfermedades comunes del tórax, IEEE CVPR, págs 3462-3471, 2017TR-4841-0620



