---
sidebar: sidebar 
permalink: ai/hcaios_kubernetes_deployment.html 
keywords: Kubernetes, Deployment, NVIDIA, DeepOps 
summary:  
---
= Puesta en marcha de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Para poner en marcha y configurar su clúster de Kubernetes con NVIDIA DeepOPS, realice las siguientes tareas desde un host de salto de implementación:

. Descargue NVIDIA DeepOps siguiendo las instrucciones de https://["Página de Inicio"^] En el sitio de NVIDIA DeepOps GitHub.
. Implemente Kubernetes en su clúster siguiendo las instrucciones que se indican en https://["Guía de puesta en marcha de Kubernetes"^] En el sitio de NVIDIA DeepOps GitHub.



NOTE: Para que la puesta en marcha de DeepOps Kubernetes funcione, debe haber el mismo usuario en todos los nodos maestro y de trabajador de Kubernetes.

Si la implementación falla, cambie el valor de `kubectl_localhost` a falso in `deepops/config/group_vars/k8s-cluster.yml` y repita el paso 2. La `Copy kubectl binary to ansible host` tarea, que sólo se ejecuta cuando el valor de `kubectl_localhost` Es cierto que se basa en el módulo Fetch Ansible, que tiene problemas conocidos con el uso de memoria. Estos problemas de uso de la memoria a veces pueden provocar un error en la tarea. Si la tarea falla debido a un problema de memoria, el resto de la operación de implementación no se completa correctamente.

Si la implementación se completa correctamente después de cambiar el valor de `kubectl_localhost` para `false`, a continuación, debe copiar manualmente la `kubectl binary` Desde un nodo maestro de Kubernetes a un host de salto de implementación. Puede encontrar la ubicación del `kubectl binary` en un nodo maestro específico ejecutando el `which kubectl` comando directamente en ese nodo.

link:hcaios_cnvrg.io_deployment.html["Siguiente: Puesta en marcha de Cnvrg.io"]
