---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= Casos de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Aunque todas las aplicaciones actuales no están impulsadas por la IA, están evolucionando capacidades que les permiten acceder a los inmensos beneficios de la IA. Para respaldar la adopción de la IA, las aplicaciones necesitan una infraestructura que les proporcione los recursos necesarios para funcionar a un nivel óptimo y para respaldar su continua evolución.

Para las aplicaciones condicionadas por la IA, las ubicaciones perimetrales funcionan como una fuente de datos importante. Los datos disponibles se pueden usar para el entrenamiento cuando se recogen de varias ubicaciones perimetrales a lo largo de un periodo de tiempo para formar un conjunto de datos de entrenamiento. A continuación, el modelo entrenado se puede volver a poner en marcha en las ubicaciones perimetrales en las que se recogieron los datos, lo que permite una inferencia más rápida sin la necesidad de transferir repetidamente datos de producción a una plataforma de inferencia dedicada.

La solución de inferencia de IA de NetApp HCI, impulsada por los nodos de computación H615c de NetApp con GPU NVIDIA T4 y los sistemas de almacenamiento conectados al cloud de NetApp, ha sido desarrollada y verificada por NetApp y NVIDIA. NetApp HCI simplifica la puesta en marcha de soluciones de inferencia de IA en centros de datos periféricos abordando las áreas de ambigüedad, eliminando complejidades en el diseño y acabar con las conjeturas. Esta solución proporciona a las organizaciones DE TI una arquitectura prescriptiva que:

* Permite la inferencia de IA en centros de datos periféricos
* Optimiza el consumo de recursos de GPU
* Proporciona una plataforma de inferencia basada en Kubernetes para conseguir flexibilidad y escalabilidad
* Elimina las complejidades de diseño


Los centros de datos del perímetro gestionan y procesan los datos en ubicaciones que están muy cerca del punto de generación. Esta proximidad aumenta la eficiencia y reduce la latencia involucrada en la gestión de datos. Muchos mercados verticales se han dado cuenta de las ventajas de un centro de datos perimetral y están adoptando en gran medida este enfoque distribuido del procesamiento de datos.

En la siguiente tabla se enumeran las aplicaciones y verticales de bordes.

|===
| Vertical | Más grandes 


| Médica | El diagnóstico asistido por ordenador ayuda al personal médico en la detección temprana de enfermedades 


| Petróleo y gas | Inspección autónoma de instalaciones de producción remotas, vídeo y análisis de imágenes 


| Aviación | Asistencia para el control del tráfico aéreo y análisis de alimentación de vídeo en tiempo real 


| Medios y entretenimiento | Filtrado de contenidos de audio y vídeo para ofrecer contenido familiar 


| Análisis empresarial | Reconocimiento de Marca para analizar la apariencia de la Marca en eventos televisados en directo 


| Comercio electrónico | La agrupación inteligente de ofertas de proveedores para encontrar combinaciones ideales de comercios y almacenes 


| Comercio minorista | Pago automático para reconocer los artículos que un cliente ha colocado en el carrito y facilitar el pago digital 


| Ciudad inteligente | Mejore el flujo de tráfico, optimice el estacionamiento y mejore la seguridad de peatones y ciclistas 


| Fabricación | Control de calidad, control de línea de montaje e identificación de defectos 


| Atención al cliente | Automatización del servicio al cliente para analizar y clasificar consultas (teléfono, correo electrónico y redes sociales) 


| Agricultura | Funcionamiento de granja inteligente y planificación de actividades, para optimizar la aplicación de fertilizantes y herbicidas 
|===


== Público objetivo

El público objetivo de la solución incluye los siguientes grupos:

* Científicos de datos
* Arquitectos de TECNOLOGÍA
* Consultores de campo
* Servicios profesionales
* Responsables de TECNOLOGÍA
* Cualquiera que necesite una infraestructura que ofrezca innovación TECNOLÓGICA y servicios de aplicaciones y datos sólidos en las ubicaciones perimetrales

