---
sidebar: sidebar 
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html 
keywords:  
summary:  
---
= Puesta en marcha de una infraestructura virtual de VMware en NetApp HCI con NDE (puesta en marcha automatizada)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Requisitos previos de puesta en marcha de NDE

Consulte la https://library.netapp.com/ecm/ecm_download_file/ECMLP2798490["Lista de verificación de requisitos previos de NetApp HCI"^] Para consultar los requisitos y las recomendaciones para NetApp HCI antes de la implementación.

. Requisitos y configuración de switch y red
. Preparar los identificadores de VLAN necesarios
. Configuración de switches
. Requisitos de dirección IP para NetApp HCI y VMware
. Requisitos de DNS y de mantenimiento del tiempo
. Preparaciones finales




== Ejecución de NDE

Antes de ejecutar el NDE, debe completar el rack y la pila de todos los componentes, la configuración de los switches de red y la verificación de todos los requisitos previos. Puede ejecutar NDE conectando a la dirección de gestión de un solo nodo de almacenamiento si tiene pensado permitir que NDE configure automáticamente todas las direcciones.

Nde realiza las siguientes tareas para poner un sistema HCI en línea:

. Instala el nodo de almacenamiento (software NetApp Element) en un mínimo de dos nodos de almacenamiento.
. Instala el hipervisor de VMware en dos nodos de computación como mínimo.
. Instala VMware vCenter para gestionar toda la pila de NetApp HCI.
. Instala y configura el nodo de gestión de almacenamiento de NetApp (mNode) y el agente de supervisión de NetApp.
+

NOTE: Esta validación utiliza NDE para configurar automáticamente todas las direcciones. También puede configurar DHCP en el entorno o asignar manualmente direcciones IP para cada nodo de almacenamiento y nodo de computación. Estos pasos no se describen en esta guía.

+
Como se mencionó anteriormente, esta validación utiliza una configuración de dos cables para los nodos de computación.

+
Los pasos detallados para el NDE no se tratan en este documento.

+
Si desea obtener una guía paso a paso para completar la puesta en marcha de la plataforma NetApp HCI básica, consulte http://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html?cp=3_0["Guía de puesta en marcha"^].

. Una vez que NDE haya terminado, inicie sesión en vCenter y cree un grupo de puertos distribuido `NetApp HCI VDS 01-NFS_Network` Para que ONTAP Select y la aplicación utilicen la red NFS.

