---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSxN, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: Esta es la página introductoria de la sección MLOps de FSxN. 
---
= AWS FSx para NetApp ONTAP (FSxN) para MLOps (en inglés)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:highlighter: rouge
:imagesdir: ./../media/


[role="lead"]
En esta sección se profundiza en la aplicación práctica del desarrollo de la infraestructura de IA, ofreciendo un tutorial integral de la construcción de una canalización de MLOps con FSxN. Compuesto por tres ejemplos completos, te guía para satisfacer tus necesidades de MLOps a través de esta potente plataforma de gestión de datos.

*Autor(es):*
Jian Jian (KEN), científico sénior de datos y aplicado, NetApp

Estos artículos se centran en:

. link:./mlops_fsxn_s3_integration.html["1 parte: Integración de AWS FSx para NetApp ONTAP (FSxN) como bloque de S3 privado en AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Parte 2: Aprovechamiento de AWS FSx para NetApp ONTAP (FSxN) como fuente de datos para el entrenamiento de modelos en SageMaker"]
. link:./mlops_fsxn_cictcd.html["Parte 3: Creación de Una canalización simplificada de MLOps (CI/CT/CD)"]


Al final de esta sección, habrá obtenido una sólida comprensión de cómo usar FSxN para agilizar los procesos de MLOps.
