---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSx ONTAP, FSx ONTAP, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: Esta es la página de introducción a la sección de MLOps de FSx ONTAP. 
---
= Amazon FSx for NetApp ONTAP (FSx ONTAP) para MLOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se profundiza en la aplicación práctica del desarrollo de la infraestructura de IA, ofreciendo un tutorial integral sobre la construcción de una canalización de MLOps con FSx ONTAP. Compuesto por tres ejemplos completos, te guía para satisfacer tus necesidades de MLOps a través de esta potente plataforma de gestión de datos.

Estos artículos se centran en:

. link:./mlops_fsxn_s3_integration.html["1 parte: Integración de Amazon FSx para NetApp ONTAP (FSx ONTAP) como bloque de S3 privado en AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Parte 2: Aprovechamiento de Amazon FSx para NetApp ONTAP (FSx ONTAP) como fuente de datos para el entrenamiento de modelos en SageMaker"]
. link:./mlops_fsxn_cictcd.html["Parte 3: Creación de Una canalización simplificada de MLOps (CI/CT/CD)"]


Al final de esta sección, habrás obtenido una sólida comprensión de cómo usar FSx ONTAP para optimizar los procesos de MLOps.
