---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Si quiere obtener más información sobre el contenido de este documento, consulte los siguientes recursos:

* Plano de control de IA de NetApp:
+
** Informe técnico sobre el plano de control de IA de NetApp
+
https://["https://www.netapp.com/us/media/tr-4798.pdf"^]



* Almacenamiento persistente de NetApp para contenedores:
+
** Trident de NetApp
+
https://["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* Marco Y herramientas DE ML:
+
** TensorFlow: Un marco de aprendizaje automático de código abierto para todos https://["https://www.tensorflow.org/"^]
** Docker
+
https://["https://docs.docker.com"^]

** Kubernetes
+
https://["https://kubernetes.io/docs/home/"^]

** Kubeflow
+
http://["http://www.kubeflow.org/"^]

** Servidor de portátiles Juppyter
+
http://["http://www.jupyter.org/"^]



* Plataforma de Ciencia de datos de Iguazio
+
** Documentación de la Plataforma de Ciencias de datos de Iguazio
+
https://["https://www.iguazio.com/docs/"^]

** Nuclio función sin servidor
+
https://["https://nuclio.io/"^]

** Marco de orquestación de canalización de código abierto MLRun
+
https://["https://www.iguazio.com/open-source/mlrun/"^]



* Sistemas DGX-1 de NVIDIA
+
** Sistemas DGX-1 de NVIDIA
+
https://["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** GPU de núcleo tensor NVIDIA Tesla V100
+
https://["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** GPU Cloud de NVIDIA
+
https://["https://www.nvidia.com/en-us/gpu-cloud/"^]



* Sistemas AFF de NetApp
+
** Especificaciones técnicas de AFF
+
https://["https://www.netapp.com/us/media/ds-3582.pdf"^]

** Ventaja de NetApp Flash para AFF
+
https://["https://www.netapp.com/us/media/ds-3733.pdf"^]

** Documentación de ONTAP 9.x.
+
https://["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** Informe técnico de NetApp FlexGroup
+
https://["https://www.netapp.com/us/media/tr-4557.pdf"^]



* ONTAP AI de NetApp
+
** Guía de diseño de ONTAP AI con DGX-1 y Cisco Networking
+
https://["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** Guía de puesta en marcha de ONTAP AI con DGX-1 y Cisco Networking
+
https://["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** Guía de diseño de ONTAP AI con DGX-1 y Mellanox Networking
+
https://["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* Redes de IA de ONTAP
+
** Switches de la serie Cisco Nexus 3232C
+
https://["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Serie de switches Ethernet de escalabilidad horizontal Mellanox SN2000
+
https://["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




