---
sidebar: sidebar 
permalink: ai/nva-1153-design-link.html 
keywords:  
summary:  
---
= DISEÑO de Mellanox-1153: ONTAP AI de NetApp con sistemas NVIDIA DGX A100 y switches NVA Spectrum Ethernet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette y Sung-han Lin, NetApp

EL DISEÑO NVA-1153 describe una arquitectura verificada de NetApp para cargas de trabajo de aprendizaje automático (ML) y de inteligencia artificial (IA) con los sistemas de almacenamiento AFF A800 de NetApp, los sistemas NVIDIA DGX A100 y los switches Ethernet de 200 GB de NVIDIA Mellanox Spectrum SN3700V. Este diseño presenta RDMA over Converged Ethernet (roce) para la estructura de interconexión de clústeres informáticos, que ofrece a los clientes una arquitectura completamente basada en ethernet para cargas de trabajo de alto rendimiento. Este documento también incluye los resultados de las pruebas de rendimiento para la arquitectura tal y como se ha implementado.

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf["DISEÑO de Mellanox-1153: ONTAP AI de NetApp con sistemas NVIDIA DGX A100 y switches NVA Spectrum Ethernet"^]
