---
sidebar: sidebar 
permalink: ai/nva-1156-design-link.html 
keywords:  
summary:  
---
= DISEÑO NVA-1156: EF-Series AI de NetApp con sistemas NVIDIA DGX A100 y BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Abdel Sadek, Tim Chau, Joe McCormick y David Arnette, NetApp

[role="lead"]
El DISEÑO de NVA-1156 describe una arquitectura verificada de NetApp para cargas de trabajo de aprendizaje automático (ML) y de inteligencia artificial (IA) mediante los sistemas de almacenamiento EF600 de NetApp, el sistema de archivos en paralelo BeeGFS, los sistemas NVIDIA DGX A100 y los switches IB de NVIDIA Quantum QM8700 de 200 Gbps. Este diseño incluye InfiniBand (IB) de 200 Gbps para la estructura de interconexión de clústeres de almacenamiento e informáticos con el fin de proporcionar a los clientes una arquitectura completamente basada en IB para las cargas de trabajo de alto rendimiento. Este documento también incluye los resultados de las pruebas de rendimiento para la arquitectura tal y como se ha implementado.

link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["DISEÑO NVA-1156: EF-Series AI de NetApp con sistemas NVIDIA DGX A100 y BeeGFS"^]
