---
sidebar: sidebar 
permalink: ai/nva-1153-deploy-link.html 
keywords:  
summary:  
---
= Puesta EN MARCHA de Mellanox-1153: ONTAP AI de NetApp con sistemas NVIDIA DGX A100 y switches NVA Spectrum Ethernet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette, NetApp

La puesta EN MARCHA de NVA-1153 incluye instrucciones para la puesta en marcha del sistema de almacenamiento para cargas de trabajo de NetApp Verified Architecture para el aprendizaje automático (ML) y de inteligencia artificial (IA) mediante los sistemas de almacenamiento AFF A800 de NetApp, los sistemas NVIDIA DGX A100 y los switches Ethernet de 200 GB de NVIDIA Mellanox Spectrum SN3700V. También incluye instrucciones para ejecutar pruebas de prueba de rendimiento de validación una vez completada la implementación.

link:https://www.netapp.com/pdf.html?item=/media/21789-nva-1153-deploy.pdf["Puesta EN MARCHA de Mellanox-1153: ONTAP AI de NetApp con sistemas NVIDIA DGX A100 y switches NVA Spectrum Ethernet"^]
