---
sidebar: sidebar 
permalink: ai/nva-1150-deploy.html 
keywords:  
summary:  
---
= NVA-1150-PUESTA en MARCHA: Quantum StorNext con la guía de puesta en marcha de sistemas E-Series de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Ryan Rodine, NetApp

[role="lead"]
Este documento proporciona detalles sobre cómo poner en marcha una solución de sistema de archivos paralelo StorNext con sistemas de almacenamiento E-Series de NetApp. Esta solución abarca la cabina all-flash EF280 de NetApp, la cabina NVMe all-flash EF300 de NetApp, la cabina NVMe all-flash EF600 de NetApp y el sistema híbrido E5760 de NetApp. Ofrece una caracterización del rendimiento basada en las pruebas comparativas de Frametest, una herramienta que se utiliza ampliamente para realizar pruebas en el sector del entretenimiento y los medios de comunicación.

link:https://www.netapp.com/pdf.html?item=/media/19429-nva-1150-deploy.pdf["NVA-1150-PUESTA en MARCHA: Quantum StorNext con la guía de puesta en marcha de sistemas E-Series de NetApp"^]
