---
sidebar: sidebar 
permalink: ai/nvaie_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: 'NVIDIA AI Enterprise con NetApp y VMware: Configuración inicial' 
---
= Configuración inicial
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se describen las tareas de configuración inicial que se deben realizar para utilizar NVIDIA AI Enterprise con NetApp y VMware.



== Requisitos previos

Antes de realizar los pasos descritos en esta sección, asumimos que ya ha implementado VMware vSphere y ONTAP de NetApp. Consulte la link:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matriz de compatibilidad de productos empresariales de NVIDIA AI"] para obtener más detalles sobre las versiones de vSphere compatibles. Consulte la link:../vmware/index.html["Documentación sobre las soluciones de NetApp y VMware"] para obtener más información sobre la implementación de VMware vSphere con NetApp ONTAP.



== Instale el software de host de NVIDIA AI Enterprise

Para instalar el software host NVIDIA AI Entrprise, siga las instrucciones que se describen en las secciones 1-4 de la link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["Guía de inicio rápido de NVIDIA AI Enterprise"].
