---
sidebar: sidebar 
permalink: ai/osrunai_netapp_ontap_ai_and_ai_control_plane.html 
keywords:  
summary:  
---
= Plano de control de la IA y la IA con ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La arquitectura de IA de ONTAP de NetApp, impulsada por los sistemas NVIDIA DGX y los sistemas de almacenamiento conectados al cloud de NetApp. Esta arquitectura de referencia proporciona a las organizaciones DE TI las siguientes ventajas:

* Elimina las complejidades de diseño
* Permite un escalado independiente de las capacidades de computación y almacenamiento
* Permite a los clientes empezar con poco y escalar sin problemas
* Ofrece una gama de opciones de almacenamiento para diferentes prestaciones de rendimiento y coste nuestro ONTAP AI integra a la perfección los sistemas de almacenamiento DGX y AFF A800 de NetApp con las redes de vanguardia. Los sistemas ONTAP AI y DGX de NetApp simplifican las puestas en marcha de IA al eliminar complejidades y conjeturas en la fase de diseño. Los clientes pueden empezar poco a poco y aumentar sus sistemas de forma ininterrumpida, a la vez que gestionan de forma inteligente datos entre el perímetro, el núcleo y el cloud.


El plano de control de IA de NetApp es una solución de gestión de experimentos y datos de IA, ML y aprendizaje profundo (DL) para científicos de datos e ingenieros de datos. A medida que las organizaciones aumentan el uso de la IA, deben hacer frente a numerosos retos, como la escalabilidad de la carga de trabajo y la disponibilidad de los datos. El plano de control de IA de NetApp aborda estos retos mediante funcionalidades como clonar rápidamente un espacio de nombres de datos del mismo modo que utilizaría un Git repo y definir e implementar flujos de trabajo de entrenamiento de IA que incorporen la creación casi instantánea de datos y líneas de base de modelos para la trazabilidad y el control de versiones. Con el plano de control de IA de NetApp, puede replicar datos sin problemas entre sitios y regiones y aprovisionar rápidamente espacios de trabajo de los portátiles Juppyter con acceso a conjuntos de datos masivos.
