---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_49.html 
keywords:  
summary:  
---
= Detalles de las pruebas para la sección 4.9
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta sección contiene detalles de la prueba para la sección link:osrunai_basic_resource_allocation_fairness.html["Equidad en la asignación de recursos básicos"].

Enviar trabajos en el siguiente orden:

|===
| Proyecto | N.o de GPU | Total | Comentar 


| equipo d | 2 | 6/8 | La carga de trabajo Team-b/c se pone en pausa y se mueve a. `pending`. 


| equipo d | 2 | 8/8 | Las cargas de trabajo de otros equipos (b/c) se pausan y pasan a. `pending`. 
|===
Consulte la siguiente secuencia de comandos ejecutada:

....
$ runai submit d-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d$ runai submit d-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d
....
En este punto, debe tener los siguientes estados:

|===
| Proyecto | GPU asignadas | Cargas de trabajo en cola 


| equipo a | 4/4 | Ninguno 


| equipo-b | 2/2 | Ninguno 


| equipo-c | 2/2 | Ninguno 


| equipo d | 8/8 | Ninguno 
|===
Consulte la sección link:osrunai_basic_resource_allocation_fairness.html["Equidad en la asignación de recursos básicos"] para un debate sobre el escenario de pruebas en curso.
