---
sidebar: sidebar 
permalink: ai/osrunai_executive_summary.html 
keywords:  
summary:  
---
= TR-4858: Solución de orquestación de NetApp con Run:AI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, David Arnette, Sung-han Lin, NetApp Yaron Goldberg, Run:AI

[role="lead"]
Los sistemas de almacenamiento AFF de NetApp proporcionan un rendimiento extremo y funcionalidades de gestión de datos de cloud híbrido líderes en el sector. NetApp y Run:AI se han asociado para demostrar las funcionalidades únicas de la solución de IA ONTAP de NetApp para cargas de trabajo de inteligencia artificial (IA) y aprendizaje automático (ML) que ofrecen rendimiento, fiabilidad y soporte de clase empresarial. Ejecutar:la orquestación de la IA de las cargas de trabajo de IA añade una programación basada en Kubernetes y una plataforma de uso de recursos para ayudar a los investigadores a gestionar y optimizar la utilización de la GPU. Junto con los sistemas DGX de NVIDIA, la solución combinada de NetApp, NVIDIA y Run:AI proporciona una pila de infraestructura diseñada específicamente para cargas de trabajo de IA empresariales. Este informe técnico proporciona instrucciones direccionales a los clientes que crean sistemas de IA conversacionales que respaldan diversos casos prácticos y mercados verticales del sector. Incluye información sobre la puesta en marcha de Run:AI y un sistema de almacenamiento AFF A800 de NetApp y sirve como arquitectura de referencia para obtener el método más sencillo de poner en marcha con éxito iniciativas de IA de forma rápida.

El público objetivo de la solución incluye los siguientes grupos:

* Los arquitectos empresariales que diseñan soluciones para el desarrollo de modelos de IA y software para casos prácticos basados en Kubernetes, como microservicios en contenedores
* Los científicos de datos que buscan formas eficientes de alcanzar objetivos de desarrollo de modelos eficientes en un entorno de clúster con varios equipos y proyectos
* Ingenieros de datos a cargo del mantenimiento y la ejecución de modelos de producción
* Responsables de la toma de decisiones de TECNOLOGÍA y ejecutivos y líderes empresariales que desean crear la experiencia óptima de utilización de recursos de clúster de Kubernetes y lograr el plazo de comercialización más rápido posible gracias a las iniciativas de IA


link:osrunai_solution_overview.html["Siguiente: Descripción general de la solución"]
