---
sidebar: sidebar 
permalink: ai/osrunai_run_ai_platform_for_ai_workload_orchestration.html 
keywords:  
summary:  
---
= Ejecutar:Plataforma de IA para orquestación de cargas de trabajo de IA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
* Plazo de innovación más rápido. UsingRun:pool de recursos de IA, puesta en cola y mecanismos de priorización junto con el sistema de almacenamiento de NetApp, los investigadores se eliminan de las dificultades de la gestión de la infraestructura y pueden centrarse exclusivamente en la ciencia de datos. Ejecución:los clientes de NetApp y IA aumentan la productividad ejecutando tantas cargas de trabajo como necesiten sin cuellos de botella en la canalización de datos o en la computación.
* Aumento de la productividad del equipo. Ejecutar:los algoritmos de justicia de IA garantizan que todos los usuarios y equipos obtengan su participación en la feria de recursos. Es posible predefinir políticas sobre proyectos de prioridad y la plataforma permite la asignación dinámica de recursos de un equipo de usuario a otro, lo que ayuda a los usuarios a obtener un acceso puntual a los recursos de GPU codiciados.
* Uso de GPU mejorado. El planificador Run:AI permite a los usuarios utilizar fácilmente GPU fraccionarias, GPU enteros y varios nodos de GPU para llevar a cabo entrenamiento distribuido en Kubernetes. De esta forma, las cargas de trabajo de IA se ejecutan en función de las necesidades, no en función de la capacidad. Los equipos de ciencia de datos pueden realizar más experimentos de IA en la misma infraestructura.

