---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_410.html 
keywords:  
summary:  
---
= Detalles de las pruebas para la sección 4.10
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta sección contiene detalles de la prueba para la sección link:osrunai_over-quota_fairness.html["Justicia por exceso de cuotas"].

Enviar trabajos en el siguiente orden para `team-a`, `team-b`, y. `team-c`:

|===
| Proyecto | N.o de GPU | Total | Comentar 


| equipo a | 2 | 4/4 | 1 carga de trabajo en cola 


| equipo a | 2 | 4/4 | 2 cargas de trabajo en cola 


| equipo-b | 2 | 2/2 | 2 cargas de trabajo en cola 


| equipo-c | 2 | 2/2 | 2 cargas de trabajo en cola 
|===
Consulte la siguiente secuencia de comandos ejecutada:

....
$ runai submit a-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit a-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit b-5-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b$ runai submit c-6-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
....
En este punto, debe tener los siguientes estados:

|===
| Proyecto | GPU asignadas | Cargas de trabajo en cola 


| equipo a | 4/4 | Dos cargas de trabajo que solicitan GPU dos cada una 


| equipo-b | 2/2 | Dos cargas de trabajo que solicitan dos GPU cada una 


| equipo-c | 2/2 | Dos cargas de trabajo que solicitan dos GPU cada una 


| equipo d | 8/8 | Ninguno 
|===
A continuación, elimine todas las cargas de trabajo para `team-d`:

....
$ runai delete -p team-d d-1-gggg d-2-gg d-3-gg
....
Consulte la sección link:osrunai_over-quota_fairness.html["Justicia por exceso de cuotas"], para las discusiones sobre el escenario de pruebas en curso.
