---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_48.html 
keywords:  
summary:  
---
= Detalles de las pruebas para la sección 4.8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta sección contiene los detalles de las pruebas de la sección link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["Utilización óptima del clúster gracias a la asignación de GPU por encima de una cuota"].

Enviar trabajos en el siguiente orden:

|===
| Proyecto | Imagen | N.o de GPU | Total | Comentar 


| equipo a | Juppyter | 1 | 1/4 | – 


| equipo a | NetApp | 1 | 2/4 | – 


| equipo a | Ejecución: IA | 2 | 4/4 | Usando toda su cuota 


| equipo-b | Ejecución: IA | 0.6 | 0.6/2 | GPU fraccionaria 


| equipo-b | Ejecución: IA | 0.4 | 1/2 | GPU fraccionaria 


| equipo-b | NetApp | 1 | 2/2 | – 


| equipo-b | NetApp | 2 | 4/2 | Dos sobre cuota 


| equipo-c | Ejecución: IA | 0.5 | 0.5/2 | GPU fraccionaria 


| equipo-c | Ejecución: IA | 0.3 | 0.8/2 | GPU fraccionaria 


| equipo-c | Ejecución: IA | 0.2 | 1/2 | GPU fraccionaria 


| equipo-c | NetApp | 2 | 3/2 | Uno sobre cuotas 


| equipo-c | NetApp | 1 | 4/2 | Dos sobre cuota 


| equipo d | NetApp | 4 | 4/8 | Utilizando la mitad de su cuota 
|===
Estructura de comandos:

....
$ runai submit <job-name> -p <project-name> -g <#GPUs> -i <image-name>
....
Secuencia de comandos real utilizada en la prueba:

....
$ runai submit a-1-1-jupyter -i jupyter/base-notebook -g 1 \
  --interactive --service-type=ingress --port 8888 \
  --args="--NotebookApp.base_url=team-a-test-ingress" --command=start-notebook.sh -p team-a
$ runai submit a-1-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-a
$ runai submit a-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a
$ runai submit b-1-g06 -i gcr.io/run-ai-demo/quickstart -g 0.6 --interactive -p team-b
$ runai submit b-2-g04 -i gcr.io/run-ai-demo/quickstart -g 0.4 --interactive -p team-b
$ runai submit b-3-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-b
$ runai submit b-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b
$ runai submit c-1-g05 -i gcr.io/run-ai-demo/quickstart -g 0.5 --interactive -p team-c
$ runai submit c-2-g03 -i gcr.io/run-ai-demo/quickstart -g 0.3 --interactive -p team-c
$ runai submit c-3-g02 -i gcr.io/run-ai-demo/quickstart -g 0.2 --interactive -p team-c
$ runai submit c-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
$ runai submit c-5-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-c
$ runai submit d-1-gggg -i gcr.io/run-ai-demo/quickstart -g 4 -p team-d
....
En este punto, debe tener los siguientes estados:

|===
| Proyecto | GPU asignadas | Cargas de trabajo en cola 


| equipo a | 4/4 (cuota suave/asignación real) | Ninguno 


| equipo-b | 4/2 | Ninguno 


| equipo-c | 4/2 | Ninguno 


| equipo d | 4/8 | Ninguno 
|===
Consulte la sección link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["Mayor uso de clúster con la asignación de GPU over-uota"] para discusiones sobre el escenario de pruebas en curso.
