---
sidebar: sidebar 
permalink: ai/rag_introduction.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG con NVIDIA Nemo y NetApp - Introducción 
---
= Generación aumentada de recuperación empresarial (RAG) con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mike Oglesby, NetApp
Sathish Thyagarajan, NetApp

[role="lead"]
La IA generativa está transformando la experiencia de búsqueda empresarial. Lo permite a los usuarios de datos de una empresa detectar activos de datos que residen en cualquier lugar, ya sea en las instalaciones o en un cloud público. Tanto si los desarrolladores utilizan la IA generativa para generar código para diseñar una aplicación web moderna, o para crear animaciones utilizando física y datos de movimiento del mundo real, las organizaciones utilizan IA generativa y modelos de lenguaje grande (LLM) pre-entrenados para construir aplicaciones de IA transformadoras, diseñar nuevas características de productos, mejorar la productividad de ingeniería y aumentar la experiencia del cliente.

Sin embargo, la IA generativa y las LLM por sí solas no pueden garantizar el valor empresarial. Para crear un impacto empresarial tangible, la IA generativa debe aprovechar los datos curados para lograr unos resultados empresariales de calidad. Por lo tanto, las grandes empresas están recurriendo a un marco emergente y esencial conocido como generación aumentada de recuperación (RAG). En esta solución, presentamos una arquitectura para las organizaciones que no desean construir un gasoducto RAG. Esta solución puede ayudarle a desbloquear el valor de sus datos privados mediante la recuperación de información contextual a través de una canalización RAG privada.
