---
sidebar: sidebar 
permalink: ai/rag_nemo_ingest_netapp_data.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG con NetApp - Ingrese los datos de NetApp existentes con Nemo Retriever 
---
= Ingiera datos de NetApp existentes con Nemo Retriever
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
El microservicio Nemo Embedding, parte de NVIDIA Nemo Retriever, se puede utilizar para ingerir datos en la base de conocimiento/tienda de vectores RAG. Esta sección describe las tareas que deben realizarse para ingerir datos de orígenes de datos NetApp existentes.



== Ingerir datos mediante el bot de chat de muestra de NVIDIA

Puede ingerir archivos existentes mediante la aplicación web de bot de chat de ejemplo que implementa el operador de LLM de NVIDIA Enterprise RAG. El proceso de ingestión de archivos existentes mediante la aplicación web del bot de chat se describe en este link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f718b504-d89b-497e-bd25-b13400d0bfbf&start=57["vídeo de demostración."]



== Ingesta de datos mediante programación

Puede ingerir grandes cantidades de datos mediante programación mediante el servidor de consultas RAG que implementa el operador NVIDIA Enterprise RAG LLM.

La API del servidor de consultas RAG se expone automáticamente a través de un servicio Kubernetes como se muestra en la salida del siguiente comando.

[source]
----
$ kubectl -n rag-sample get service chain-server
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
chain-server   ClusterIP   10.233.28.129   <none>        8081/TCP   59d
----
De forma predeterminada, el tipo de servicio es ClusterIP, por lo que solo se puede acceder al punto final de la API desde el interior del clúster de Kubernetes. El tipo de servicio se puede cambiar modificando el `query.service.type` en la configuración de la tubería de helm (por ejemplo, helmpipeline_app.yaml).

Se puede acceder al esquema de Swagger del servidor API en `<chain_server_url>:<chain_server_api_port>/docs``.
