---
sidebar: sidebar 
permalink: ai/rag_nemo_data_protection.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: RAG empresarial con NetApp - Protección de datos de la base de conocimientos de RAG 
---
= Protección de datos de la base de conocimientos de RAG
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
A medida que las aplicaciones RAG se convierten en componentes clave de flujos de trabajo organizativos importantes, es fundamental proteger los almacenes vectoriales/bases de conocimientos que respaldan estas aplicaciones RAG. Es importante realizar backups de sus bases de datos vectoriales e implementar flujos de trabajo de recuperación ante desastres del mismo modo que lo haría con cualquier otra base de datos.



== Proteja su base de conocimientos Nemo RAG con las tecnologías de NetApp

Las tecnologías de NetApp, como link:https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html["Copias Snapshot"] y.. link:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-disaster-recovery-data-transfer-concept.html["Recuperación ante desastres con SnapMirror"], se puede utilizar para proteger su tienda de vectores / base de conocimiento. Para obtener más información sobre la protección de datos de bases de datos vectoriales, consulte la link:https://docs.netapp.com/us-en/netapp-solutions/ai/vector-database-solution-with-netapp.html["Documentación de la solución de base de datos vectorial de NetApp."]
