---
sidebar: sidebar 
permalink: ai/runai-ld_additional_information.html 
keywords: azure, lane, detection, additional, information, websites 
summary: Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y sitios web. 
---
= Información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Conjunto de datos: TuSimple
+
https://["https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection"^]

* Arquitectura de redes de aprendizaje profundo: Red neuronal convolucional espacial
+
https://["https://arxiv.org/abs/1712.06080"^]

* Marco de entrenamiento de aprendizaje profundo distribuido: Horovod
+
https://["https://horovod.ai/"^]

* EJECUCIÓN: Solución de orquestación de contenedores de IA: EJECUCIÓN: Introducción del producto de IA
+
https://["https://docs.run.ai/home/components/"^]

* EJECUCIÓN: Documentación de instalación de IA
+
https://["https://docs.run.ai/Administrator/Cluster-Setup/cluster-install/#step-3-install-runai"^] https://["https://docs.run.ai/Administrator/Researcher-Setup/cli-install/#runai-cli-installation"^]

* Envío de trabajos EN EJECUCIÓN: Interfaz de línea de comandos de IA
+
https://["https://docs.run.ai/Researcher/cli-reference/runai-submit/"^]

+
https://["https://docs.run.ai/Researcher/cli-reference/runai-submit-mpi/"^]

* Recursos de cloud para Azure: Azure NetApp Files
+
https://["https://docs.microsoft.com/azure/azure-netapp-files/"^]

* Servicio Azure Kubernetes
+
https://["https://azure.microsoft.com/services/kubernetes-service/-features"^]

* SKU de Azure VM
+
https://["https://azure.microsoft.com/services/virtual-machines/"^]

* Azure VM con SKU de GPU
+
https://["https://docs.microsoft.com/azure/virtual-machines/sizes-gpu"^]

* Trident de NetApp
+
https://["https://github.com/NetApp/trident/releases"^]

* Data Fabric con tecnología de NetApp
+
https://["https://www.netapp.com/data-fabric/what-is-data-fabric/"^]

* Documentación de productos de NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]


