---
sidebar: sidebar 
permalink: ai/tr-4807.html 
keywords:  
summary:  
---
= TR-4807: Arquitectura de referencia de IA de ONTAP de NetApp para cargas de trabajo de servicios financieros - Diseño de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, Sung-han Lin, NetApp Jacci Cenci, NVIDIA

[role="lead"]
Esta arquitectura de referencia ofrece directrices a los clientes que crean una infraestructura de inteligencia artificial con los sistemas NVIDIA DGX-1 y el almacenamiento AFF de NetApp para casos de uso con sectores financieros. Por ejemplo, incluye información sobre los flujos de trabajo de alto nivel utilizados en el desarrollo de modelos de aprendizaje profundo para los casos de pruebas y los resultados de servicios financieros. También incluye recomendaciones para el dimensionamiento de las puestas en marcha de los clientes.

link:https://www.netapp.com/pdf.html?item=/media/17205-tr4807pdf.pdf["TR-4807: Arquitectura de referencia de IA de ONTAP de NetApp para cargas de trabajo de servicios financieros - Diseño de la solución"^]
