---
sidebar: sidebar 
permalink: ai/tr-4811.html 
keywords:  
summary:  
---
= TR-4811: Arquitectura de referencia de IA ONTAP de NetApp para el sector sanitario: Imágenes de diagnóstico - diseño de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sung-han Lin, Sathish Thyagarajan, NetApp Jacci Cenci, NVIDIA

[role="lead"]
Esta arquitectura de referencia ofrece directrices para los clientes que crean una infraestructura de inteligencia artificial (IA) con sistemas NVIDIA DGX-2 y almacenamiento AFF de NetApp para casos de uso de sanidad. Incluye información sobre los flujos de trabajo de alto nivel utilizados en el desarrollo de modelos de aprendizaje profundo (DL) para imágenes de diagnóstico médico, casos de prueba validados y resultados. También incluye recomendaciones para el dimensionamiento de las puestas en marcha de los clientes.

link:https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["TR-4811: Arquitectura de referencia de IA ONTAP de NetApp para el sector sanitario: Imágenes de diagnóstico - diseño de la solución"^]
