---
sidebar: sidebar 
permalink: ai/tr-4785.html 
keywords:  
summary:  
---
= TR-4785: Puesta en marcha de IA con E-Series de NetApp y BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nagalakshmi Raju, Daniel Landas, Nathan Swartz, Amine Bennani, NetApp

[role="lead"]
Las aplicaciones de inteligencia artificial (IA), aprendizaje automático (ML, por sus siglas en inglés) y aprendizaje profundo (DL, por sus siglas en inglés) implican conjuntos de datos de gran tamaño y cálculos elevados. Para ejecutar estas cargas de trabajo con éxito, necesita una infraestructura ágil que le permita escalar horizontalmente tanto los nodos de almacenamiento como los de computación sin problemas. Este informe incluye los pasos para poner en marcha un modelo de entrenamiento de IA en un modo distribuido, que permite un escalado horizontal fluido de los nodos de computación y almacenamiento. El informe también incluye varios indicadores de rendimiento para mostrar cómo una solución, que combina el almacenamiento E-Series de NetApp con el sistema de archivos en paralelo BeeGFS, proporciona una solución flexible, rentable y sencilla para cargas de trabajo de IA.

link:https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf["TR-4785: Puesta en marcha de IA con E-Series de NetApp y BeeGFS"^]
