---
sidebar: sidebar 
permalink: ai/tr-4851-link.html 
keywords:  
summary:  
---
= TR-4851: Lago de datos de StorageGRID de NetApp para cargas de trabajo de conducción autónoma - Diseño de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette, NetApp

[role="lead"]
En el TR-4851 se muestra el uso del almacenamiento de objetos StorageGRID de NetApp como repositorio de datos y sistema de gestión para el desarrollo de software de aprendizaje automático (ML) y aprendizaje profundo (DL). Este documento describe el flujo de datos y los requisitos del desarrollo de software de vehículos autónomos y las funciones de StorageGRID que optimizan el ciclo de vida de los datos. Esta solución se aplica a cualquier flujo de trabajo de canalización de datos multietapa típico en los procesos de desarrollo DE APRENDIZAJE AUTOMÁTICO y aprendizaje profundo.

link:https://www.netapp.com/pdf.html?item=/media/19399-tr-4851.pdf["TR-4851: Lago de datos de StorageGRID de NetApp para cargas de trabajo de conducción autónoma - Diseño de la solución"^]
