---
sidebar: sidebar 
permalink: ai/tr-4799.html 
keywords:  
summary:  
---
= TR-4799-DESIGN: Arquitectura de referencia ONTAP AI de NetApp para cargas de trabajo de conducción autónoma
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette y Sung-han Lin, NetApp

[role="lead"]
La familia de sistemas NVIDIA DGX es la primera plataforma de inteligencia artificial (IA) integrada del mundo, específicamente diseñada para IA empresarial. Los sistemas de almacenamiento AFF de NetApp proporcionan un rendimiento extremo y funcionalidades de gestión de datos de cloud híbrido líderes en el sector. NetApp y NVIDIA se han asociado para crear la arquitectura de referencia de IA ONTAP de NetApp con el fin de ofrecer a los clientes una solución lista para usar que respalda cargas de trabajo DE IA y aprendizaje automático (ML) con rendimiento, fiabilidad y soporte de nivel empresarial.

link:https://www.netapp.com/pdf.html?item=/media/8554-tr4799designpdf.pdf["TR-4799-DESIGN: Arquitectura de referencia ONTAP AI de NetApp para cargas de trabajo de conducción autónoma"^]
