---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: Introducción a la solución de bases de datos vectoriales para NetApp 
---
= Introducción
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se ofrece una introducción a la solución de bases de datos vectoriales para NetApp.



== Introducción

Las bases de datos vectoriales abordan con eficacia los desafíos que están diseñados para manejar las complejidades de la búsqueda semántica en modelos de lenguaje grande (LLMs) y la inteligencia artificial generativa (IA). A diferencia de los sistemas tradicionales de gestión de datos, las bases de datos vectoriales son capaces de procesar y buscar a través de varios tipos de datos, incluyendo imágenes, vídeos, texto, audio, etc. y otras formas de datos no estructurados, usando el contenido de los datos en sí en lugar de etiquetas o etiquetas.

Las limitaciones de los sistemas de gestión de bases de datos relacionales (RDBMS) están bien documentadas, particularmente sus luchas con representaciones de datos de alta dimensión y datos no estructurados comunes en las aplicaciones de IA. Los RDBMS a menudo requieren un proceso largo y propenso a errores de aplanar los datos en estructuras más manejables, lo que conduce a retrasos e ineficiencias en las búsquedas. Las bases de datos vectoriales, sin embargo, están diseñadas para eludir estos problemas, ofreciendo una solución más eficiente y precisa para gestionar y buscar a través de datos complejos y de alta dimensión, facilitando así el avance de las aplicaciones de IA.

Este documento sirve como guía completa para los clientes que actualmente utilizan o planean usar bases de datos vectoriales, y detalla las mejores prácticas para utilizar bases de datos vectoriales en plataformas como NetApp ONTAP, NetApp StorageGRID, Amazon FSxN para NetApp ONTAP y SnapCenter. El contenido proporcionado aquí abarca una variedad de temas:

* Las directrices de infraestructura para bases de datos vectoriales, como Milvus, que proporciona el almacenamiento de NetApp mediante el almacenamiento de objetos de NetApp ONTAP y StorageGRID.
* Validación de la base de datos de Milvus en AWS FSx para NetApp ONTAP mediante almacén de archivos y objetos.
* Profundiza en la dualidad archivo-objeto de NetApp y demuestra su utilidad para datos en bases de datos vectoriales y otras aplicaciones.
* El producto de gestión de la protección de datos de NetApp, SnapCenter, ofrece funcionalidades de backup y restauración para datos de bases de datos vectoriales.
* Cómo el cloud híbrido de NetApp ofrece la replicación y la protección de datos en entornos locales y de cloud.
* Proporciona información sobre la validación del rendimiento de bases de datos vectoriales como Milvus y pgvector en NetApp ONTAP.
* Dos casos de uso específicos: Generación Aumentada de Recuperación (RAG) con Modelos de Lenguaje Grande (LLM) y ChatAI del equipo de TI DE NetApp, ofreciendo así ejemplos prácticos de los conceptos y prácticas esbozados.

