---
sidebar: sidebar 
permalink: ai/vector-database-conclusion.html 
keywords: vector database, conclusion 
summary: conclusión - solución de base de datos vectorial para NetApp 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En esta sección se concluye la solución de base de datos vectorial para NetApp.



== Conclusión

En conclusión, este documento ofrece una visión general completa para la puesta en marcha y la gestión de bases de datos vectoriales, como Milvus y pgvector, en las soluciones de almacenamiento de NetApp. Hemos tratado las directrices de infraestructura para aprovechar el almacenamiento de objetos NetApp ONTAP y StorageGRID y validado la base de datos de Milvus en AWS FSx para NetApp ONTAP mediante almacén de archivos y objetos.

Exploramos la dualidad archivo-objeto de NetApp, lo cual demuestra su utilidad no solo para datos en bases de datos vectoriales, sino también para otras aplicaciones. También hemos destacado cómo SnapCenter, el producto de gestión empresarial de NetApp, ofrece funcionalidades de backup, restauración y clonado para datos de bases de datos vectoriales, garantizando así la integridad y la disponibilidad de los datos.

El documento también analiza cómo la solución de cloud híbrido de NetApp ofrece la replicación y la protección de datos en entornos en las instalaciones y de cloud, lo que proporciona una experiencia de gestión de datos segura y fluida. Proporcionamos información sobre la validación del rendimiento de bases de datos vectoriales como Milvus y pgvecto en NetApp ONTAP, ofreciendo información valiosa sobre su eficiencia y escalabilidad.

Por último, hemos hablado de dos casos de uso de IA generativos: RAG con LLM y la ChatAI interna de NetApp. Estos ejemplos prácticos subrayan las aplicaciones y beneficios del mundo real de los conceptos y prácticas descritos en este documento. En general, este documento sirve como guía completa para cualquiera que desee aprovechar las potentes soluciones de almacenamiento de NetApp para la gestión de bases de datos vectoriales.



=== Reconocimientos

Al autor le gusta expresar su más sincero agradecimiento a los colaboradores que aparecen a continuación, a otros que han proporcionado sus comentarios y comentarios para que este documento sea valioso para los clientes de NetApp y los campos de NetApp.

. Sathish Thyagarajan, Ingeniero de Marketing Técnico, ONTAP AI & Analytics, NetApp
. Mike Oglesby, Ingeniero Técnico de Marketing de NetApp
. AJ Mahajan, director sénior de NetApp
. Joe Scott, director de ingeniería de rendimiento de cargas de trabajo de NetApp
. Puneet Dhawan, director sénior de gestión de productos FSx, NetApp
. Yuval Kalderon, director sénior de producto, Equipo de producto de FSx, NetApp




=== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Documentación de Milvus - https://milvus.io/docs/overview.md[]
* Documentación independiente de Milvus - https://milvus.io/docs/v2.0.x/install_standalone-docker.md[]
* Documentación de productos de NetApp
https://www.netapp.com/support-and-training/documentation/[]
* instaclustr - link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE["documentación de instalación"]




=== Historial de versiones

|===


| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Abril de 2024 | Versión inicial 
|===