---
sidebar: sidebar 
permalink: ai/vector-database-solution-overview.html 
keywords: Solution Overview vector database 
summary: Descripción general de la solución de bases de datos vectoriales para NetApp 
---
= Descripción general de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se proporciona una descripción general de la solución NetApp Vector Database.



== Descripción general de la solución

Esta solución muestra las funciones y las ventajas específicas que NetApp ofrece para hacer frente a los desafíos a los que se enfrentan los clientes de bases de datos vectoriales. Con NetApp ONTAP, StorageGRID, las soluciones cloud de NetApp y SnapCenter, los clientes pueden añadir un valor significativo a sus operaciones empresariales. Estas herramientas no solo abordan los problemas existentes, sino que también mejoran la eficiencia y la productividad, lo que contribuye al crecimiento global del negocio.



=== ¿Por qué elegir NetApp?

* Las ofertas de NetApp, como ONTAP y StorageGRID, permiten la separación del almacenamiento y de la computación, lo que permite una utilización óptima de los recursos en función de requisitos específicos. Esta flexibilidad permite a los clientes escalar de manera independiente su almacenamiento con las soluciones de almacenamiento de NetApp.
* Al aprovechar las controladoras de almacenamiento de NetApp, los clientes pueden servir datos de forma eficiente a su base de datos vectorial mediante los protocolos NFS y S3. Estos protocolos facilitan el almacenamiento de datos de los clientes y gestionan el índice de bases de datos vectoriales, lo que elimina la necesidad de contar con varias copias de los datos a las que se accede mediante métodos de objetos y archivos.
* NetApp ONTAP proporciona compatibilidad nativa para el almacenamiento NAS y de objetos en proveedores de servicios cloud líderes como AWS, Azure y Google Cloud. Esta amplia compatibilidad garantiza una integración perfecta, lo que permite la movilidad de datos del cliente, la accesibilidad global, la recuperación de desastres, la escalabilidad dinámica y el alto rendimiento.
* Con las sólidas capacidades de gestión de datos de NetApp, los clientes pueden estar seguros de que sus datos están bien protegidos frente a posibles riesgos y amenazas. NetApp da prioridad a la seguridad de los datos y ofrece tranquilidad a los clientes en lo que respecta a la seguridad e integridad de su información valiosa.

