---
sidebar: sidebar 
permalink: ai/vector-database-solution-verification-overview.html 
keywords: Solution Overview vector database 
summary: 'descripción general de la verificación de la solución: solución de bases de datos vectoriales para NetApp' 
---
= Descripción general de la solución
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Hemos realizado una completa validación de la solución centrada en cinco áreas clave, cuyos detalles se describen a continuación. Cada sección analiza los retos a los que se enfrentan los clientes, las soluciones ofrecidas por NetApp y las ventajas subsiguientes para el cliente.

. link:./vector-database-milvus-cluster-setup.html["Configuración de clúster de Milvus con Kubernetes en las instalaciones"]
Retos del cliente para escalar de manera independiente en el almacenamiento y la computación, una gestión de la infraestructura eficaz y la gestión de los datos. En esta sección detallamos el proceso de instalación de un clúster Milvus en Kubernetes, utilizando una controladora de almacenamiento de NetApp tanto para los datos de clúster como para los de cliente.
. link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html["Milvus con Amazon FSxN para NetApp ONTAP: Dualidad de archivos y objetos"]
En esta sección, ¿Por qué necesitamos implementar la base de datos vectorial en la nube?, así como los pasos para implementar la base de datos vectorial ( milvus standalone ) en Amazon FSxN para NetApp ONTAP dentro de contenedores docker.
. link:./vector-database-protection-using-snapcenter.html["Protección de bases de datos vectoriales mediante NetApp SnapCenter."]
En esta sección, profundizamos en cómo SnapCenter protege los datos de la base de datos vectorial y los datos de Milvus que residen en ONTAP. En este ejemplo, utilizamos un bucket NAS (milvusdbvol1) derivado de un volumen ONTAP NFS (vol1) para los datos de los clientes y un volumen NFS independiente (vectordbpv) para los datos de configuración del cluster Milvus.
. link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["Recuperación ante desastres con SnapMirror de NetApp"]
En esta sección trataremos la importancia de la recuperación ante desastres para las bases de datos vectoriales y cómo NetApp el producto de recuperación ante desastres snapmirror proporciona la solución de recuperación ante desastres para la base de datos vectorial.
. link:./vector-database-performance-validation.html["Validación del rendimiento"]
En este apartado, el objetivo es profundizar en la validación del rendimiento de las bases de datos vectoriales, como Milvus y pgvecto.rs, centrándose en sus características de rendimiento del almacenamiento, como el perfil de I/O y el comportamiento de la controladora de almacenamiento NetApp, para admitir cargas de trabajo de inferencia y RAG dentro del ciclo de vida del LLM. Evaluaremos e identificaremos cualquier diferenciación en el rendimiento cuando estas bases de datos se combinen con la solución de almacenamiento de ONTAP. Nuestro análisis se basará en indicadores clave de rendimiento, como el número de consultas procesadas por segundo (QPS).

