---
sidebar: sidebar 
permalink: ai/vector-database-solution-with-netapp.html 
keywords: vector database, milvus, usecases 
summary: Esta es una página abstracta para la solución de base de datos vectorial con NetApp. 
---
= Solución Vector Database con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam y Rodrigo Nascimento, NetApp

[role="lead"]
Este documento proporciona una exploración en profundidad de la puesta en marcha y la gestión de las bases de datos vectoriales, como Milvus y pgvecto, una extensión PostgreSQL de código abierto, mediante las soluciones de almacenamiento de NetApp. Detalla las directrices de infraestructura para usar el almacenamiento de objetos NetApp ONTAP y StorageGRID y valida la aplicación de la base de datos de Milvus en AWS FSx para NetApp ONTAP. El documento elucida la dualidad archivos-objetos de NetApp y su utilidad para aplicaciones y bases de datos vectoriales que admiten la incrustación de vectores. Enfatiza las capacidades de SnapCenter, el producto de gestión empresarial de NetApp, ofreciendo funcionalidades de backup y restauración para bases de datos vectoriales, garantizando así la integridad y la disponibilidad de los datos. En este documento se profundiza en la solución de cloud híbrido de NetApp y se habla de su papel en la replicación y la protección de datos en entornos locales y de cloud. Incluye información sobre la validación del rendimiento de las bases de datos vectoriales en NetApp ONTAP y concluye con dos casos de uso prácticos sobre IA generativa: RAG con LLM y ChatAI interna de NetApp. Este documento sirve como una guía completa para aprovechar las soluciones de almacenamiento de NetApp para la gestión de bases de datos vectoriales.

La arquitectura de referencia se centra en lo siguiente:

. link:./vector-database-introduction.html["Introducción"]
. link:./vector-database-solution-overview.html["Descripción general de la solución"]
. link:./vector-database-vector-database.html["Base de datos vectorial"]
. link:./vector-database-technology-requirement.html["Requisitos tecnológicos"]
. link:./vector-database-deployment-procedure.html["Procedimiento de Despliegue"]
. link:./vector-database-solution-verification-overview.html["Descripción general de la verificación de la solución"]
+
** link:./vector-database-milvus-cluster-setup.html["Configuración de clúster de Milvus con Kubernetes en las instalaciones"]
** link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html["Milvus con Amazon FSxN para NetApp ONTAP: Dualidad de archivos y objetos"]
** link:./vector-database-protection-using-snapcenter.html["Protección de bases de datos vectoriales mediante NetApp SnapCenter."]
** link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["Recuperación ante desastres con SnapMirror de NetApp"]
** link:./vector-database-performance-validation.html["Validación del rendimiento"]


. link:./vector-database-instaclustr-with-pgvector.html["Vector de base de datos con Instaclustr usando PostgreSQL: Pgvector"]
. link:./vector-database-use-cases.html["Casos de uso de bases de datos vectoriales"]
. link:./vector-database-conclusion.html["Conclusión"]
. link:./vector-database-values-yaml.html["Apéndice A: Valores.yaml"]
. link:./vector-database-prepare-data-netapp-new-py.html["Apéndice B: prepare_data_netapp_new.py"]
. link:./vector-database-verify-data-netapp-py.html["Apéndice C: verify_data_netapp.py"]
. link:./vector-database-docker-compose-xml.html["Apéndice D: docker-compose.yml"]

