---
sidebar: sidebar 
permalink: ai/wp-dgxc.html 
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing 
summary: NVIDIA DGX Cloud con Cloud Volumes ONTAP/ANF de NetApp 
---
= Servicios de datos en el cloud de NetApp para NVIDIA DGX Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Dave Arnette y Sathish Thyagarajan, NetApp

[role="lead"]
Gestión de datos avanzada para un superordenador de primera clase



== Introducción

En este documento se describe cómo pueden utilizar Cloud Volumes/ANF de NetApp para proporcionar funcionalidades avanzadas de gestión de datos junto con NVIDIA DGX Cloud para optimizar y optimizar las operaciones de canalización de datos de IA.



=== Asociación: NVIDIA, Microsoft y NetApp

DGX Cloud ofrece a los clientes acceso inmediato a un superordenador de IA desde un navegador web.  Con DGX Cloud, las empresas pueden acceder a la formación de IA de varios nodos a escala para acelerar el diseño de modelos complejos. Si las empresas deciden expandirse a la infraestructura local, pueden consolidar todos sus recursos para ofrecer una nube híbrida que aproveche BlueXP™ de NetApp y la plataforma de comandos base de NVIDIA, lo que proporciona a los desarrolladores una vista coherente de un solo panel.



=== DGX Cloud de NVIDIA

~nvidia para proporcionarnos qué contenido se debe agregar aquí



=== Microsoft Azure



=== BlueXP™ de NetApp



=== Azure NetApp Files®



=== Dualidad de objetos de archivos NetApp



== Arquitectura y configuración



=== Diseño/descripción general de la solución



=== Dibujo de arquitectura



=== Puesta en marcha de CVO/ANF

Con BlueXP



=== Configuración de la dualidad archivo/objeto

¿Automatizada mediante Ansible?



=== Conexión a DGXC



== Conclusión
