---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP 
permalink: cyber-vault/index.html 
summary: Cybervault de NetApp ONTAP, impulsado por SnapLock Compliance para la retención de datos inmutable e indeleble. 
---
= Ciberalmacén de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El ciberalmacén basado en ONTAP de NetApp ofrece a las organizaciones una solución completa y flexible para proteger sus activos de datos más importantes. Gracias a la separación lógica con metodologías de refuerzo sólidas, ONTAP permite crear entornos de almacenamiento aislados y seguros que son resilientes frente a ciberamenazas en constante evolución. Con ONTAP, puede garantizar la confidencialidad, la integridad y la disponibilidad de sus datos y mantener la agilidad y la eficiencia de su infraestructura de almacenamiento.


NOTE: A partir de julio de 2024, el contenido de informes técnicos previamente publicados como archivos PDF se integró con la documentación de los productos de ONTAP. Además, los nuevos informes técnicos (TRS) como este documento ya no obtendrán números TR.
