---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: cyber-vault/ontap-cyber-vault-interoperability.html 
summary: Interoperabilidad de Cyber vault 
---
= Interoperabilidad de Cyber vault
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El hardware y software de ONTAP se pueden usar para crear una configuración de ciberalmacén.



== Recomendaciones de hardware de ONTAP

Todas las cabinas físicas unificadas de ONTAP se pueden utilizar para la implementación de ciberalmacén.

* El almacenamiento híbrido de FAS ofrece la solución más rentable.
* La serie C de AFF ofrece el consumo de alimentación y la densidad más eficientes.
* AFF A-Series es la plataforma de mayor rendimiento que ofrece el mejor objetivo de tiempo de recuperación. Con el reciente anuncio de nuestra última serie AFF A, esta plataforma ofrecerá la mejor eficiencia del almacenamiento sin comprometer el rendimiento.




== Recomendaciones de software de ONTAP

A partir de ONTAP 9.14,1, puede especificar períodos de retención para etiquetas de SnapMirror específicas en la política de SnapMirror de la relación de SnapMirror, de modo que las copias Snapshot replicadas del volumen de origen al de destino se conserven durante el período de retención especificado en la regla. Si no se especifica ningún período de retención, se utiliza el período de retención predeterminado del volumen de destino.

A partir de ONTAP 9.13,1, puede restaurar al instante una copia Snapshot bloqueada en el volumen SnapLock de destino de una relación de almacén de SnapLock. Para ello, cree una FlexClone con la opción de tipo SnapLock configurada en «non-SnapLock» y especifique la copia Snapshot como la «snapshot principal» al ejecutar la operación de creación de clones de volúmenes. Más información sobre link:https://docs.netapp.com/us-en/ontap/volumes/create-flexclone-task.html?q=volume+clone["Creación de un volumen FlexClone con un tipo de SnapLock"^].



== Configuración de MetroCluster

Para las configuraciones de MetroCluster, debe tener en cuenta lo siguiente:

* Solo puede crear relaciones de SnapVault entre varias SVM sincronizada en origen, no entre una SVM sincronizada en origen y una SVM sincronizada en destino.
* Puede crear una relación de SnapVault entre un volumen en una SVM sincronizada en origen y una SVM que sirva datos.
* Puede crear una relación de SnapVault entre un volumen en una SVM que sirva datos y un volumen de DP en una SVM sincronizada en origen.

