---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-conclusion.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: Esta es la solución de NetApp ONTAP para configurar, reforzar y validar un ciberalmacén basado en ONTAP 
---
= Conclusión de la solución PowerShell de ciberalmacén de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Gracias a la separación de aire con sólidas metodologías de refuerzo proporcionadas por ONTAP, NetApp te permite crear un entorno de almacenamiento aislado y seguro resiliente frente a las ciberamenazas en constante evolución. Todo esto se logra al tiempo que se mantiene la agilidad y la eficiencia de la infraestructura de almacenamiento existente. Este acceso seguro permite a las empresas alcanzar sus estrictos objetivos de seguridad y tiempo de actividad con un cambio mínimo en el marco de trabajo de sus personas, procesos y tecnología existentes.

El ciberalmacén de ONTAP utiliza funciones nativas de ONTAP es un enfoque sencillo para obtener protección adicional y crear copias inalterables e indelebles de sus datos. Añadir cibervault basado en ONTAP de NetApp a la política de seguridad general:

* Cree un entorno que esté separado y desconectado de las redes de producción y copia de seguridad y restrinja el acceso de los usuarios a él.

