---
sidebar: sidebar 
permalink: automation/automation_introduction.html 
summary: La automatización de las soluciones de NetApp permite al cliente automatizar la puesta en marcha, la configuración y la ejecución de muchas tareas comunes de infraestructura y aplicaciones. 
keywords: netapp, solutions, automation, ansible, terraform 
---
= Automatización de soluciones de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/




== Introducción

Al ofrecer soluciones para los retos empresariales actuales, NetApp ofrece soluciones con los siguientes objetivos:

* Proporcionar pasos validados de instalación y configuración,
* Ofrece soluciones fáciles de consumibles,
* Ofrecer una puesta en marcha de una solución con un resultado previsible, se repite fácilmente y se puede escalar en toda la empresa del cliente.


Para poder alcanzar estos objetivos, es fundamental que la implementación y configuración de la infraestructura y/o las aplicaciones que ofrecemos a través de nuestras soluciones se simplifique mediante la automatización. NetApp se compromete a simplificar el consumo de soluciones mediante la automatización.

Las soluciones de NetApp, que utilizan herramientas de automatización de código abierto como Red Hat Ansible, HashiCorp Terraform o Microsoft PowerShell, tienen la capacidad de automatizar la puesta en marcha de aplicaciones, el aprovisionamiento del cloud, la gestión de la configuración y muchas otras tareas TECNOLÓGICAS comunes. Las soluciones de NetApp aprovechan los artefactos de automatización disponibles de forma pública, así como ofrecen la automatización escrita por NetApp, para simplificar la puesta en marcha general de una solución.

Cuando haya capacidades de automatización disponibles, el material complementario de la solución guiará al usuario a través del proceso de automatización de los pasos de la solución o de la solución a través de las herramientas de automatización específicas.
